Repository zyfra/Prizm, pull requests merged in 2023-12, with the labels that each got.

#1032 fix: progress status translations for file upload #931
  apps/doc/src/app/components/file-upload/examples/i18n/file-upload-i18n-example.component.html
  apps/doc/src/app/components/file-upload/examples/i18n/file-upload-i18n-example.component.ts
  apps/doc/src/app/how-to-work/internationalization/examples/language-switcher/language-switcher-example.component.html
  apps/doc/src/app/how-to-work/internationalization/examples/language-switcher/language-switcher-example.component.ts
  apps/doc/src/app/how-to-work/internationalization/internationalization.module.ts
  libs/components/src/lib/components/file-upload/file-upload-options.ts
  libs/components/src/lib/components/file-upload/file-upload.component.html
  libs/components/src/lib/components/file-upload/file-upload.component.ts
  libs/components/src/lib/components/file-upload/file-upload.enums.ts
  libs/components/src/lib/components/file-upload/pipes/file-size.pipe.ts
  libs/components/src/lib/components/file-upload/pipes/upload-status.pipe.ts
  libs/components/src/lib/components/file-upload/types.ts
  libs/i18n/src/lib/interfaces/language.ts
  libs/i18n/src/lib/languages/russian/file-upload.ts
Labels: ready, testing_done

#1060 feat: theme guide for developers #979
  apps/doc/src/app/guidelines/colors/colors.component.html
  apps/doc/src/app/guidelines/colors/colors.module.ts
  apps/doc/src/app/guidelines/colors/components/frame25826/frame25826.component.ts
  apps/doc/src/app/guidelines/colors/components/palette/palette.component.css
  apps/doc/src/app/guidelines/colors/components/palette/palette.component.html
  apps/doc/src/app/guidelines/colors/components/palette/palette.component.ts
  apps/doc/src/app/guidelines/colors/components/theme-colors/theme-colors.component.css
  apps/doc/src/app/guidelines/colors/components/theme-colors/theme-colors.component.html
  apps/doc/src/app/guidelines/colors/components/theme-colors/theme-colors.component.ts
  apps/doc/src/app/guidelines/theme/components/examples/custom-theme-css.md
  apps/doc/src/app/guidelines/theme/components/examples/custom-theme-inverted.md
  apps/doc/src/app/guidelines/theme/components/examples/custom-theme-palette.md
  apps/doc/src/app/guidelines/theme/components/examples/custom-theme-setup.md
  apps/doc/src/app/guidelines/theme/components/examples/custom-theme.md
  apps/doc/src/app/guidelines/theme/components/examples/setup-module.md
  apps/doc/src/app/guidelines/theme/components/examples/setup-styles.md
  apps/doc/src/app/guidelines/theme/components/examples/setup.md
  apps/doc/src/app/guidelines/theme/components/examples/style-variables.md
  apps/doc/src/app/guidelines/theme/components/examples/theme-reverse.md
  apps/doc/src/app/guidelines/theme/components/examples/theme-switcher.md
  apps/doc/src/app/guidelines/theme/components/examples/updated-palette.md
  apps/doc/src/app/guidelines/theme/components/theme-for-designers/theme-for-designers.component.html
  apps/doc/src/app/guidelines/theme/components/theme-for-designers/theme-for-designers.component.less
  apps/doc/src/app/guidelines/theme/components/theme-for-designers/theme-for-designers.component.ts
  apps/doc/src/app/guidelines/theme/components/theme-for-developers/theme-for-developers.component.html
  apps/doc/src/app/guidelines/theme/components/theme-for-developers/theme-for-developers.component.less
  apps/doc/src/app/guidelines/theme/components/theme-for-developers/theme-for-developers.component.ts
  apps/doc/src/app/guidelines/theme/theme-guide.component.html
  apps/doc/src/app/guidelines/theme/theme-guide.component.ts
  apps/doc/src/app/guidelines/theme/theme-guide.module.ts
  libs/theme/src/lib/directive/theme/const.ts
  libs/theme/src/lib/directive/theme/theme-inverted-values.service.ts
Labels: ready, testing_done

#1090 fix(components/dropdown-host): fix close logic #1074
  .github/workflows/pr-ng14.yml
  apps/doc/src/app/components/dropdowns/dropdown-host/dropdown-host.component.html
  apps/doc/src/app/components/dropdowns/dropdown-host/examples/date-list-edit/date-list-edit.component.html
  apps/doc/src/app/components/dropdowns/dropdown-host/examples/date-list-edit/date-list-edit.component.ts
  libs/components/src/lib/components/dropdowns/dropdown-host/dropdown-host.component.html
  libs/components/src/lib/components/dropdowns/dropdown-host/dropdown-host.component.ts
  libs/components/src/lib/components/input/carousel/carousel.component.ts
  libs/components/src/lib/directives/zone-event/zone-event.directive.ts
  libs/components/src/lib/directives/zone-event/zone-event.service.ts
  libs/helpers/src/lib/util/rxjs/rxjs.ts
Labels: ready, testing_done

#1094 fix(components/table): fix error when pass not observable value #1068
  libs/components/src/lib/components/table/table.service.ts
Labels: ready, testing_done

#1095 refactor: changed depedencies to actual standalone and fix doc #572
  apps/doc/src/app/components/input/input-chips/examples/input-chips-basic-example/input-chips-basic-example.component.html
  apps/doc/src/app/components/input/input-chips/examples/input-chips-outer-example/input-chips-outer-example.component.html
  libs/components/src/lib/components/chips/chips-item/chips-item.component.ts
  libs/components/src/lib/components/chips/chips.component.ts
  libs/components/src/lib/directives/element-ready/element-ready.directive.ts
  libs/components/src/lib/directives/element-ready/element-ready.module.ts
  libs/components/src/lib/directives/lifecycle/lifecycle.directive.ts
  libs/components/src/lib/directives/lifecycle/lifecycle.module.ts
Labels: ready, testing_done

#1096 fix(doc/dropdown-host): example with range components #893
  apps/doc/src/app/components/dropdowns/dropdown-host/examples/date-list-edit/date-list-edit.component.ts
Labels: ready, testing_done

#1097 feat(components/switcher): ability to change appearance #978
  apps/doc/src/app/components/switcher/examples/switcher-basic-example/switcher-basic-example.component.ts
  libs/components/src/lib/components/button/button.component.ts
  libs/components/src/lib/components/switcher/components/switcher-item/switcher-item.component.html
  libs/components/src/lib/components/switcher/components/switcher-item/switcher-item.component.ts
  libs/components/src/lib/components/switcher/switcher.interface.ts
Labels: ready, testing_done

#1114 feat(icons): divided location and less #1047
  apps/doc/src/app/how-to-work/for-developers/for-developers.component.ts
  libs/components/src/lib/components/table/table.service.ts
  libs/components/src/styles/icons-16/icons-16.less
  libs/components/src/styles/icons-16/location.less
  libs/components/src/styles/icons-16/set.less
  libs/components/src/styles/icons/icons.less
  libs/components/src/styles/icons/location.less
  libs/components/src/styles/icons/set.less
  libs/icons/base/src/styles/icon-location.less
  libs/icons/base/src/styles/icons-24/prizm-icons.css
  libs/icons/base/src/styles/styles.less
Labels: ready, testing_done

#1082 Feat/controls and calendars v3 color
  libs/components/src/lib/components/calendar-month/calendar-month.component.html
  libs/components/src/lib/components/calendar-month/calendar-month.component.less
  libs/components/src/lib/components/calendar-month/calendar-month.component.ts
  libs/components/src/lib/components/calendar-month/calendar-month.module.ts
  libs/components/src/lib/components/calendar-range/calendar-range.component.html
  libs/components/src/lib/components/calendar-range/calendar-range.component.less
  libs/components/src/lib/components/chips/chips.component.less
  libs/components/src/lib/components/data-list/data-list.component.less
  libs/components/src/lib/components/dropdowns/multi-select/input-multi-select.component.less
  libs/components/src/lib/components/dropdowns/select/input-select-item.component.less
  libs/components/src/lib/components/input/carousel/input-carousel.component.less
  libs/components/src/lib/components/input/common/input-icon-button/input-icon-button.component.less
  libs/components/src/lib/components/input/common/input-invalid-subtext/input-status-subtext.component.less
  libs/components/src/lib/components/input/common/input-layout/input-layout-textarea.component.less
  libs/components/src/lib/components/input/common/input-layout/input-layout.component.less
  libs/components/src/lib/components/input/common/styles/input.component.less
  libs/components/src/lib/components/input/input-date-multi/input-date-multi.component.html
  libs/components/src/lib/components/input/input-date-multi/input-date-multi.component.less
  libs/components/src/lib/components/input/input-date-multi/input-date-multi.component.ts
  libs/components/src/lib/components/input/input-date-range/input-date-range.component.ts
  libs/components/src/lib/components/input/input-date-relative/input-layout-date-relative.component.html
  libs/components/src/lib/components/input/input-date-relative/input-layout-date-relative.component.less
  libs/components/src/lib/components/input/input-date-relative/input-layout-date-relative.component.ts
  libs/components/src/lib/components/input/input-date-time/input-layout-date-time.component.html
  libs/components/src/lib/components/input/input-date-time/input-layout-date-time.component.less
  libs/components/src/lib/components/input/input-date-time/input-layout-date-time.component.ts
  libs/components/src/lib/components/input/input-date/input-layout-date-shared.component.less
  libs/components/src/lib/components/input/input-date/input-layout-date.component.less
  libs/components/src/lib/components/input/input-month-range/input-month-range.module.ts
  libs/components/src/lib/components/input/input-password/input-password-auxiliary-control.component.ts
  libs/components/src/lib/components/input/input-password/input-password.directive.ts
  libs/components/src/lib/components/input/input-text/input-textarea.component.less
  libs/components/src/lib/components/input/input-time/input-layout-time.component.html
  libs/components/src/lib/components/input/input-time/input-layout-time.component.less
  libs/components/src/lib/components/input/input-time/input-layout-time.component.ts
  libs/components/src/lib/components/internal/primitive-calendar-range/primitive-calendar-range.component.html
  libs/components/src/lib/components/internal/primitive-calendar-range/primitive-calendar-range.component.less
  libs/components/src/lib/components/internal/primitive-calendar/primitive-calendar.component.html
  libs/components/src/lib/components/internal/primitive-calendar/primitive-calendar.component.less
  libs/components/src/lib/components/internal/primitive-month-picker/primitive-month-picker.component.less
  libs/components/src/lib/components/internal/primitive-spin-button/primitive-spin-button.component.less
  libs/components/src/lib/components/internal/primitive-spin-button/primitive-spin-button.component.ts
  libs/components/src/lib/components/internal/primitive-spin-button/primitive-spin-button.template.html
  libs/components/src/lib/components/internal/primitive-year-month-pagination/primitive-year-month-pagination.component.html
  libs/components/src/lib/components/internal/primitive-year-month-pagination/primitive-year-month-pagination.component.less
  libs/components/src/lib/components/internal/primitive-year-month-pagination/primitive-year-month-pagination.module.ts
  libs/components/src/lib/components/internal/primitive-year-picker/primitive-year-picker.component.less
  libs/components/src/lib/components/listing-item/listing-item.component.less
  libs/components/src/styles/mixins/mixins.less
  libs/components/src/styles/mixins/picker.less
Labels: ready, testing_done

#1121 feat: columns settings v3 colors #1104
  libs/components/src/lib/components/column-settings/column-settings.component.html
  libs/components/src/lib/components/column-settings/column-settings.component.less
  libs/components/src/lib/components/column-settings/column-settings.component.ts
  libs/components/src/lib/components/column-settings/components/column-drop-list/column-drop-list.component.html
  libs/components/src/lib/components/column-settings/components/column-drop-list/column-drop-list.component.less
  libs/components/src/lib/components/column-settings/components/column-drop-list/column-drop-list.component.ts
  libs/components/src/lib/components/dropdowns/dropdown-host/dropdown-host.component.less
  libs/components/src/lib/components/listing-item/listing-item.component.less
  libs/theme/src/styles/theme/v3/dark.less
  libs/theme/src/styles/theme/v3/default.less
Labels: ready, testing_done

#1103 feat: table colors update to v3 #1093
  apps/doc/src/app/components/table/examples/table-editable-col-example/table-editable-col-example.component.html
  apps/doc/src/app/components/table/examples/table-editable-col-example/table-editable-col-example.component.less
  apps/doc/src/app/components/table/examples/table-editable-row-example/table-editable-row-example.component.less
  apps/doc/src/app/components/table/examples/table-search-example/table-search-example.component.html
  apps/doc/src/app/components/table/examples/table-search-example/table-search-example.component.less
  apps/doc/src/app/components/table/examples/table-track-by-example/table-track-by-example.component.html
  apps/doc/src/app/components/table/table-example.component.html
  apps/doc/src/app/components/table/table-example.component.ts
  apps/doc/src/app/how-to-work/internationalization/examples/language-switcher/language-switcher-example.component.ts
  libs/components/src/lib/components/input/common/input-layout/input-layout.component.less
  libs/components/src/lib/components/table/components/searchable-content/searchable-content.component.ts
  libs/components/src/lib/components/table/tbody/tbody.component.less
  libs/components/src/lib/components/table/td/td.component.less
  libs/components/src/lib/components/table/th/th.style.less
  libs/components/src/lib/components/table/tr/tr.component.less
Labels: ready, testing_done

#1131 feat: dialogs colors update to v3 #1129
  libs/components/src/lib/components/dialogs/confirm-dialog/confirm-dialog.component.less
  libs/components/src/lib/components/dialogs/dialog/dialog.component.html
  libs/components/src/lib/components/dialogs/dialog/dialog.component.less
Labels: ready, testing_done

#1126 feat: colors update for cron #1124
  apps/doc/src/app/components/cron-human-readable/examples/base/cron-base-example.component.html
  apps/doc/src/app/components/cron-human-readable/examples/base/cron-base-example.component.ts
  apps/doc/src/app/components/cron-human-readable/examples/func/cron-func-example.component.html
  apps/doc/src/app/components/cron-human-readable/examples/func/cron-func-example.component.ts
  libs/components/src/lib/components/cron/components/carousel/carousel.component.less
  libs/components/src/lib/components/cron/components/schedule/schedule.component.less
  libs/components/src/lib/components/cron/cron.component.html
  libs/components/src/lib/components/cron/cron.component.less
  libs/components/src/lib/components/input/common/input-icon-button/input-icon-button.component.less
  libs/components/src/lib/components/input/common/input-layout/input-layout.component.less
Labels: ready, testing_done

#1139 feat: error page colors update #1138
  apps/doc/src/app/components/error-page/examples/base/base.component.ts
  libs/components/src/lib/components/error-page/error-page.component.less
Labels: ready, testing_done

#1159 feat: widget and splitter v3 colors
  apps/doc/src/app/components/splitter/examples/areas-control-display-none/areas-control-display-none.component.html
  apps/doc/src/app/components/splitter/examples/areas-control-ngif/areas-control-ngif.component.less
  apps/doc/src/app/components/splitter/examples/areas-control-size/areas-control-size.component.html
  apps/doc/src/app/components/splitter/examples/areas-control-size/areas-control-size.component.less
  apps/doc/src/app/components/splitter/examples/basic/basic.component.less
  apps/doc/src/app/components/splitter/examples/limit-size/limit-size.component.less
  apps/doc/src/app/components/splitter/examples/vertical/vertical.component.less
  libs/components/src/lib/components/grid/components/grid-item/grid-item.component.less
  libs/components/src/lib/components/splitter/gutter/gutter-default.component.less
  libs/components/src/lib/components/splitter/splitter.component.less
  libs/components/src/lib/components/widget/widget.component.less
Labels: ready, testing_done

#1161 feat: update colors for stepper #1153
  libs/components/src/lib/components/stepper/stepper-selector.component.html
  libs/components/src/lib/components/stepper/stepper-selector.component.less
  libs/components/src/lib/components/stepper/stepper.component.less
  libs/components/src/lib/components/stepper/stepper.component.ts
Labels: ready, testing_done

#1217 feat: cache to artifacts
  .github/workflows/beta-publish-ng14.yml
  .github/workflows/beta-publish-ng15.yml
  .github/workflows/beta-publish-ng16.yml
  .github/workflows/main-publish-ng14.yml
  .github/workflows/main-publish-ng15.yml
  .github/workflows/main-publish-ng16.yml
  .github/workflows/pre-release-publish-ng14.yml
  .github/workflows/pre-release-publish-ng15.yml
  .github/workflows/pre-release-publish-ng16.yml
Labels: devOnly, ready for dev

#1208 fix(components/input-layout-date-time): after clear set state #1076
  libs/components/src/lib/components/input/input-date-time/input-layout-date-time.component.ts
Labels: ready, testing_done

#1204 fix: issue 952
  apps/doc/src/app/components/input/input-date-multi/examples/four/input-date-multi-four-example.component.html
Labels: ready, testing_done

#1198 fix(components/calendar): scroll in to view in year/month pickers #760
  .github/workflows/beta-publish-ng14.yml
  .github/workflows/beta-publish-ng15.yml
  .github/workflows/beta-publish-ng16.yml
  .github/workflows/beta-released.yml
  .github/workflows/pre-released.yml
  .github/workflows/released.yml
  libs/components/src/lib/components/calendar-month/calendar-month.component.ts
  libs/components/src/lib/components/internal/primitive-month-picker/primitive-month-picker.component.ts
  libs/components/src/lib/components/internal/primitive-year-month-pagination/primitive-year-month-pagination.component.ts
  libs/components/src/lib/components/internal/primitive-year-picker/primitive-year-picker.component.ts
  libs/components/src/lib/components/internal/primitive-year-picker/primitive-year-picker.module.ts
  libs/components/src/lib/components/scrollbar/scrollbar.component.ts
  libs/components/src/lib/directives/hovered/hovered.directive.ts
  libs/components/src/lib/directives/hovered/hovered.module.ts
  libs/components/src/lib/directives/mutation-observer/mutation-observer.directive.ts
  libs/components/src/lib/directives/mutation-observer/mutation-observer.module.ts
  libs/components/src/lib/directives/native-value/input-native-value.directive.ts
  libs/components/src/lib/directives/native-value/input-native-value.module.ts
  libs/components/src/lib/directives/overscroll/overscroll.directive.ts
  libs/components/src/lib/directives/overscroll/overscroll.module.ts
  libs/components/src/lib/directives/pressed/pressed.directive.ts
  libs/components/src/lib/directives/pressed/pressed.module.ts
  libs/components/src/lib/directives/prevent-default/prevent-default.directive.ts
  libs/components/src/lib/directives/prevent-default/prevent-default.module.ts
  libs/components/src/lib/directives/scroll-into-view/scroll-into-view.directive.ts
  libs/components/src/lib/directives/scroll-into-view/scroll-into-view.module.ts
  libs/components/src/lib/directives/shadow/shadow.directive.ts
  libs/components/src/lib/directives/shadow/shadow.module.ts
  libs/components/src/lib/directives/skeleton/skeleton.directive.ts
  libs/components/src/lib/directives/skeleton/skeleton.module.ts
  libs/icons/base/src/styles/icons-24/prizm-icons.less
  libs/icons/base/src/styles/styles.less
  libs/icons/flags/src/styles/font/prizm-flag-icons.less
  libs/icons/flags/src/styles/styles.less
  libs/theme/src/styles/font.less
Labels: ready, testing_done

#1194 fix: hide breaking in table till 4.0
  apps/doc/src/app/components/table/examples/table-editable-col-example/table-editable-col-example.component.less
  apps/doc/src/app/components/table/examples/table-editable-row-example/table-editable-row-example.component.less
  libs/components/src/lib/components/table/td/td.component.less
  libs/components/src/lib/components/table/th/th.style.less
Labels: ready, ready for dev, testing_done

#1191 fix(components): added empty initializer for all query list
  libs/components/src/lib/components/accordion/accordion.component.ts
  libs/components/src/lib/components/breadcrumbs/breadcrumbs.component.ts
  libs/components/src/lib/components/grid/grid.component.ts
  libs/components/src/lib/components/navigation-menu/components/prizm-navigation-menu-items/prizm-navigation-menu-items.component.ts
  libs/components/src/lib/components/navigation-menu/components/prizm-navigation-menu/prizm-navigation-menu.component.ts
  libs/components/src/lib/components/slider/slider.component.ts
  libs/components/src/lib/components/splitter/splitter.component.ts
  libs/components/src/lib/components/stepper/stepper-selector.component.ts
  libs/components/src/lib/components/stepper/stepper.component.ts
  libs/components/src/lib/components/table/directives/sort-by.directive.ts
  libs/components/src/lib/components/table/tbody/tbody.component.ts
  libs/components/src/lib/components/table/th-group/th-group.component.ts
  libs/components/src/lib/components/table/tr/tr.component.ts
  libs/components/src/lib/components/tabs/tabs.component.ts
  libs/doc/base/src/lib/components/documentation/documentation.component.ts
  libs/doc/base/src/lib/components/page/page.component.ts
  libs/helpers/src/lib/util/common.ts
Labels: ready, testing_done

#1176 feat: tree colors update #1162
  apps/doc/src/app/components/tree/examples/active-color/tree-active-color-example.component.ts
  apps/doc/src/app/components/tree/examples/base/tree-base-example.component.ts
  apps/doc/src/app/components/tree/examples/component/folder.component.less
  apps/doc/src/app/components/tree/examples/in-modal/tree-in-modal-example.component.ts
  apps/doc/src/app/components/tree/examples/lazy/tree-template-lazy-example.component.ts
  apps/doc/src/app/components/tree/examples/lazy/tree-template-lazy-example.module.ts
  apps/doc/src/app/components/tree/examples/template-checkbox/tree-template-example.module.ts
  libs/components/src/lib/components/tree/components/tree-item-content/tree-item-content.component.less
  libs/components/src/lib/components/tree/components/tree-item/tree-item.component.less
Labels: ready, ready for dev, testing_done

#1171 fix: switcher active state colors #1168
  libs/components/src/lib/components/switcher/components/switcher-item/switcher-item.component.html
  libs/components/src/lib/components/switcher/components/switcher-item/switcher-item.component.less
Labels: ready, ready for dev, testing_done

#1170 feat: navigation-menu colors update #1151
  apps/doc/src/app/components/navigation-menu/examples/navigation-menu-basic-example/navigation-menu-basic-example.component.less
  apps/doc/src/app/components/navigation-menu/examples/navigation-menu-children-handler-example/navigation-menu-children-handler-example.component.less
  apps/doc/src/app/components/navigation-menu/examples/navigation-menu-groups-example/navigation-menu-groups-example.component.less
  apps/doc/src/app/components/navigation-menu/examples/navigation-menu-one-mode-example/navigation-menu-one-mode-example.component.less
  libs/components/src/lib/components/navigation-menu/components/prizm-navigation-menu-group/prizm-navigation-menu-group.component.html
  libs/components/src/lib/components/navigation-menu/components/prizm-navigation-menu-group/prizm-navigation-menu-group.component.less
  libs/components/src/lib/components/navigation-menu/components/prizm-navigation-menu-item/prizm-navigation-menu-item.component.less
  libs/components/src/lib/components/navigation-menu/components/prizm-navigation-menu-search/prizm-navigation-menu-search.component.html
  libs/components/src/lib/components/navigation-menu/components/prizm-navigation-menu-search/prizm-navigation-menu-search.component.less
  libs/components/src/lib/components/navigation-menu/components/prizm-navigation-menu-search/prizm-navigation-menu-search.component.ts
  libs/components/src/lib/components/navigation-menu/components/prizm-navigation-menu-toolbar/prizm-navigation-menu-toolbar.component.html
  libs/components/src/lib/components/navigation-menu/components/prizm-navigation-menu-toolbar/prizm-navigation-menu-toolbar.component.less
  libs/components/src/lib/components/navigation-menu/components/prizm-navigation-menu-toolbar/prizm-navigation-menu-toolbar.component.ts
  libs/components/src/lib/components/navigation-menu/components/prizm-navigation-menu/prizm-navigation-menu.component.less
  libs/components/src/lib/components/navigation/components/prizm-navigation-item-simple/prizm-navigation-item-simple.component.html
Labels: ready, testing_done

#1136 feat: update colors to sidebar #1135
  libs/components/src/lib/components/dialogs/confirm-dialog/confirm-dialog.component.less
  libs/components/src/lib/components/dialogs/dialog/dialog.component.less
  libs/components/src/lib/components/dialogs/sidebar/sidebar.component.html
  libs/components/src/lib/components/dialogs/sidebar/sidebar.component.less
Labels: ready, testing_done

#1145 feat: file upload v3 colors
  libs/components/src/lib/components/file-upload/file-upload.component.html
  libs/components/src/lib/components/file-upload/file-upload.component.less
  libs/components/src/styles/skeleton/skeleton.less
Labels: ready, testing_done

#1156 Feat/doc old icons with number
  apps/doc/src/app/components/icons/old/icon.component.html
  apps/doc/src/app/components/icons/old/icon.component.ts
Labels: ready, testing_done

#1157 feat(doc/input): added example with counter #499
  apps/doc/src/app/components/input/input-text/examples/input-subtext-example/input-subtext-example.component.html
  apps/doc/src/app/components/input/input-text/examples/input-subtext-example/input-subtext-example.component.ts
  libs/components/src/lib/components/input/common/input-layout/input-layout.component.less
Labels: ready, testing_done

#1207 fix(components/table): fix error in DI #1141
  libs/components/src/lib/components/table/directives/table.directive.ts
Labels: ready, devOnly

#1158 chore: update tokens for v3 themes
  libs/theme/src/styles/theme/v3/dark-palette.less
  libs/theme/src/styles/theme/v3/dark.less
  libs/theme/src/styles/theme/v3/default-palette.less
  libs/theme/src/styles/theme/v3/default.less
  libs/theme/src/styles/theme/v3/index.less
  libs/theme/src/styles/theme/v3/palette.less
Labels: devOnly

#1206 fix(components/input-multi-select): re render fix #1048
  .nx/cache/file-map.json
  .nx/cache/lockfile.hash
  .nx/cache/parsed-lock-file.json
  .nx/cache/project-graph.json
  libs/components/src/lib/components/chips/chips.component.html
  libs/components/src/lib/components/chips/chips.component.ts
  libs/components/src/lib/components/dropdowns/multi-select/input-multi-select.component.html
  libs/components/src/lib/components/dropdowns/multi-select/input-multi-select.component.ts
Labels: ready, testing_done

#1205 fix(components/input-select): fix style #946
  apps/doc/src/app/components/input/input-select/input-select.component.html
  apps/doc/src/app/components/input/input-select/input-select.component.less
Labels: ready, testing_done

#1192 fix(components/input-select): show placeholder #1187 #1038
  apps/doc/src/app/components/table/examples/table-editable-row-example/table-editable-row-example.component.html
  apps/doc/src/app/components/table/examples/table-editable-row-example/table-editable-row-example.component.ts
  apps/doc/src/app/components/table/table-example.module.ts
  libs/components/src/lib/components/dropdowns/dropdown-host/dropdown-host.component.ts
  libs/components/src/lib/components/dropdowns/multi-select/input-multi-select.component.html
  libs/components/src/lib/components/dropdowns/multi-select/input-multi-select.component.ts
  libs/components/src/lib/components/dropdowns/select/input-select.component.html
  libs/components/src/lib/components/dropdowns/select/input-select.component.ts
  libs/components/src/lib/components/input/common/base/input-ng-control.class.ts
  libs/components/src/lib/components/input/common/input-layout/input-layout.component.ts
  libs/components/src/lib/components/input/input-date-range/input-layout-date-range.component.html
  libs/components/src/lib/components/input/input-date-range/input-layout-date-range.component.ts
  libs/components/src/lib/components/input/input-date-relative/input-layout-date-relative.component.html
  libs/components/src/lib/components/input/input-date-time-range/input-layout-date-time-range.component.html
  libs/components/src/lib/components/input/input-date-time-range/input-layout-date-time-range.component.ts
  libs/components/src/lib/components/input/input-date-time/input-layout-date-time.component.html
  libs/components/src/lib/components/input/input-date-time/input-layout-date-time.component.ts
  libs/components/src/lib/components/input/input-date/input-layout-date.component.html
  libs/components/src/lib/components/input/input-month-range/input-layout-month-range.component.html
  libs/components/src/lib/components/input/input-month/input-layout-month.component.html
  libs/components/src/lib/components/input/input-time/input-layout-time.component.html
Labels: ready, testing_done

#1229 fix: artifact download folder in beta release
  .github/workflows/beta-publish-ng14.yml
  .github/workflows/beta-publish-ng15.yml
  .github/workflows/beta-publish-ng16.yml
Labels: ready, devOnly

#1227 feat(components/navigation): search lower case #1214
  libs/components/src/lib/components/navigation-menu/components/prizm-navigation-menu/prizm-navigation-menu.component.ts
  libs/components/src/lib/components/navigation-menu/services/prizm-navigation-menu-group.service.ts
Labels: ready, testing_done

#1200 feat: update colors for shadow #1199
  libs/components/src/lib/directives/shadow/models.ts
  libs/components/src/lib/modules/overlay/overlay.component.less
Labels: ready, testing_done

#1228 fix: artifact dowload folder in next release
  .github/workflows/pre-release-publish-ng14.yml
  .github/workflows/pre-release-publish-ng15.yml
  .github/workflows/pre-release-publish-ng16.yml
Labels: ready, devOnly

#1233 feat(components/sidebar): added ability to control scrollbar visibility #780
  apps/doc/src/app/components/dialogs/confirm-dialog/confirm.component.html
  apps/doc/src/app/components/dialogs/confirm-dialog/confirm.component.ts
  apps/doc/src/app/components/dialogs/dialog/dialog-example.component.html
  apps/doc/src/app/components/dialogs/dialog/dialog-example.component.ts
  apps/doc/src/app/components/dialogs/sidebar/sidebar.component.html
  apps/doc/src/app/components/dialogs/sidebar/sidebar.component.ts
  apps/doc/src/app/components/scrollbar/scrollbar.component.html
  libs/components/src/lib/components/dialogs/confirm-dialog/confirm-dialog.component.html
  libs/components/src/lib/components/dialogs/confirm-dialog/confirm-dialog.models.ts
  libs/components/src/lib/components/dialogs/dialog/dialog.component.html
  libs/components/src/lib/components/dialogs/dialog/dialog.models.ts
  libs/components/src/lib/components/dialogs/sidebar/sidebar.component.html
  libs/components/src/lib/components/dialogs/sidebar/sidebar.component.ts
  libs/components/src/lib/components/dialogs/sidebar/sidebar.models.ts
Labels: ready, testing_done

#1249 feat: added css variable for tab max-width #1244
  apps/doc/src/app/components/tabs/tabs-example.component.html
  apps/doc/src/app/components/tabs/tabs-example.component.ts
  libs/components/src/lib/components/tabs/components/tab.component.less
Labels: ready, ready for test, ready for dev, testing_done

#1273 fix(components/input-date-time): date update #1263
  libs/components/src/lib/components/input/input-date-time/input-layout-date-time.component.ts
Labels: ready, ready for test, testing_done

#1230 feat(components/textarea): show placeholder #357
  apps/doc/src/app/components/input/input-number/input-number-example.component.html
  apps/doc/src/app/components/input/input-number/input-number-example.component.ts
  apps/doc/src/app/components/input/input-select/input-select.component.html
  apps/doc/src/app/components/input/input-text/input.component.html
  apps/doc/src/app/components/input/input-text/input.component.ts
  apps/doc/src/app/components/input/textarea/textarea-example.component.html
  apps/doc/src/app/components/input/textarea/textarea-example.component.ts
  apps/doc/src/app/components/input/textarea/textarea-example.module.ts
  libs/components/src/lib/components/input/common/styles/input.component.less
  libs/components/src/lib/components/input/input-number/input-number.component.ts
  libs/components/src/lib/components/input/input-text/input-text.component.ts
  libs/components/src/lib/components/input/input-text/input-textarea.component.less
Labels: ready, ready for test, testing_done

#1237 fix: input number min/max should apply for manual input values
  libs/components/src/lib/components/input/input-number/input-number.component.ts
Labels: ready for test

#1253 fix: none-status tokens updated for dark theme
  libs/theme/src/styles/theme/v3/dark.less
Labels: ready, ready for test, testing_done

#1268 feat: update toggle styles #1169
  libs/components/src/lib/components/toggle/toggle.component.less
Labels: ready, ready for test, testing_done

#1262 feat: navigation v3 colors #1186
  apps/doc/src/app/components/navigation/examples/navigation-basic-example/navigation-basic-example.component.less
  libs/components/src/lib/components/header/components/prizm-header-dropdown/prizm-header-dropdown.component.less
  libs/components/src/lib/components/header/components/prizm-header-module-btn/prizm-header-module-btn.component.less
  libs/components/src/lib/components/header/prizm-header.component.less
  libs/components/src/lib/components/navigation/components/prizm-navigation-item-expandable/prizm-navigation-item-expandable.component.html
  libs/components/src/lib/components/navigation/components/prizm-navigation-item-expandable/prizm-navigation-item-expandable.component.less
  libs/components/src/lib/components/navigation/components/prizm-navigation-item-simple/prizm-navigation-item-simple.component.less
Labels: ready, ready for test, testing_done

#1274 feat(components/input-zone): add hook on update value and fix bug #1092
  apps/doc/src/app/components/input/input-layout-date-range/examples/base/input-layout-date-range-base-example.component.html
  libs/components/src/lib/components/input/input-date-range/input-layout-date-range.component.html
  libs/components/src/lib/components/input/input-date-range/input-layout-date-range.component.ts
  libs/components/src/lib/directives/input-zone/input-in-zone.directive.ts
  libs/components/src/lib/directives/input-zone/input-zone.directive.ts
Labels: ready, ready for test, testing_done

#1277 feat(components/sticky): update on changes #1085
  libs/components/src/lib/directives/sticky/sticky-relative.service.ts
  libs/components/src/lib/directives/sticky/sticky.directive.ts
Labels: ready, ready for test, testing_done

#1276 feat(component/event-zone): directive to standalone #1260
  libs/components/src/lib/directives/event-zone/event-zone.directive.ts
  libs/components/src/lib/directives/event-zone/event-zone.module.ts
Labels: devOnly

#1275 fix(components/input-date-time): min max limit #488
  apps/doc/src/app/components/input/input-layout-date-range/examples/base/input-layout-date-range-base-example.component.html
  libs/components/src/lib/@core/date-time/day-range.ts
  libs/components/src/lib/components/input/input-date-range/input-layout-date-range.component.ts
  libs/components/src/lib/components/input/input-date-time/input-layout-date-time.component.html
  libs/components/src/lib/components/input/input-date-time/input-layout-date-time.component.ts
Labels: ready, ready for test, testing_done
