Repository zyfra/Prizm, pull requests merged in 2023-10, with the labels that each got.

#767 fix(doc/repo): outdated links removed
  apps/doc/src/app/about-prizm/repositories/repositories.component.html
Labels: ready

#764 fix(doc/live-demo): dark theme color fix #758
  libs/doc/base/src/lib/components/documentation/documentation.style.less
Labels: ready

#770 fix: ci names of task
  apps/doc/src/app/app.component.ts
  libs/ast/cb3-code-examples/src/lib/tasks/accordion.task.ts
  libs/ast/cb3-template-examples/src/lib/v1-v2-remove-deprecated/input-multi-select.task.ts
  package.json
Labels: devOnly

#789 feat: new theme added
  libs/theme/src/styles/theme/index.less
  libs/theme/src/styles/theme/v3/dark-palette.less
  libs/theme/src/styles/theme/v3/dark.less
  libs/theme/src/styles/theme/v3/default-palette.less
  libs/theme/src/styles/theme/v3/default.less
  libs/theme/src/styles/theme/v3/index.less
Labels: devOnly

#763 feat(components/column-settings): add new feature
  apps/doc/src/app/components/sticky/sticky.component.html
  apps/doc/src/app/components/table/examples/table-column-settings-example/pipes/column-sticky-pipe.pipe.ts
  apps/doc/src/app/components/table/examples/table-column-settings-example/pipes/header-sticky-pipe.pipe.ts
  apps/doc/src/app/components/table/examples/table-column-settings-example/table-column-settings-example.component.html
  apps/doc/src/app/components/table/examples/table-column-settings-example/table-column-settings-example.component.less
  apps/doc/src/app/components/table/examples/table-column-settings-example/table-column-settings-example.component.ts
  apps/doc/src/app/components/table/table-example.component.html
  apps/doc/src/app/components/table/table-example.component.ts
  apps/doc/src/app/components/table/table-example.module.ts
  libs/components/src/lib/components/column-settings/column-settings.component.html
  libs/components/src/lib/components/column-settings/column-settings.component.less
  libs/components/src/lib/components/column-settings/column-settings.component.spec.ts
  libs/components/src/lib/components/column-settings/column-settings.component.ts
  libs/components/src/lib/components/column-settings/column-settings.model.ts
  libs/components/src/lib/components/column-settings/column-settings.module.ts
  libs/components/src/lib/components/column-settings/components/column-drop-list/column-drop-list.component.html
  libs/components/src/lib/components/column-settings/components/column-drop-list/column-drop-list.component.less
  libs/components/src/lib/components/column-settings/components/column-drop-list/column-drop-list.component.ts
  libs/components/src/lib/components/column-settings/index.ts
  libs/components/src/lib/components/column-settings/pipes/column-icon.pipe.ts
  libs/components/src/lib/components/index.ts
  libs/components/src/lib/components/table/th-group/th-group.component.ts
  libs/components/src/lib/components/table/th/th.style.less
  libs/components/src/lib/directives/sticky/sticky.directive.ts
  libs/components/src/lib/tokens/i18n.ts
  libs/helpers/src/lib/util/rxjs/move.spec.ts
  libs/helpers/src/lib/util/rxjs/race-emit.spec.ts
  libs/helpers/src/lib/util/rxjs/rxjs.spec.ts
  libs/helpers/src/lib/util/rxjs/rxjs.ts
  libs/i18n/src/lib/interfaces/language.ts
  libs/i18n/src/lib/languages/russian/column-settings.ts
  libs/i18n/src/lib/languages/russian/russian.ts
Labels: ready

#796 fix: new theme default palette colors fix
  libs/theme/src/styles/theme/v3/default-palette.less
  libs/theme/src/styles/theme/v3/default.less
Labels: devOnly

#794 feat: mirror links added to doc
  apps/doc/src/app/about-prizm/repositories/repositories.component.html
  apps/doc/src/app/about-prizm/service-level-agreement/service-level-agreement.component.html
Labels: ready

#810 feat(components/input-select): added wrap model for simple content
  libs/components/src/lib/components/checkbox/checkbox.component.less
  libs/components/src/lib/components/dropdowns/multi-select/input-multi-select.component.less
  libs/components/src/lib/components/dropdowns/select/input-select.component.html
Labels: ready

#805 fix: initial table sort
  apps/doc/src/app/components/table/examples/table-sort-example/table-sort-example.component.html
  apps/doc/src/app/components/table/examples/table-sort-example/table-sort-example.component.ts
  libs/components/src/lib/components/table/directives/table.directive.ts
  libs/components/src/lib/components/table/service/table-sorter.service.ts
Labels: ready

#802 fix: deprecated select component has been changed for new one for pag…
  libs/components/src/lib/components/paginator/prizm-paginator.component.html
  libs/components/src/lib/components/paginator/prizm-paginator.component.ts
  libs/components/src/lib/components/paginator/prizm-paginator.module.ts
  libs/components/src/lib/tokens/i18n.ts
  libs/i18n/src/lib/interfaces/language.ts
  libs/i18n/src/lib/languages/russian/paginator.ts
  libs/i18n/src/lib/languages/russian/russian.ts
Labels: ready

#804 fix: input layout outer label incorrect display #788
  libs/components/src/lib/components/input/common/input-layout/input-layout.component.less
Labels: ready

#795 fix: disabled sync between layout in in put #771
  apps/doc/src/app/components/input/textarea/examples/textarea-basic-example/textarea-basic-example.component.html
  apps/doc/src/app/components/input/textarea/examples/textarea-basic-example/textarea-basic-example.component.ts
  apps/doc/src/app/components/side-menu/examples/side-menu-example-basic/side-menu-example-basic.component.html
  libs/components/assets/icon-codepoints.json
  libs/components/src/lib/components/icon/icon-16-definitions.ts
  libs/components/src/lib/components/icon/icon-definitions.ts
  libs/components/src/lib/components/input/common/base/input-ng-control.class.ts
  libs/components/src/lib/components/input/common/input-layout/input-layout.component.html
  libs/components/src/lib/components/input/common/input-layout/input-layout.component.less
  libs/components/src/lib/components/input/common/input-layout/input-layout.component.ts
  libs/components/src/lib/components/input/input-text/input-text.component.ts
  libs/components/src/styles/icons-16/icons-16.less
  libs/components/src/styles/icons/icons.less
Labels: ready

#820 Feat/release 3.2.0.next.1
  apps/doc/src/app/about-prizm/changelog/CHANGELOG.md
Labels: ready, devOnly

#808 fix(components/tabs): update tab #759
  apps/doc/src/app/components/tabs/examples/tabs-example-closable/tabs-example-closable.component.html
  apps/doc/src/app/components/tabs/examples/tabs-example-closable/tabs-example-closable.component.ts
  apps/doc/src/app/components/tabs/tabs-example.component.html
  libs/components/src/lib/components/tabs/components/tab.component.ts
  libs/components/src/lib/components/tabs/tabs.component.ts
  libs/components/src/lib/components/tabs/tabs.service.ts
Labels: ready

#801 feat: colors v3 for tabs and buttons
  apps/doc/src/app/components/tabs/examples/tabs-example-in-panel/tabs-example-in-panel.component.html
  apps/doc/src/app/components/tabs/examples/tabs-example-in-panel/tabs-example-in-panel.component.less
  apps/doc/src/app/components/tabs/examples/tabs-example-in-panel/tabs-example-in-panel.component.ts
  apps/doc/src/app/components/tabs/tabs-example.component.html
  apps/doc/src/app/components/tabs/tabs-example.component.ts
  apps/doc/src/app/components/tabs/tabs-example.module.ts
  libs/components/src/lib/components/button/button.component.less
  libs/components/src/lib/components/switcher/components/switcher-item/switcher-item.component.html
  libs/components/src/lib/components/switcher/components/switcher-item/switcher-item.component.less
  libs/components/src/lib/components/switcher/switcher.component.less
  libs/components/src/lib/components/switcher/switcher.component.ts
  libs/components/src/lib/components/tabs/components/tab.component.html
  libs/components/src/lib/components/tabs/components/tab.component.less
  libs/components/src/lib/components/tabs/tabs.component.html
  libs/components/src/lib/components/tabs/tabs.component.less
  libs/components/src/lib/components/tabs/tabs.component.ts
  libs/components/src/lib/directives/wrapper/wrapper.component.less
  libs/theme/src/styles/theme/v3/dark.less
Labels: ready

#797 fix(components/polymorph): build error #738 #806
  libs/components/src/lib/directives/polymorph/classes/component.ts
  libs/components/src/lib/directives/polymorph/directives/outlet.ts
  libs/components/src/lib/directives/polymorph/directives/template.ts
  libs/components/src/lib/directives/polymorph/types/content.ts
  libs/components/src/lib/directives/polymorph/types/handler.ts
Labels: ready, devOnly

#835 chore: prepare release 3.2.0
  apps/doc/src/app/about-prizm/changelog/CHANGELOG.md
  apps/doc/src/app/components/input/input-select/input-select.component.ts
  libs/components/src/lib/components/input/common/base/input-ng-control.class.ts
  libs/components/src/lib/components/input/input-number/input-number.component.ts
Labels: ready

#825 Feat/cron limits
  libs/components/src/lib/components/cron-human-readable/human-readable/cron-parser.ts
  libs/components/src/lib/components/cron-human-readable/human-readable/expression-descriptor.ts
  libs/components/src/lib/components/cron-human-readable/human-readable/i18n/locale.ts
  libs/components/src/lib/components/cron-human-readable/human-readable/i18n/locales/ru.ts
  libs/components/src/lib/components/cron-human-readable/human-readable/range-validator.ts
  libs/components/src/lib/components/cron/components/day/day.component.html
  libs/components/src/lib/components/cron/components/year/year.component.html
  libs/components/src/lib/components/cron/components/year/year.component.ts
  libs/components/src/lib/components/input/common/index.ts
  libs/components/src/lib/components/input/common/input-allowed-symbols/const.ts
  libs/components/src/lib/components/input/common/input-allowed-symbols/index.ts
  libs/components/src/lib/components/input/common/input-allowed-symbols/input-allowed-symbols.directive.ts
  libs/components/src/lib/components/input/common/input-common.module.ts
Labels: ready

#831 feat: white-space pre-line for hints and dialogs
  apps/doc/src/app/components/hint/examples/with-template/hint-with-template-example.component.html
  libs/components/src/lib/components/dialogs/confirm-dialog/confirm-dialog.component.less
  libs/components/src/lib/directives/confirm-popup/confirm-popup-container.component.less
  libs/components/src/lib/directives/hint/hint-container.component.less
  libs/components/src/lib/directives/tooltip/tooltip-container.component.less
Labels: ready

#828 feat: add variable for panel height #811
  apps/doc/src/app/components/panel/panel-example.component.html
  apps/doc/src/app/components/panel/panel-example.component.ts
  libs/components/src/lib/components/panel/panel.component.less
  libs/components/src/lib/components/panel/panel.component.ts
Labels: ready, devOnly

#838 fix: widget header shrinks #273
  apps/doc/src/app/components/splitter/examples/areas-control-size/areas-control-size.component.html
  apps/doc/src/app/components/splitter/splitter-example.module.ts
  libs/components/src/lib/components/widget/widget.component.less
Labels: ready

#839 fix: splitter area collapsed after display changed #737
  libs/components/src/lib/components/splitter/splitter.component.ts
Labels: ready

#840 feat: remove redundant page 'technology list' from docs
  apps/doc/src/app/about-prizm/technology-list/technology-list.component.html
  apps/doc/src/app/about-prizm/technology-list/technology-list.component.less
  apps/doc/src/app/about-prizm/technology-list/technology-list.component.spec.ts
  apps/doc/src/app/about-prizm/technology-list/technology-list.component.ts
  apps/doc/src/app/about-prizm/technology-list/technology-list.module.ts
  apps/doc/src/app/app.module.ts
  apps/doc/src/app/app.routes.ts
  apps/doc/src/app/pages.ts
Labels: ready

#860 feat(components/dialog): added outer-header with example #854
  apps/doc/src/app/components/dialogs/dialog/dialog-example.component.html
  apps/doc/src/app/components/dialogs/dialog/dialog-example.module.ts
  apps/doc/src/app/components/dialogs/dialog/examples/outher-header/dialog-outher-header-example.component.html
  apps/doc/src/app/components/dialogs/dialog/examples/outher-header/dialog-outher-header-example.component.ts
  libs/components/src/lib/components/dialogs/dialog/dialog.component.html
  libs/components/src/lib/components/dialogs/dialog/dialog.models.ts
  libs/components/src/lib/components/dialogs/dialog/dialog.service.ts
Labels: ready

#858 Fix/input select open dropdown
  apps/doc/src/app/components/input/input-select/examples/async/select-async-example.component.html
  apps/doc/src/app/components/input/input-select/examples/async/select-async-example.component.ts
  apps/doc/src/app/components/input/input-select/input-select.component.html
  apps/doc/src/app/components/input/input-select/input-select.component.ts
  apps/doc/src/app/components/input/input-select/input-select.module.ts
  libs/components/src/lib/components/dropdowns/select/input-select.component.html
  libs/components/src/lib/components/dropdowns/select/input-select.component.ts
  libs/components/src/lib/directives/polymorph/directives/outlet.ts
  libs/components/src/lib/directives/polymorph/index.ts
  libs/components/src/lib/directives/polymorph/util.ts
Labels: ready

#846 fix(components/input-select): lazy get items #836 #812
  apps/doc/src/app/components/input/input-select/examples/async/select-async-example.component.html
  apps/doc/src/app/components/input/input-select/examples/async/select-async-example.component.ts
  apps/doc/src/app/components/input/input-select/input-select.component.html
  apps/doc/src/app/components/input/input-select/input-select.component.ts
  apps/doc/src/app/components/input/input-select/input-select.module.ts
  libs/components/src/lib/components/dropdowns/select/input-select.component.html
  libs/components/src/lib/components/dropdowns/select/input-select.component.ts
Labels: ready

#850 fix: cron buttons width #848
  apps/doc/src/app/components/buttons/button/button.component.html
  apps/doc/src/app/components/buttons/button/button.component.ts
  apps/doc/src/app/components/buttons/button/examples/filled/filled-buttons-example.component.ts
  apps/doc/src/app/components/buttons/button/examples/ghost/ghost-buttons-example.component.ts
  apps/doc/src/app/components/buttons/button/examples/outline/outline-buttons-example.component.ts
  apps/doc/src/styles.less
  libs/components/src/lib/components/button/button.component.less
  libs/components/src/lib/components/tabs/components/tab.component.less
  libs/components/src/lib/components/tabs/tabs.component.ts
Labels: ready

#827 feat: add polymorph template support for confirm-dialog component #799
  apps/doc/src/app/components/dialogs/confirm-dialog/confirm.component.html
  apps/doc/src/app/components/dialogs/confirm-dialog/confirm.component.ts
  apps/doc/src/app/components/dialogs/confirm-dialog/confirm.module.ts
  apps/doc/src/app/components/dialogs/confirm-dialog/examples/footer-template/footer-template.component.html
  apps/doc/src/app/components/dialogs/confirm-dialog/examples/footer-template/footer-template.component.ts
  libs/components/src/lib/components/dialogs/confirm-dialog/confirm-dialog.component.html
  libs/components/src/lib/components/dialogs/confirm-dialog/confirm-dialog.models.ts
Labels: ready

#817 Fix/cront weekday names
  apps/doc/src/app/components/cron/cron.component.html
  apps/doc/src/app/components/cron/cron.component.ts
  libs/components/src/lib/components/cron-human-readable/human-readable/expression-descriptor.ts
  libs/components/src/lib/components/cron/components/year/year.component.html
  libs/components/src/lib/components/cron/components/year/year.component.less
  libs/components/src/lib/components/cron/components/year/year.component.ts
  libs/components/src/lib/components/cron/cron.module.ts
  libs/components/src/lib/components/input/common/index.ts
  libs/components/src/lib/components/input/common/input-allowed-symbols/index.ts
  libs/components/src/lib/components/input/common/input-allowed-symbols/input-allowed-symbols.module.ts
  libs/components/src/lib/components/input/common/input-common.module.ts
  libs/components/src/lib/components/input/common/input-corrector/index.ts
  libs/components/src/lib/components/input/common/input-corrector/input-corrector.directive.ts
  libs/components/src/lib/components/input/common/input-corrector/input-corrector.module.ts
Labels: ready

#832 feat(components/input): added new parametr with control #762
  apps/doc/src/app/components/input/input-text/examples/input-validation-custom-example/input-validation-custom-texts.service.ts
  libs/components/src/lib/components/input/common/base/input-invalid-text-base-class.directive.ts
  libs/components/src/lib/components/input/common/services/input-invalid-subtext.service.ts
  tools/executors/icon-font-builder/impl.js
Labels: ready, devOnly

#833 feat(components/overlay): new close logic #798
  apps/doc/src/app/tools/overlay/examples/relative/template.ts
  libs/components/src/lib/modules/overlay/overlay-control.ts
  libs/components/src/lib/modules/overlay/overlay.component.ts
Labels: ready

#851 feat(components/input-date-time): new transformer for work with base date format #410
  apps/doc/src/app/components/input/input-layout-date-time/examples/base-transformer/input-layout-date-time-base-transformer-example.component.html
  apps/doc/src/app/components/input/input-layout-date-time/examples/base-transformer/input-layout-date-time-base-transformer-example.component.ts
  apps/doc/src/app/components/input/input-layout-date-time/input-layout-date-time.component.html
  apps/doc/src/app/components/input/input-layout-date-time/input-layout-date-time.component.ts
  apps/doc/src/app/components/input/input-layout-date-time/input-layout-date-time.module.ts
  libs/components/src/lib/@core/date-time/date-time.ts
  libs/components/src/lib/components/input/input-date-time/index.ts
  libs/components/src/lib/components/input/input-date-time/input-date-time-base.transformer.ts
  libs/components/src/lib/components/input/input-date-time/input-date-time-native.transformer.ts
Labels: ready

#859 Feat: counter
  apps/doc/src/app/app.routes.ts
  apps/doc/src/app/components/buttons/button/button.component.html
  apps/doc/src/app/components/buttons/button/button.component.ts
  apps/doc/src/app/components/buttons/button/button.module.ts
  apps/doc/src/app/components/buttons/button/examples/counter/button-with-counter-example.component.html
  apps/doc/src/app/components/buttons/button/examples/counter/button-with-counter-example.component.ts
  apps/doc/src/app/components/counter/counter-example.component.html
  apps/doc/src/app/components/counter/counter-example.component.ts
  apps/doc/src/app/components/counter/counter-example.module.ts
  apps/doc/src/app/components/counter/examples/base/counter-base-example.component.html
  apps/doc/src/app/components/counter/examples/base/counter-base-example.component.ts
  apps/doc/src/app/components/counter/examples/directive/counter-directive-example.component.html
  apps/doc/src/app/components/counter/examples/directive/counter-directive-example.component.ts
  apps/doc/src/app/components/counter/examples/setup-module.md
  apps/doc/src/app/pages.ts
  libs/components/src/lib/components/counter/counter.component.html
  libs/components/src/lib/components/counter/counter.component.less
  libs/components/src/lib/components/counter/counter.component.spec.ts
  libs/components/src/lib/components/counter/counter.component.ts
  libs/components/src/lib/components/counter/counter.directive.ts
  libs/components/src/lib/components/counter/counter.models.ts
  libs/components/src/lib/components/counter/counter.module.ts
  libs/components/src/lib/components/counter/index.ts
  libs/components/src/lib/components/index.ts
Labels: ready

#864 fix: buttons pseudo state documentation update #809
  apps/doc/src/app/components/buttons/button/button.component.html
  apps/doc/src/app/components/buttons/icon-button/icon-button.component.html
Labels: ready

#866 fix: table row group column borders disappear when filtering #230
  apps/doc/src/app/components/table/examples/table-row-group-example/table-row-group-example.component.html
  apps/doc/src/app/components/table/examples/table-row-group-example/table-row-group-example.component.ts
  apps/doc/src/app/components/table/examples/table-search-example/table-search-example.component.html
  libs/components/src/lib/components/table/directives/table.directive.ts
  libs/components/src/lib/components/table/table.service.ts
  libs/components/src/lib/components/table/tbody/tbody.component.html
  libs/components/src/lib/components/table/tbody/tbody.component.less
  libs/components/src/lib/components/table/tbody/tbody.component.ts
  libs/components/src/lib/components/table/th-group/th-group.component.ts
  libs/components/src/lib/components/table/th-group/th-group.service.ts
  libs/components/src/lib/components/table/th/th.component.ts
Labels: ready
