Repository zyfra/Prizm, pull requests merged in 2023-11, with the labels that each got.

#934 feat(components/input-layout): custom clear button #855
  apps/doc/src/app/components/dropdowns/multi-select/multi-select.component.html
  apps/doc/src/app/components/dropdowns/select/select.component.html
  apps/doc/src/app/components/input/date/date.component.html
  apps/doc/src/app/components/input/input-carousel/input-carousel-example.component.html
  apps/doc/src/app/components/input/input-date-range/input-date-range.component.html
  apps/doc/src/app/components/input/input-date-relative/input-date-relative.component.html
  apps/doc/src/app/components/input/input-date-time-range/input-date-time-range.component.html
  apps/doc/src/app/components/input/input-date-time/input-date-time.component.html
  apps/doc/src/app/components/input/input-layout-date-range/input-layout-date-range.component.html
  apps/doc/src/app/components/input/input-layout-date-relative/input-layout-date-relative.component.html
  apps/doc/src/app/components/input/input-layout-date-time-range/input-layout-date-time-range.component.html
  apps/doc/src/app/components/input/input-layout-date-time/input-layout-date-time.component.html
  apps/doc/src/app/components/input/input-layout-date/input-layout-date.component.html
  apps/doc/src/app/components/input/input-layout-month-range/input-layout-month-range.component.html
  apps/doc/src/app/components/input/input-layout-month/input-layout-month.component.html
  apps/doc/src/app/components/input/input-layout-time/input-layout-time.component.html
  apps/doc/src/app/components/input/input-month-range/input-month-range.component.html
  apps/doc/src/app/components/input/input-month/input-month.component.html
  apps/doc/src/app/components/input/input-multi-select/input-multi-select.component.html
  apps/doc/src/app/components/input/input-select/input-select.component.html
  apps/doc/src/app/components/input/input-text/examples/input-custom-clear-button-example/input-custom-clear-button-example.component.html
  apps/doc/src/app/components/input/input-text/examples/input-custom-clear-button-example/input-custom-clear-button-example.component.less
  apps/doc/src/app/components/input/input-text/examples/input-custom-clear-button-example/input-custom-clear-button-example.component.ts
  apps/doc/src/app/components/input/input-text/input-example.module.ts
  apps/doc/src/app/components/input/input-text/input.component.html
  apps/doc/src/app/components/input/input-text/input.component.ts
  apps/doc/src/app/components/input/input-time/input-time.component.html
  libs/components/src/lib/components/input/common/input-common.module.ts
  libs/components/src/lib/components/input/common/input-layout/input-layout.component.html
  libs/components/src/lib/components/input/common/input-layout/input-layout.component.ts
Labels: ready

#868 feat: v3 colors for indicator #867
  libs/components/src/lib/components/indicator/indicator.component.less
Labels: ready

#873 feat: v3 colors for checkbox, spinner and loader #870 #871
  libs/components/src/lib/components/checkbox/checkbox.component.less
  libs/components/src/lib/components/loader/loader.component.less
  libs/components/src/lib/components/spinner/spinner.component.less
  libs/theme/src/styles/theme/v3/default.less
Labels: ready

#875 fix: inputDateMulti incorrect label text #753
  apps/doc/src/app/components/input/input-date-multi/examples/four/input-date-multi-four-example.component.html
Labels: ready

#894 feat: add hint to switcher #856
  apps/doc/src/app/components/switcher/examples/switcher-only-icon-example/switcher-only-icon-example.component.ts
  apps/doc/src/app/components/switcher/switcher-example.component.html
  libs/components/src/lib/components/input/input-text/input-text.component.ts
  libs/components/src/lib/components/switcher/components/switcher-item/switcher-item.component.ts
  libs/components/src/lib/components/switcher/directives/switcher-hint.directive.ts
  libs/components/src/lib/components/switcher/switcher.component.html
  libs/components/src/lib/components/switcher/switcher.interface.ts
  libs/components/src/lib/components/switcher/switcher.module.ts
Labels: ready

#896 feat: scrollbar colors update to v3 #895
  libs/components/src/lib/components/scrollbar/scroll-controls.component.less
Labels: ready

#899 feat: add prizm counter to tabs #863
  apps/doc/src/app/components/tabs/examples/tabs-example-counter/tabs-example-counter.component.html
  apps/doc/src/app/components/tabs/examples/tabs-example-counter/tabs-example-counter.component.ts
  apps/doc/src/app/components/tabs/tabs-example.component.html
  apps/doc/src/app/components/tabs/tabs-example.component.ts
  libs/components/src/lib/components/counter/counter.component.less
  libs/components/src/lib/components/tabs/components/tab.component.html
  libs/components/src/lib/components/tabs/components/tab.component.ts
  libs/components/src/lib/components/tabs/tabs.interface.ts
  libs/components/src/lib/components/tabs/tabs.module.ts
Labels: ready

#901 fix: file upload button type #837
  apps/doc/src/app/components/file-upload/examples/file-upload-in-form/file-upload-in-form-example.component.html
  apps/doc/src/app/components/file-upload/examples/file-upload-in-form/file-upload-in-form-example.component.less
  apps/doc/src/app/components/file-upload/examples/file-upload-in-form/file-upload-in-form-example.component.ts
  apps/doc/src/app/components/file-upload/file-upload-example.component.html
  apps/doc/src/app/components/file-upload/file-upload-example.component.ts
  apps/doc/src/app/components/file-upload/file-upload-example.module.ts
  libs/components/src/lib/components/file-upload/file-upload.component.html
Labels: ready

#910 feat: update progress colors to v3 #902
  apps/doc/src/app/components/progress/circle-bar/examples/circle/progress-circle-example.component.html
  apps/doc/src/app/components/progress/circle-bar/examples/circle/progress-circle-example.component.ts
  apps/doc/src/app/components/progress/circle-bar/progress-circle-bar.component.ts
  apps/doc/src/app/components/progress/line-bar/examples/base/progress-base-example.component.html
  apps/doc/src/app/components/progress/line-bar/examples/base/progress-base-example.component.ts
  apps/doc/src/app/components/progress/line-bar/progress-line-bar.component.ts
  apps/doc/src/app/components/progress/line-segmented/examples/base/progress-base-example.component.ts
  apps/doc/src/app/components/progress/line-segmented/progress-line-segmented.component.ts
  libs/components/src/lib/components/progress/progress-bar/progress-bar.component.less
  libs/components/src/lib/components/progress/progress-bar/progress-color-segments.directive.ts
  libs/components/src/lib/components/progress/progress-circle/progress-circle.component.less
  libs/components/src/lib/components/progress/progress-label/progress-label.component.less
  libs/components/src/lib/components/progress/progress-segmented/progress-segmented.component.less
  libs/components/src/lib/components/progress/progress-segmented/progress-segmented.component.ts
Labels: ready

#915 fix: table documentation open property #654
  apps/doc/src/app/components/table/table-example.component.html
  apps/doc/src/app/components/table/table-example.component.ts
Labels: ready

#918 fix(components/toast): double toast error and scrollbar #481 #734
  libs/components/src/lib/components/toast/toast-container/toast-container.component.html
  libs/components/src/lib/components/toast/toast-container/toast-container.component.less
  libs/components/src/lib/components/toast/toast.module.ts
Labels: ready

#919 fix(components/tree): active item style and update doc #708 #654
  apps/doc/src/app/components/tree/examples/active-color/tree-active-color-example.component.html
  apps/doc/src/app/components/tree/examples/active-color/tree-active-color-example.component.ts
  apps/doc/src/app/components/tree/tree.component.html
  apps/doc/src/app/components/tree/tree.component.ts
  apps/doc/src/app/components/tree/tree.module.ts
  libs/components/src/lib/components/tree/components/tree-item/tree-item.component.html
  libs/components/src/lib/components/tree/components/tree-item/tree-item.component.ts
Labels: ready

#935 feat(chore): changed lodash to lodash-es #886
  apps/doc/src/app/about-prizm/design-system/design-system.component.spec.ts
  apps/doc/src/app/about-prizm/release-policy/release-policy.component.spec.ts
  apps/doc/src/app/about-prizm/repositories/repositories.component.spec.ts
  apps/doc/src/app/components/table/examples/table-column-settings-example/pipes/header-sticky-pipe.pipe.ts
  apps/doc/src/app/components/table/examples/table-tree-example/table-tree-example.component.ts
  apps/doc/src/app/forZIIoT/introduction/introduction.component.spec.ts
  apps/doc/src/app/how-to-work/internationalization/internationalization.component.spec.ts
  jest.config.ts
  libs/ast/schematics-helpers/src/run-tasks-by-project-name/run-tasks-by-project-name.ts
  libs/charts/base/src/lib/service/charts-theme.service.ts
  libs/components/src/lib/components/column-settings/column-settings.component.spec.ts
  libs/components/src/lib/components/column-settings/column-settings.component.ts
  libs/components/src/lib/components/cron/cron-ui-base.state.ts
  libs/components/src/lib/components/switcher/components/switcher-item/switcher-item.component.spec.ts
  libs/components/src/lib/components/tabs/tabs.component.spec.ts
  libs/doc/base/src/lib/components/documentation/documentation-property-connector.directive.ts
  libs/doc/base/src/lib/components/documentation/documentation.component.ts
  libs/nxmv/src/generators/apply/index.ts
  libs/plugin/src/generators/update-version/generator.spec-r.ts
  package-lock.json
  package-lock.json.ng14
  package-lock.json.ng15
  package-lock.json.ng16
  package.json
  package.json.ng14
  package.json.ng15
  package.json.ng16
Labels: ready, devOnly

#908 feat(components/dropdown-control): new directive control for dropdown…
  apps/doc/src/app/components/input/input-layout-date-time/examples/base/input-layout-date-time-base-example.component.html
  libs/components/src/lib/components/dropdowns/dropdown-host/dropdown-host-control.directive.ts
  libs/components/src/lib/components/dropdowns/dropdown-host/dropdown-host.component.ts
  libs/components/src/lib/components/dropdowns/dropdown-host/dropdown-host.module.ts
  libs/components/src/lib/components/input/input-date-time/input-layout-date-time.module.ts
Labels: ready, devOnly

#912 feat(components): create own calendar exports
  libs/components/src/lib/components/calendar/calendar.module.ts
  libs/components/src/lib/components/index.ts
  libs/components/src/lib/components/internal/index.ts
Labels: ready, devOnly

#937 feat(components): add boolean compatible with async #714
  libs/components/src/lib/abstract/interactive.ts
  libs/components/src/lib/components/accordion/components/accordion-item/accordion-item.component.ts
  libs/components/src/lib/components/button/button.component.ts
  libs/components/src/lib/components/button/split-button/split-button.component.ts
  libs/components/src/lib/components/checkbox/checkbox.component.ts
  libs/components/src/lib/components/chips/chips-item/chips-item.component.ts
  libs/components/src/lib/components/counter/counter.component.ts
  libs/components/src/lib/components/counter/counter.directive.ts
  libs/components/src/lib/components/cron/cron.component.ts
  libs/components/src/lib/components/file-upload/file-upload.component.ts
  libs/components/src/lib/components/input/common/input-icon-button/input-icon-button.component.ts
  libs/components/src/lib/components/internal/primitive-spin-button/primitive-spin-button.component.ts
  libs/components/src/lib/components/slider/slider-cnob.component.ts
  libs/components/src/lib/components/stepper/stepper-selector-item.directive.ts
  libs/components/src/lib/components/stepper/stepper-step.directive.ts
  libs/components/src/lib/components/tabs/components/tab.component.ts
  libs/components/src/lib/directives/wrapper/wrapper.component.ts
Labels: ready

#905 feat(components/hint): standalone directives
  libs/components/src/lib/directives/hint/hint.directive.ts
  libs/components/src/lib/directives/hint/hint.module.ts
Labels: ready, reopen

#917 feat(components/input): update on blur #736
  libs/components/src/lib/components/input/common/base/input-ng-control.class.ts
Labels: ready, reopen

#920 feat(components/input): empty label mode for iner #384
  apps/doc/src/app/components/input/input-text/examples/input-empty-label-example/input-empty-label-example.component.html
  apps/doc/src/app/components/input/input-text/examples/input-empty-label-example/input-empty-label-example.component.less
  apps/doc/src/app/components/input/input-text/examples/input-empty-label-example/input-empty-label-example.component.ts
  apps/doc/src/app/components/input/input-text/input-example.module.ts
  apps/doc/src/app/components/input/input-text/input.component.html
  apps/doc/src/app/components/input/input-text/input.component.ts
  libs/components/src/lib/components/input/common/input-layout/input-layout.component.html
  libs/components/src/lib/components/input/common/input-layout/input-layout.component.ts
  libs/components/src/lib/components/input/common/styles/input.component.less
Labels: ready, reopen

#975 feat(components/icon): to standalone
  libs/components/src/lib/components/icon/icon.component.ts
  libs/components/src/lib/components/icon/icon.module.ts
Labels: ready

#973 feat(components/grid): to standalone
  libs/components/src/lib/components/grid/components/grid-item/grid-item.component.spec.ts
  libs/components/src/lib/components/grid/components/grid-item/grid-item.component.ts
  libs/components/src/lib/components/grid/grid.component.spec.ts
  libs/components/src/lib/components/grid/grid.component.ts
  libs/components/src/lib/components/grid/grid.module.ts
Labels: ready

#972 feat(components/file-upload): to standalone
  libs/components/src/lib/components/file-upload/file-upload.component.ts
  libs/components/src/lib/components/file-upload/file-upload.module.ts
Labels: ready

#970 feat(components/select): to standalone
  libs/components/src/lib/components/dropdowns/select/select.component.ts
  libs/components/src/lib/components/dropdowns/select/select.module.ts
Labels: ready

#969 feat(components/multi-select): to standalone
  libs/components/src/lib/components/dropdowns/multi-select/input-multi-select.component.ts
  libs/components/src/lib/components/dropdowns/multi-select/input-multi-select.module.ts
  libs/components/src/lib/components/dropdowns/multi-select/multi-select.component.ts
  libs/components/src/lib/components/dropdowns/multi-select/multi-select.module.ts
Labels: ready

#968 feat(components/cron-hr): to standalone
  libs/components/src/lib/components/cron-human-readable/cron-human-readable.module.ts
  libs/components/src/lib/components/cron-human-readable/pipe/cron-human-readable.pipe.ts
Labels: ready

#971 feat(components/expand): to standalone
  libs/components/src/lib/components/expand/expand-content.directive.ts
  libs/components/src/lib/components/expand/expand.component.ts
  libs/components/src/lib/components/expand/expand.module.ts
Labels: ready

#966 feat(components/counter): to standalone
  libs/components/src/lib/components/counter/counter.component.ts
  libs/components/src/lib/components/counter/counter.directive.ts
  libs/components/src/lib/components/counter/counter.module.ts
Labels: ready

#963 feat(components/checkbox): to standalone
  libs/components/src/lib/components/checkbox/checkbox.component.ts
  libs/components/src/lib/components/checkbox/checkbox.module.ts
Labels: ready

#962 feat(components/card): to standalone
  libs/components/src/lib/components/card/card.component.ts
  libs/components/src/lib/components/card/card.module.ts
Labels: ready

#960 feat(components/calendar-month): to standalone
  libs/components/src/lib/components/calendar-month/calendar-month.component.ts
  libs/components/src/lib/components/calendar-month/calendar-month.module.ts
Labels: ready

#961 feat(components/calendar-range): to standalone
  libs/components/src/lib/components/calendar-range/calendar-range.component.ts
  libs/components/src/lib/components/calendar-range/calendar-range.module.ts
Labels: ready

#964 feat(components/chips): to standalone
  libs/components/src/lib/components/chips/chips-item/chips-item.component.ts
  libs/components/src/lib/components/chips/chips.component.ts
  libs/components/src/lib/components/chips/chips.module.ts
Labels: ready

#957 feat(components/breadcrumbs): to standalone
  libs/components/src/lib/components/breadcrumbs/breadcrumbs.component.ts
  libs/components/src/lib/components/breadcrumbs/breadcrumbs.directive.ts
  libs/components/src/lib/components/breadcrumbs/breadcrumbs.module.ts
Labels: ready

#956 feat(components/accordion): to standalone
  libs/components/src/lib/components/accordion/accordion.component.ts
  libs/components/src/lib/components/accordion/accordion.module.ts
  libs/components/src/lib/components/accordion/components/accordion-item/accordion-item.component.ts
  libs/components/src/lib/components/accordion/directives/accordion-content.directive.ts
  libs/components/src/lib/components/accordion/directives/accordion-tools.directive.ts
Labels: ready

#999 feat(components/progress): to standalones
  libs/components/src/lib/components/progress/progress-bar/progress-bar.component.ts
  libs/components/src/lib/components/progress/progress-bar/progress-color-segments.directive.ts
  libs/components/src/lib/components/progress/progress-circle/progress-circle.component.ts
  libs/components/src/lib/components/progress/progress-label/progress-label.component.ts
  libs/components/src/lib/components/progress/progress-segmented/progress-segmented.component.ts
  libs/components/src/lib/components/progress/progress.module.ts
  libs/components/src/lib/directives/repeat-times/repeat-times.directive.ts
  libs/components/src/lib/directives/repeat-times/repeat-times.module.ts
Labels: ready

#998 feat(components/scrollbar): to standalone
  libs/components/src/lib/components/radio/prizm-radio-button.component.ts
  libs/components/src/lib/components/radio/prizm-radio-button.module.ts
Labels: ready

#996 feat(components/slider): to standalone
  libs/components/src/lib/components/slider/slider-cnob.component.ts
  libs/components/src/lib/components/slider/slider.component.ts
  libs/components/src/lib/components/slider/slider.module.ts
Labels: ready

#995 feat(components/spinner): to standalone
  libs/components/src/lib/components/spinner/spinner.component.ts
  libs/components/src/lib/components/spinner/spinner.module.ts
Labels: ready

#994 feat(components/splitter): to standalone
  libs/components/src/lib/components/splitter/area/area.component.ts
  libs/components/src/lib/components/splitter/custom-gutter.directive.ts
  libs/components/src/lib/components/splitter/gutter/gutter-default.component.ts
  libs/components/src/lib/components/splitter/gutter/gutter.component.ts
  libs/components/src/lib/components/splitter/splitter.component.ts
  libs/components/src/lib/components/splitter/splitter.module.ts
Labels: ready

#992 feat(components/switcher): to standalone
  libs/components/src/lib/components/switcher/components/switcher-item/switcher-item.component.ts
  libs/components/src/lib/components/switcher/directives/switcher-hint.directive.ts
  libs/components/src/lib/components/switcher/switcher.component.ts
  libs/components/src/lib/components/switcher/switcher.module.ts
Labels: ready

#991 feat(components/tabs): to standalone
  libs/components/src/lib/components/tabs/components/tab.component.ts
  libs/components/src/lib/components/tabs/tab-menu-item.directive.ts
  libs/components/src/lib/components/tabs/tabs.component.ts
  libs/components/src/lib/components/tabs/tabs.module.ts
Labels: ready

#990 feat(components/toggle): to standalone
  libs/components/src/lib/components/toggle/toggle.component.ts
  libs/components/src/lib/components/toggle/toggle.module.ts
Labels: ready

#989 feat(components/widget): to standalone
  libs/components/src/lib/components/widget/widget.component.ts
  libs/components/src/lib/components/widget/widget.module.ts
Labels: ready

#986 fix: add more space for chips in multiselect #892
  libs/components/src/lib/components/chips/chips.component.less
Labels: ready

#958 feat(components/button): to standalone
  libs/components/src/lib/components/button/button.component.ts
  libs/components/src/lib/components/button/button.module.ts
  libs/components/src/lib/components/button/split-button/split-button.component.ts
  libs/components/src/lib/directives/confirm-popup/confirm-popup-container.component.ts
  libs/components/src/lib/directives/confirm-popup/confirm-popup.module.ts
  libs/components/src/lib/directives/wrapper/wrapper.component.ts
  libs/components/src/lib/directives/wrapper/wrapper.module.ts
Labels: ready

#1004 feat(components/indicator): to standalone
  apps/doc/src/app/components/indicators/examples/setup-module.md
  libs/components/src/lib/components/grid/grid.module.ts
  libs/components/src/lib/components/indicator/indicator.component.spec.ts
  libs/components/src/lib/components/indicator/indicator.component.ts
  libs/components/src/lib/components/indicator/indicator.module.ts
Labels: ready

#1006 feat(components/input-layout-date-standalone): to standalone
  apps/doc/src/app/components/input/input-layout-date/examples/setup-module.md
  libs/components/src/lib/components/input/input-date/input-layout-date.component.ts
  libs/components/src/lib/components/input/input-date/input-layout-date.module.ts
Labels: ready

#1008 feat(components/input-layout-date-range-standalone): to standalone
  apps/doc/src/app/components/input/input-layout-date-range/examples/setup-module.md
  libs/components/src/lib/components/input/input-date-range/input-layout-date-range.component.ts
  libs/components/src/lib/components/input/input-date-range/input-layout-date-range.module.ts
Labels: ready

#1009 feat(components/input-layout-date-relative-standalone): to standalone
  libs/components/src/lib/components/input/input-date-relative/input-layout-date-relative.component.ts
  libs/components/src/lib/components/input/input-date-relative/input-layout-date-relative.directive.ts
  libs/components/src/lib/components/input/input-date-relative/input-layout-date-relative.module.ts
Labels: ready

#1010 feat(components/input-layout-date-time-standalone): to standalone
  apps/doc/src/app/components/input/input-layout-date-time/examples/setup-module.md
  libs/components/src/lib/components/input/input-date-time/input-layout-date-time.component.ts
  libs/components/src/lib/components/input/input-date-time/input-layout-date-time.module.ts
Labels: ready

#1011 feat(components/input-layout-date-time-range-standalone): to standalone
  libs/components/src/lib/components/input/input-date-time-range/input-layout-date-time-range.component.ts
  libs/components/src/lib/components/input/input-date-time-range/input-layout-date-time-range.module.ts
Labels: ready

#1012 feat(components/input-layout-month-standalone): to standalone
  libs/components/src/lib/components/input/input-month/input-layout-month.component.ts
  libs/components/src/lib/components/input/input-month/input-layout-month.directive.ts
  libs/components/src/lib/components/input/input-month/input-layout-month.module.ts
Labels: ready

#1013 feat(components/input-layout-month-range-standalone): to standalone
  apps/doc/src/app/components/input/input-layout-month-range/examples/setup-module.md
  libs/components/src/lib/components/input/input-month-range/input-layout-month-range.component.ts
  libs/components/src/lib/components/input/input-month-range/input-layout-month-range.directive.ts
  libs/components/src/lib/components/input/input-month-range/input-layout-month-range.module.ts
Labels: ready

#1014 feat(components/input-number-standalone): to standalone
  libs/components/src/lib/components/input/input-number/input-number-auxiliary-control.directive.ts
  libs/components/src/lib/components/input/input-number/input-number-auxiliary-controls.component.ts
  libs/components/src/lib/components/input/input-number/input-number.component.ts
  libs/components/src/lib/components/input/input-number/input-number.module.ts
Labels: ready

#1015 feat(components/input-text): to standalone
  libs/components/src/lib/components/input/input-text/input-block.component.ts
  libs/components/src/lib/components/input/input-text/input-text.component.ts
  libs/components/src/lib/components/input/input-text/input-text.module.ts
  libs/components/src/lib/components/input/input-text/textarea.directive.ts
Labels: ready

#1016 feat(components/input-layout-time): to standalone
  apps/doc/src/app/components/input/input-layout-time/examples/setup-module.md
  libs/components/src/lib/components/input/input-time/input-layout-time.component.ts
  libs/components/src/lib/components/input/input-time/input-layout-time.module.ts
Labels: ready

#1017 feat(components/loader): to standalone
  apps/doc/src/app/components/loader/examples/setup-module.md
  libs/components/src/lib/components/link/link.component.ts
  libs/components/src/lib/components/link/link.module.ts
  libs/components/src/lib/components/loader/loader.component.ts
  libs/components/src/lib/components/loader/loader.module.ts
Labels: ready

#1018 feat(components/navigation-menu): to standalone
  libs/components/src/lib/components/accordion/accordion.module.ts
  libs/components/src/lib/components/accordion/components/accordion-item/accordion-item.component.ts
  libs/components/src/lib/components/accordion/directives/accordion-content.directive.ts
  libs/components/src/lib/components/navigation-menu/components/prizm-navigation-menu-group/prizm-navigation-menu-group.component.ts
  libs/components/src/lib/components/navigation-menu/components/prizm-navigation-menu-item/prizm-navigation-menu-item.component.ts
  libs/components/src/lib/components/navigation-menu/components/prizm-navigation-menu-items/prizm-navigation-menu-items.component.ts
  libs/components/src/lib/components/navigation-menu/components/prizm-navigation-menu-search/prizm-navigation-menu-search.component.ts
  libs/components/src/lib/components/navigation-menu/components/prizm-navigation-menu-toolbar/prizm-navigation-menu-toolbar.component.ts
  libs/components/src/lib/components/navigation-menu/components/prizm-navigation-menu/prizm-navigation-menu.component.ts
  libs/components/src/lib/components/navigation-menu/index.ts
  libs/components/src/lib/components/navigation-menu/navigation-menu.module.ts
Labels: ready

#1019 feat(components/paginator): to standalone
  libs/components/src/lib/components/paginator/prizm-paginator.component.ts
  libs/components/src/lib/components/paginator/prizm-paginator.module.ts
Labels: ready

#1005 feat(components/input-carousel): to standalone
  apps/doc/src/app/components/input/input-carousel/examples/setup-module.md
  libs/components/src/lib/components/input/carousel/input-carousel-auxiliary-left.component.ts
  libs/components/src/lib/components/input/carousel/input-carousel-auxiliary-right.component.ts
  libs/components/src/lib/components/input/carousel/input-carousel.component.ts
  libs/components/src/lib/components/input/carousel/input-carousel.module.ts
  libs/components/src/lib/components/input/common/input-common.module.ts
Labels: ready

#959 feat(components/calendar): to standalone
  libs/components/src/lib/components/calendar-range/calendar-range.component.ts
  libs/components/src/lib/components/calendar/calendar.component.ts
  libs/components/src/lib/components/calendar/calendar.module.ts
  libs/components/src/lib/components/internal/primitive-calendar-range/primitive-calendar-range.component.ts
  libs/components/src/lib/components/internal/primitive-calendar-range/primitive-calendar-range.module.ts
  libs/components/src/lib/components/internal/primitive-calendar/primitive-calendar.component.ts
  libs/components/src/lib/components/internal/primitive-calendar/primitive-calendar.module.ts
  libs/components/src/lib/components/internal/primitive-month-picker/primitive-month-picker.component.ts
  libs/components/src/lib/components/internal/primitive-month-picker/primitive-month-picker.module.ts
  libs/components/src/lib/components/internal/primitive-year-month-pagination/primitive-year-month-pagination.component.ts
  libs/components/src/lib/components/internal/primitive-year-month-pagination/primitive-year-month-pagination.module.ts
  libs/components/src/lib/components/internal/primitive-year-picker/primitive-year-picker.component.ts
  libs/components/src/lib/components/internal/primitive-year-picker/primitive-year-picker.module.ts
Labels: ready, reopen

#916 fix: icon with the step number is not displayed if the status for thi…
  libs/components/src/lib/components/stepper/stepper-selector.component.html
  libs/components/src/lib/components/stepper/stepper-selector.component.ts
Labels: ready

#928 fix: hidden splitter filtering #923
  libs/components/src/lib/components/splitter/splitter.component.ts
Labels: ready

#936 feat: colors and theme documentation #765
  apps/doc/src/app/app.routes.ts
  apps/doc/src/app/guidelines/colors/components/frame25826/frame25826.component.css
  apps/doc/src/app/guidelines/colors/components/frame25826/frame25826.component.html
  apps/doc/src/app/guidelines/theme/components/examples/hex.md
  apps/doc/src/app/guidelines/theme/components/examples/style.md
  apps/doc/src/app/guidelines/theme/components/examples/token.md
  apps/doc/src/app/guidelines/theme/components/theme-for-designers/theme-for-designers.component.html
  apps/doc/src/app/guidelines/theme/components/theme-for-designers/theme-for-designers.component.less
  apps/doc/src/app/guidelines/theme/components/theme-for-designers/theme-for-designers.component.ts
  apps/doc/src/app/guidelines/theme/components/theme-for-developers/theme-for-developers.component.html
  apps/doc/src/app/guidelines/theme/components/theme-for-developers/theme-for-developers.component.less
  apps/doc/src/app/guidelines/theme/components/theme-for-developers/theme-for-developers.component.ts
  apps/doc/src/app/guidelines/theme/theme-guide.component.html
  apps/doc/src/app/guidelines/theme/theme-guide.component.less
  apps/doc/src/app/guidelines/theme/theme-guide.component.spec.ts
  apps/doc/src/app/guidelines/theme/theme-guide.component.ts
  apps/doc/src/app/guidelines/theme/theme-guide.module.ts
  apps/doc/src/app/pages.ts
Labels: ready

#932 feat: slider update colors to v3 #930
  libs/components/src/lib/components/slider/slider-cnob.component.less
  libs/components/src/lib/components/slider/slider.component.less
Labels: ready

#1020 fix: added lodash-es to peerDependencies #1001
  libs/charts/base/package.json
  libs/charts/base/package.json.ng14
  libs/charts/base/package.json.ng15
  libs/charts/base/package.json.ng16
  libs/components/package.json
  libs/components/package.json.ng14
  libs/components/package.json.ng15
  libs/components/package.json.ng16
Labels: ready, devOnly

#1029 fix(components/input-layout): clear button position when we didn't pass template #1022'
  libs/components/src/lib/components/input/common/input-layout/input-layout.component.html
  libs/components/src/lib/components/input/common/input-layout/input-layout.component.ts
Labels: ready

#1021 feat(components/input-select): added hint support for inner input #984
  apps/doc/src/app/components/input/input-select/input-select.component.html
  apps/doc/src/app/components/input/input-select/input-select.component.ts
  libs/components/src/lib/components/dropdowns/select/input-select.component.html
  libs/components/src/lib/components/dropdowns/select/input-select.component.ts
  libs/components/src/lib/components/input/common/input-hint/input-hint.directive.ts
Labels: ready

#967 feat(components/cron): to standalone
  libs/components/src/lib/components/cron/cron-inner.module.ts
  libs/components/src/lib/components/cron/cron.component.ts
  libs/components/src/lib/components/cron/cron.module.ts
  libs/components/src/lib/components/cron/pipes/cron-month.pipe.ts
  libs/components/src/lib/components/cron/pipes/cron-week.pipe.ts
Labels: ready, reopen

#965 feat(components/column-settings): to standalone
  libs/components/src/lib/components/column-settings/column-settings.component.ts
  libs/components/src/lib/components/column-settings/column-settings.module.ts
  libs/components/src/lib/components/column-settings/components/column-drop-list/column-drop-list.component.ts
  libs/components/src/lib/components/column-settings/pipes/column-icon.pipe.ts
Labels: ready, reopen

#924 fix: inputDateTime and inputDateMulti incorrect date set after manual…
  libs/components/src/lib/components/input/input-date-multi/input-date-multi.component.ts
  libs/components/src/lib/components/input/input-date-time/input-layout-date-time.component.ts
Labels: ready

#1039 fix: build error #1033
  libs/components/package.json.ng14
  libs/components/package.json.ng15
  libs/components/package.json.ng16
Labels: ready, devOnly

#1066 Fix/pre release ng 16
  .github/workflows/beta-publish-ng14.yml
  .github/workflows/beta-publish-ng15.yml
  .github/workflows/beta-publish-ng16.yml
  .github/workflows/main-publish-ng14.yml
  .github/workflows/main-publish-ng15.yml
  .github/workflows/main-publish-ng16.yml
  .github/workflows/pre-release-publish-ng14.yml
  .github/workflows/pre-release-publish-ng15.yml
  .github/workflows/pre-release-publish-ng16.yml
  apps/doc/src/app/components/table/table-example.component.html
  libs/ast/package.json
  libs/ast/package.json.ng14
  libs/ast/package.json.ng15
  libs/ast/package.json.ng16
  libs/ast/schematics-helpers/src/run-tasks-by-project-name/run-tasks-by-project-name.ts
  libs/components/package.json
  libs/components/package.json.ng16
  libs/helpers/package.json
  libs/helpers/package.json.ng16
  libs/nxmv/tsconfig.lib.json
  libs/plugin/package.json
  libs/plugin/package.json.ng16
  libs/schematics/package.json
  libs/schematics/package.json.ng16
  libs/theme/package.json.ng16
  package-lock.json
  package-lock.json.ng14
  package-lock.json.ng15
  package-lock.json.ng16
  package.json
  package.json.ng14
  package.json.ng15
  package.json.ng16
Labels: devOnly

#953 Fix: dropdown for tabs #844
  apps/doc/src/app/app.routes.ts
  apps/doc/src/app/components/input/input-chips/examples/input-chips-item-example/input-chips-item-example.component.html
  apps/doc/src/app/components/input/input-chips/input-chips-example.component.html
  apps/doc/src/app/components/input/input-chips/input-chips-example.component.ts
  apps/doc/src/app/components/listing-item/examples/base/listing-item-base-example.component.html
  apps/doc/src/app/components/listing-item/examples/base/listing-item-base-example.component.ts
  apps/doc/src/app/components/listing-item/examples/chips/listing-item-chips-example.component.html
  apps/doc/src/app/components/listing-item/examples/chips/listing-item-chips-example.component.ts
  apps/doc/src/app/components/listing-item/examples/setup-module.md
  apps/doc/src/app/components/listing-item/examples/with-instrumnets/listing-item-with-instruments-example.component.html
  apps/doc/src/app/components/listing-item/examples/with-instrumnets/listing-item-with-instruments-example.component.ts
  apps/doc/src/app/components/listing-item/listing-item-example.component.html
  apps/doc/src/app/components/listing-item/listing-item-example.component.ts
  apps/doc/src/app/components/listing-item/listing-item-example.module.ts
  apps/doc/src/app/components/tabs/examples/tabs-example-counter/tabs-example-counter.component.ts
  apps/doc/src/app/pages.ts
  libs/components/src/lib/components/chips/chips-item/chips-item.component.html
  libs/components/src/lib/components/chips/chips-item/chips-item.component.less
  libs/components/src/lib/components/chips/chips-item/chips-item.component.ts
  libs/components/src/lib/components/index.ts
  libs/components/src/lib/components/listing-item/index.ts
  libs/components/src/lib/components/listing-item/listing-item.component.html
  libs/components/src/lib/components/listing-item/listing-item.component.less
  libs/components/src/lib/components/listing-item/listing-item.component.ts
  libs/components/src/lib/components/tabs/components/tab.component.less
  libs/components/src/lib/components/tabs/pipes/icon-tabs.pipe.ts
  libs/components/src/lib/components/tabs/tabs.component.html
  libs/components/src/lib/components/tabs/tabs.component.less
  libs/components/src/lib/components/tabs/tabs.component.ts
  libs/doc/base/src/lib/components/navigation/navigation.component.html
  libs/doc/base/src/lib/components/navigation/navigation.component.less
  libs/doc/base/src/lib/components/navigation/navigation.module.ts
  libs/doc/base/src/lib/interfaces/page.ts
Labels: ready, moved, testing_done

#1071 fix: invalid icon name can be set in accordion live demo #947
  apps/doc/src/app/components/accordion/accordion-example.component.html
  apps/doc/src/app/components/accordion/accordion-example.component.ts
  apps/doc/src/app/components/accordion/accordion-example.module.ts
  apps/doc/src/app/components/buttons/button/button.component.ts
  libs/components/src/lib/components/accordion/components/accordion-item/accordion-item.component.less
Labels: ready, testing_done

#1034 fix: confirm popup live demo property works incorrect #570
  apps/doc/src/app/components/confirm-popup/confirm-popup-example.component.html
  apps/doc/src/app/components/confirm-popup/confirm-popup-example.component.ts
Labels: ready, testing_done

#1037 feat: colors v3 for hint, tooltip and confirm #1035
  libs/components/src/lib/directives/confirm-popup/confirm-popup-container.component.less
  libs/components/src/lib/directives/hint/hint-container.component.less
  libs/components/src/lib/directives/hint/hint.directive.ts
  libs/components/src/lib/directives/hint/hint.module.ts
  libs/components/src/lib/directives/tooltip/tooltip-container.component.less
  libs/theme/src/styles/theme/v3/dark.less
Labels: ready, testing_done

#1080 fix: navigation extra notification for active item change #571
  libs/components/src/lib/components/navigation/prizm-navigation.component.ts
Labels: ready, testing_done

#1083 fix(components/tabs): unsubscribe error #1079 #842 #1023
  libs/components/src/lib/components/tabs/components/tab.component.ts
Labels: ready, ready for dev, testing_done

#1043 chore: replaced fixed versions on patch relative
  apps/doc/src/app/code-demo/files/package.json.template
  libs/charts/base/package.json
  libs/charts/base/package.json.ng14
  libs/charts/base/package.json.ng16
  libs/components/package.json
  libs/components/package.json.ng14
  libs/components/package.json.ng16
  libs/core/package.json
  libs/core/package.json.ng14
  libs/core/package.json.ng16
  libs/helpers/package.json
  libs/helpers/package.json.ng14
  libs/helpers/package.json.ng16
  libs/i18n/package.json
  libs/i18n/package.json.ng14
  libs/i18n/package.json.ng16
  libs/icons/base/package.json
  libs/icons/base/package.json.ng14
  libs/icons/base/package.json.ng16
  libs/icons/flags/package.json
  libs/icons/flags/package.json.ng14
  libs/icons/flags/package.json.ng16
  libs/schematics/package.json
  libs/schematics/package.json.ng14
  libs/schematics/package.json.ng16
  libs/theme/package.json
  libs/theme/package.json.ng14
  libs/theme/package.json.ng16
Labels: devOnly
