Repository zyfra/Prizm, pull requests merged in 2024-12, with the labels that each got.

#2219 feat(components/date-relative): changed time to icon to new #1479
  libs/components/src/lib/components/input/input-date-relative/input-date-relative.models.ts
  libs/components/src/lib/components/input/input-date-relative/input-layout-date-relative.component.ts
  libs/icons/base/assets/16/letter-time-utc.svg
  libs/icons/base/assets/24/letter-time-utc.svg
  libs/icons/base/base/index.ts
  libs/icons/base/base/names/index.ts
  libs/icons/base/base/source/icon-set.ts
  libs/icons/base/base/source/index.ts
  libs/icons/base/base/source/letter-time-utc/index.ts
  libs/icons/base/base/source/letter-time-utc/ng-package.json
  libs/icons/base/base/source/letter-time-utc/prizmIcons-letter-time-utc.icon.ts
  libs/icons/base/base/source/prizm-icons.model.ts
  libs/icons/base/full/names/index.ts
  libs/icons/base/full/source/icon-set.ts
  libs/icons/base/full/source/index.ts
  libs/icons/base/full/source/letter-time-utc/index.ts
  libs/icons/base/full/source/letter-time-utc/ng-package.json
  libs/icons/base/full/source/letter-time-utc/prizmIcons-letter-time-utc.icon.ts
  libs/icons/base/full/source/prizm-icons.model.ts
  libs/icons/base/project.json
  libs/icons/base/src/styles/icons-base/prizm-base-icons-location.css
  libs/icons/base/src/styles/icons-base/prizm-base-icons-location.scss
  libs/icons/base/src/styles/icons-base/prizm-base-icons.css
  libs/icons/base/src/styles/icons-base/prizm-base-icons.eot
  libs/icons/base/src/styles/icons-base/prizm-base-icons.scss
  libs/icons/base/src/styles/icons-base/prizm-base-icons.ttf
  libs/icons/base/src/styles/icons-base/prizm-base-icons.woff
  libs/icons/base/src/styles/icons-base/prizm-base-icons.woff2
  libs/icons/base/src/styles/icons-full/prizm-full-icons-location.css
  libs/icons/base/src/styles/icons-full/prizm-full-icons-location.scss
  libs/icons/base/src/styles/icons-full/prizm-full-icons.css
  libs/icons/base/src/styles/icons-full/prizm-full-icons.eot
  libs/icons/base/src/styles/icons-full/prizm-full-icons.scss
  libs/icons/base/src/styles/icons-full/prizm-full-icons.ttf
  libs/icons/base/src/styles/icons-full/prizm-full-icons.woff
  libs/icons/base/src/styles/icons-full/prizm-full-icons.woff2
  libs/icons/loader/full/src/icons.ts
  libs/icons/loader/src/lib/icons.ts
Labels: availability:reviewed, availability:tested

#2193 fix(components/input): correction input hint behavior for input without ng-control #1966
  apps/doc/src/app/components/input/input-chips/input-chips-example.component.html
  apps/doc/src/app/components/input/input-text/examples/input-basic-example/input-basic-example.component.html
  libs/components/src/lib/components/chips/chips.component.html
  libs/components/src/lib/components/chips/chips.component.ts
  libs/components/src/lib/components/input/common/input-hint/input-hint.directive.ts
  libs/components/src/lib/components/input/input-text/input-text.component.ts
Labels: availability:reviewed, availability:tested, version:5

#2192 fix(components/tabs): autoscrolling to selected tab in dropdown added #1962
  libs/components/src/lib/components/tabs/tabs.component.html
  libs/components/src/lib/components/tabs/tabs.component.ts
Labels: availability:reviewed, availability:tested, version:5

#2177 feat(components/time-picker): add new component #2103
  apps/doc/src/app/app.routes.ts
  apps/doc/src/app/components/time-picker/examples/setup-module.md
  apps/doc/src/app/components/time-picker/examples/time-picker-basic-example/time-picker-basic-example.component.html
  apps/doc/src/app/components/time-picker/examples/time-picker-basic-example/time-picker-basic-example.component.less
  apps/doc/src/app/components/time-picker/examples/time-picker-basic-example/time-picker-basic-example.component.ts
  apps/doc/src/app/components/time-picker/examples/time-picker-min-max-example/time-picker-min-max-example.component.html
  apps/doc/src/app/components/time-picker/examples/time-picker-min-max-example/time-picker-min-max-example.component.less
  apps/doc/src/app/components/time-picker/examples/time-picker-min-max-example/time-picker-min-max-example.component.ts
  apps/doc/src/app/components/time-picker/time-picker-example.component.html
  apps/doc/src/app/components/time-picker/time-picker-example.component.less
  apps/doc/src/app/components/time-picker/time-picker-example.component.ts
  apps/doc/src/app/components/time-picker/time-picker-example.module.ts
  apps/doc/src/app/pages.ts
  libs/components/src/lib/components/cron/cron-ui-base.state.ts
  libs/components/src/lib/components/cron/cron-ui-day.state.ts
  libs/components/src/lib/components/cron/cron-ui-hour.state.ts
  libs/components/src/lib/components/cron/util.ts
  libs/components/src/lib/components/index.ts
  libs/components/src/lib/components/input/input-time/input-layout-time.component.ts
  libs/components/src/lib/components/internal/index.ts
  libs/components/src/lib/components/internal/primitive-time-pagination/index.ts
  libs/components/src/lib/components/internal/primitive-time-pagination/primitive-time-pagination.component.html
  libs/components/src/lib/components/internal/primitive-time-pagination/primitive-time-pagination.component.less
  libs/components/src/lib/components/internal/primitive-time-pagination/primitive-time-pagination.component.ts
  libs/components/src/lib/components/internal/primitive-time-pagination/types/types.ts
  libs/components/src/lib/components/internal/primitive-time-picker/index.ts
  libs/components/src/lib/components/internal/primitive-time-picker/primitive-time-picker.component.html
  libs/components/src/lib/components/internal/primitive-time-picker/primitive-time-picker.component.less
  libs/components/src/lib/components/internal/primitive-time-picker/primitive-time-picker.component.ts
  libs/components/src/lib/components/internal/primitive-time-picker/types/types.ts
  libs/components/src/lib/components/time-picker/index.ts
  libs/components/src/lib/components/time-picker/pipes/picker-disable-items.pipe.ts
  libs/components/src/lib/components/time-picker/pipes/picker-disable.pipe.ts
  libs/components/src/lib/components/time-picker/pipes/time-sheet.pipe.ts
  libs/components/src/lib/components/time-picker/time-picker.component.html
  libs/components/src/lib/components/time-picker/time-picker.component.less
  libs/components/src/lib/components/time-picker/time-picker.component.spec.ts
  libs/components/src/lib/components/time-picker/time-picker.component.ts
  libs/components/src/lib/components/time-picker/types/types.ts
  libs/components/src/lib/pipes/number-with-zero/index.ts
  libs/components/src/lib/pipes/number-with-zero/number-with-zero.pipe.ts
  libs/components/src/lib/tokens/i18n.ts
  libs/components/src/lib/util/common/get-arr-string-numbers.ts
  libs/doc/base/src/lib/components/host/host-element.service.ts
  libs/i18n/src/lib/interfaces/language.ts
  libs/i18n/src/lib/languages/english/english.ts
  libs/i18n/src/lib/languages/english/time-pagination.ts
  libs/i18n/src/lib/languages/english/time-picker.ts
  libs/i18n/src/lib/languages/russian/russian.ts
  libs/i18n/src/lib/languages/russian/time-pagination.ts
  libs/i18n/src/lib/languages/russian/time-picker.ts
Labels: availability:reviewed, availability:tested, version:5

#2212 fix(components/toast): toast content width changed #305
  libs/components/src/lib/components/toast/toast/toast.component.less
Labels: availability:reviewed, availability:tested, version:5

#2252 release 1.19.2, 2.16.2, 3.15.2
  .github/workflows/beta-publish-ng14.yml
  .github/workflows/beta-publish-ng15.yml
  .github/workflows/beta-publish-ng16.yml
  .github/workflows/pre-release-publish-ng14.yml
  .github/workflows/pre-release-publish-ng15.yml
  .github/workflows/pre-release-publish-ng16.yml
  apps/doc/src/app/about-prizm/changelog/CHANGELOG.md
  apps/doc/src/app/components/input/input-select/examples/base/select-base-example.component.ts
  apps/doc/src/app/version-manager/current.const.ts.ng14
  apps/doc/src/app/version-manager/current.const.ts.ng15
  apps/doc/src/app/version-manager/current.const.ts.ng16
  apps/doc/src/app/version-manager/versions.constants.ts
  libs/ast/package.json.ng14
  libs/ast/package.json.ng15
  libs/ast/package.json.ng16
  libs/charts/base/package.json.ng14
  libs/charts/base/package.json.ng15
  libs/charts/base/package.json.ng16
  libs/components/package.json.ng14
  libs/components/package.json.ng15
  libs/components/package.json.ng16
  libs/components/src/lib/components/dropdowns/select/input-select.component.html
  libs/components/src/lib/components/dropdowns/select/input-select.component.ts
  libs/components/src/lib/components/input/common/base/input-ng-control.class.ts
  libs/core/package.json.ng14
  libs/core/package.json.ng15
  libs/core/package.json.ng16
  libs/helpers/package.json.ng14
  libs/helpers/package.json.ng15
  libs/helpers/package.json.ng16
  libs/i18n/package.json.ng14
  libs/i18n/package.json.ng15
  libs/i18n/package.json.ng16
  libs/icons/base/package.json.ng14
  libs/icons/base/package.json.ng15
  libs/icons/base/package.json.ng16
  libs/icons/flags/package.json.ng14
  libs/icons/flags/package.json.ng15
  libs/icons/flags/package.json.ng16
  libs/nxmv/package.json.ng14
  libs/nxmv/package.json.ng15
  libs/nxmv/package.json.ng16
  libs/plugin/package.json.ng14
  libs/plugin/package.json.ng15
  libs/plugin/package.json.ng16
  libs/schematics/package.json.ng14
  libs/schematics/package.json.ng15
  libs/schematics/package.json.ng16
  libs/theme/package.json.ng14
  libs/theme/package.json.ng15
  libs/theme/package.json.ng16
  package.json
  package.json.ng14
  package.json.ng15
  package.json.ng16
Labels: availability:reviewed, availability:tested, version:3

#2237 release 5.4.0
  .github/PULL_REQUEST_TEMPLATE/prepare_release_for_5.md
  apps/doc/src/app/about-prizm/changelog/CHANGELOG.md
  apps/doc/src/app/components/table-advanced/examples/table-editable-layouts-example/table-editable-layouts-example.component.html
  apps/doc/src/app/components/table/examples/table-editable-row-example/table-editable-row-example.component.html
  apps/doc/src/app/version-manager/current.const.ts
  apps/doc/src/app/version-manager/versions.constants.ts
  apps/doc/src/app/version-manager/versions.constants.ts.ng18
  libs/addons/query-builder/package.json
  libs/ast/package.json
  libs/charts/base/package.json
  libs/components/package.json
  libs/components/src/lib/components/dropdowns/combobox/combobox.component.html
  libs/components/src/lib/components/dropdowns/combobox/combobox.component.ts
  libs/components/src/lib/components/input/common/input-layout/input-layout-inserted.component.less
  libs/components/src/lib/components/input/common/input-layout/input-layout.component.html
  libs/components/src/lib/components/input/common/input-layout/input-layout.component.less
  libs/components/src/lib/components/input/input-number/input-number.component.ts
  libs/components/src/lib/components/toast/toast/toast.component.less
  libs/core/package.json
  libs/helpers/package.json
  libs/i18n/package.json
  libs/icons/base/package.json
  libs/icons/flags/package.json
  libs/icons/loader/package.json
  libs/nxmv/package.json
  libs/nxmv/src/generators/apply/index.ts
  libs/nxmv/src/generators/apply/schema.d.ts
  libs/plugin/package.json
  libs/schematics/package.json
  libs/schematics/src/ng-add/consts.ts
  libs/theme/package.json
  local/package.json
  nxmv.json
  nxmv.json.ng18
  package-lock.json
  package.json
Labels: availability:reviewed, availability:tested

#2250 fix(doc): search after first clear did not work #0
  .github/workflows/pr-ng17.yml
  package-lock.json
  package-lock.json.ng17
  package.json
  package.json.ng17
Labels: availability:reviewed, availability:tested, version:4

#2262 fix(components/toast): toast content width changed #305 v4
  libs/components/src/lib/components/toast/toast/toast.component.less
Labels: availability:reviewed, availability:tested, version:4

#2268 fix(components/switcher): add type button to switcher button #2254 v4
  apps/doc/src/app/components/switcher/switcher-example.module.ts
  libs/components/src/lib/components/switcher/components/switcher-item/switcher-item.component.html
Labels: availability:reviewed, availability:tested, version:4

#2266 fix(components/tabs): autoscroll to selected tab in dropdown added #1962
  libs/components/src/lib/components/tabs/tabs.component.html
  libs/components/src/lib/components/tabs/tabs.component.ts
Labels: availability:reviewed, availability:tested, version:4

#2246 fix(components/input-layout-date-time): update calendar view after control value changed #2243
  apps/doc/src/app/components/input/input-layout-date-range/examples/base/input-layout-date-range-base-example.component.html
  apps/doc/src/app/components/input/input-layout-date-range/examples/base/input-layout-date-range-base-example.component.ts
  apps/doc/src/app/components/input/input-layout-date-range/input-layout-date-range.module.ts
  apps/doc/src/app/components/input/input-layout-date-time-range/examples/base/input-layout-date-time-range-base-example.component.html
  apps/doc/src/app/components/input/input-layout-date-time-range/examples/base/input-layout-date-time-range-base-example.component.ts
  apps/doc/src/app/components/input/input-layout-date-time-range/input-layout-date-time-range.module.ts
  apps/doc/src/app/components/input/input-layout-date/examples/base/input-layout-date-base-example.component.html
  apps/doc/src/app/components/input/input-layout-date/examples/base/input-layout-date-base-example.component.ts
  libs/components/src/lib/components/calendar-range/calendar-range.component.ts
  libs/components/src/lib/components/input/input-date-time-range/input-layout-date-time-range.component.ts
  libs/components/src/lib/components/input/input-date-time/input-layout-date-time.component.ts
  libs/components/src/lib/components/input/input-date/input-layout-date.component.ts
  libs/components/src/lib/components/internal/primitive-year-month-pagination/primitive-year-month-pagination.component.ts
Labels: availability:reviewed, availability:tested

#2267 fix(components/input-layout-date-time): update calendar view after control value changed #2243 v4
  apps/doc/src/app/components/input/input-layout-date-range/examples/base/input-layout-date-range-base-example.component.html
  apps/doc/src/app/components/input/input-layout-date-range/examples/base/input-layout-date-range-base-example.component.ts
  apps/doc/src/app/components/input/input-layout-date-range/input-layout-date-range.module.ts
  apps/doc/src/app/components/input/input-layout-date-time-range/examples/base/input-layout-date-time-range-base-example.component.html
  apps/doc/src/app/components/input/input-layout-date-time-range/examples/base/input-layout-date-time-range-base-example.component.ts
  apps/doc/src/app/components/input/input-layout-date-time-range/input-layout-date-time-range.module.ts
  apps/doc/src/app/components/input/input-layout-date/examples/base/input-layout-date-base-example.component.html
  apps/doc/src/app/components/input/input-layout-date/examples/base/input-layout-date-base-example.component.ts
  libs/components/src/lib/components/calendar-range/calendar-range.component.ts
  libs/components/src/lib/components/input/input-date-time-range/input-layout-date-time-range.component.ts
  libs/components/src/lib/components/input/input-date-time/input-layout-date-time.component.ts
  libs/components/src/lib/components/input/input-date/input-layout-date.component.ts
  libs/components/src/lib/components/internal/primitive-calendar-range/primitive-calendar-range.component.ts
  libs/components/src/lib/components/internal/primitive-year-month-pagination/primitive-year-month-pagination.component.ts
Labels: availability:reviewed, availability:tested, version:4

#2272 fix(components/table): add styles for focus within in inserted inputs
  libs/components/src/lib/components/input/common/input-layout/input-layout-inserted.component.less
  libs/components/src/lib/components/table/td/td.component.less
Labels: availability:reviewed, availability:review, availability:tested, version:5

#2274 feat(chore): release 5.4.1
  .github/PULL_REQUEST_TEMPLATE/prepare_release_for_5.md
  apps/doc/src/app/about-prizm/changelog/CHANGELOG.md
  apps/doc/src/app/version-manager/current.const.ts
  apps/doc/src/app/version-manager/versions.constants.ts
  libs/addons/query-builder/package.json
  libs/ast/package.json
  libs/charts/base/package.json
  libs/components/package.json
  libs/core/package.json
  libs/helpers/package.json
  libs/i18n/package.json
  libs/icons/base/package.json
  libs/icons/flags/package.json
  libs/icons/loader/package.json
  libs/nxmv/package.json
  libs/plugin/package.json
  libs/schematics/package.json
  libs/schematics/src/ng-add/consts.ts
  libs/theme/package.json
  local/package.json
  nxmv.json
  package.json
  package.json.ng18
Labels: availability:reviewed, availability:tested, version:5
