Repository zyfra/Prizm, pull requests merged in 2024-09, with the labels that each got.

#2065 feat(doc): add link to github issue page #000 v4
  apps/doc/src/app/about-prizm/contacts/contacts.component.html
  apps/doc/src/app/how-to-work/contributing/contributing.component.html
  apps/doc/src/app/how-to-work/set-task/set-task.component.html
Labels: availability:reviewed, availability:tested, version:4

#2037 fix(doc/version): add v5 version to v4 #2035
  apps/doc/src/app/version-manager/versions.constants.ts
Labels: availability:reviewed, availability:tested, version:4

#2034 feat(components/input-select): fix position search input for dropdown #1981
  libs/components/src/lib/components/dropdowns/multi-select/input-multi-select.component.html
  libs/components/src/lib/components/dropdowns/multi-select/input-multi-select.component.less
  libs/components/src/lib/components/dropdowns/select/input-select.component.html
  libs/components/src/lib/components/dropdowns/select/input-select.component.less
Labels: availability:reviewed, availability:tested, version:4

#2030 feat(components/checkbox): add box shadow for disabled radio and checkbox and radio v4 #2024
  libs/components/src/lib/components/checkbox/checkbox.component.less
  libs/components/src/lib/components/radio/prizm-radio-button.component.less
Labels: availability:reviewed, availability:tested, version:4

#2018 fix(components/table): table sort cursor correction #1986
  libs/components/src/lib/components/table/th/th.component.html
  libs/components/src/lib/components/table/th/th.style.less
Labels: availability:reviewed, availability:tested, version:4

#2016 fix(components/tabs): fix Cannot read properties of undefined (reading 'disconnect') #2013
  libs/components/src/lib/components/tabs/tabs.component.ts
Labels: availability:reviewed, availability:tested, version:4

#1976 fix(components/button): correct outline buttons height #1399
  libs/components/src/lib/components/button/button.component.less
Labels: state:ready, availability:reviewed, availability:tested, version:4

#1967 Fix/navigation tree item height-1964
  apps/doc/src/app/about-prizm/changelog/CHANGELOG.md
  apps/doc/src/app/components/tree/tree.component.html
  apps/doc/src/app/components/tree/tree.component.ts
  libs/components/src/lib/components/navigation-menu/components/prizm-navigation-menu/prizm-navigation-menu.component.less
  libs/components/src/lib/components/tree/components/tree-item-content/tree-item-content.component.less
Labels: state:ready, availability:reviewed, availability:tested, version:4

#1886 feat(components/paginator): add left direction support #1154
  apps/doc/src/app/components/paginator/examples/paginator-basic-left-example/paginator-basic-left-example.component.html
  apps/doc/src/app/components/paginator/examples/paginator-basic-left-example/paginator-basic-left-example.component.less
  apps/doc/src/app/components/paginator/examples/paginator-basic-left-example/paginator-basic-left-example.component.ts
  apps/doc/src/app/components/paginator/paginator-example.component.html
  apps/doc/src/app/components/paginator/paginator-example.component.ts
  apps/doc/src/app/components/paginator/paginator-example.module.ts
  libs/components/src/lib/components/paginator/interfaces/prizm-paginator.interface.ts
  libs/components/src/lib/components/paginator/paginator.component.less
  libs/components/src/lib/components/paginator/paginator.component.ts
Labels: state:ready, availability:reviewed, availability:tested, version:4

#1837 feat(doc/slider): add form control for slider #531
  apps/doc/src/app/components/slider/examples/slider-basic-example/slider-basic-example.component.ts
  apps/doc/src/app/components/slider/examples/slider-range-example/slider-range-example.component.ts
  apps/doc/src/app/components/slider/examples/slider-step-example/slider-step-example.component.ts
  apps/doc/src/app/components/slider/examples/slider-vertical-example/slider-vertical-example.component.ts
  apps/doc/src/app/components/slider/slider.component.html
  apps/doc/src/app/components/slider/slider.component.ts
  apps/doc/src/app/components/slider/slider.module.ts
  libs/components/src/lib/components/slider/slider.component.ts
Labels: state:ready, availability:tested, version:4

#1819 Feat/file upload translations 1769
  libs/components/src/lib/components/file-upload/file-upload.component.html
  libs/components/src/lib/components/file-upload/pipes/file-size.pipe.ts
  libs/i18n/src/lib/interfaces/language.ts
  libs/i18n/src/lib/languages/english/file-upload.ts
  libs/i18n/src/lib/languages/russian/file-upload.ts
Labels: state:ready, availability:reviewed, availability:tested, version:4

#1764 feat(components/accordion): border-bottom can be added to accordion item header #1322
  apps/doc/src/app/components/accordion/accordion-example.component.html
  apps/doc/src/app/components/accordion/accordion-example.component.ts
  apps/doc/src/app/components/accordion/examples/accordion-basic-example/accordion-basic-example.component.html
  libs/components/src/lib/components/accordion/components/accordion-item/accordion-item.component.less
Labels: state:ready, availability:tested, version:4

#2064 feat(doc): add link to github issue page #000
  apps/doc/src/app/about-prizm/contacts/contacts.component.html
  apps/doc/src/app/how-to-work/contributing/contributing.component.html
  apps/doc/src/app/how-to-work/set-task/set-task.component.html
Labels: availability:reviewed, availability:tested, version:5

#2036 fix(doc/versions): angular version correction in doc for v5 #2035
  apps/doc/src/app/version-manager/versions.constants.ts
  apps/doc/src/app/version-manager/versions.constants.ts.ng18
Labels: availability:reviewed, availability:tested, version:5

#2033 feat(components/input-select): fix position search input for dropdown #1981
  libs/components/src/lib/components/dropdowns/multi-select/input-multi-select.component.html
  libs/components/src/lib/components/dropdowns/multi-select/input-multi-select.component.less
  libs/components/src/lib/components/dropdowns/select/input-select.component.html
  libs/components/src/lib/components/dropdowns/select/input-select.component.less
Labels: availability:reviewed, availability:tested, version:5

#2012 feat(components/accordion): border-bottom can be dded to accordion item header #1322
  apps/doc/src/app/components/accordion/accordion-example.component.html
  apps/doc/src/app/components/accordion/accordion-example.component.ts
  apps/doc/src/app/components/accordion/examples/accordion-basic-example/accordion-basic-example.component.html
  libs/components/src/lib/components/accordion/components/accordion-item/accordion-item.component.less
Labels: availability:reviewed, availability:tested, version:5

#2010 Feat/file upload translations 1769 v5
  libs/components/src/lib/components/file-upload/file-upload.component.html
  libs/components/src/lib/components/file-upload/pipes/file-size.pipe.ts
  libs/i18n/src/lib/interfaces/language.ts
  libs/i18n/src/lib/languages/english/file-upload.ts
  libs/i18n/src/lib/languages/russian/file-upload.ts
Labels: availability:reviewed, availability:tested, version:5

#2020 fix(components/table): table sort cursor correction #1986
  libs/components/src/lib/components/table/th/th.component.html
  libs/components/src/lib/components/table/th/th.style.less
Labels: availability:reviewed, availability:tested, version:5

#2009 Feat/slider livedemo improvement 531 v5
  apps/doc/src/app/components/slider/examples/slider-basic-example/slider-basic-example.component.ts
  apps/doc/src/app/components/slider/examples/slider-range-example/slider-range-example.component.ts
  apps/doc/src/app/components/slider/examples/slider-step-example/slider-step-example.component.ts
  apps/doc/src/app/components/slider/examples/slider-vertical-example/slider-vertical-example.component.ts
  apps/doc/src/app/components/slider/slider.component.html
  apps/doc/src/app/components/slider/slider.component.ts
  apps/doc/src/app/components/slider/slider.module.ts
  libs/components/src/lib/components/slider/slider.component.ts
Labels: availability:reviewed, availability:tested, version:5

#2008 feat(components/paginator): update paginator dictionary #1840
  apps/doc/src/app/components/paginator/examples/paginator-with-labels-example/paginator-with-labels-example.component.html
  apps/doc/src/app/components/paginator/paginator-example.module.ts
  libs/components/src/lib/components/paginator/paginator.component.html
  libs/components/src/lib/components/paginator/paginator.component.ts
  libs/i18n/src/lib/interfaces/language.ts
  libs/i18n/src/lib/languages/english/paginator.ts
  libs/i18n/src/lib/languages/russian/paginator.ts
Labels: availability:reviewed, availability:tested, version:5

#2006 Feat/paginator left 1154 v5
  apps/doc/src/app/components/paginator/examples/paginator-basic-left-example/paginator-basic-left-example.component.html
  apps/doc/src/app/components/paginator/examples/paginator-basic-left-example/paginator-basic-left-example.component.less
  apps/doc/src/app/components/paginator/examples/paginator-basic-left-example/paginator-basic-left-example.component.ts
  apps/doc/src/app/components/paginator/paginator-example.component.html
  apps/doc/src/app/components/paginator/paginator-example.component.ts
  apps/doc/src/app/components/paginator/paginator-example.module.ts
  libs/components/src/lib/components/paginator/interfaces/prizm-paginator.interface.ts
  libs/components/src/lib/components/paginator/paginator.component.less
  libs/components/src/lib/components/paginator/paginator.component.ts
Labels: availability:reviewed, availability:tested, version:5

#2005 feat(components/input-date-time): add time restrictions for min max values #1570 v5
  apps/doc/src/app/components/input/input-layout-date-time-range/examples/base/input-layout-date-time-range-base-example.component.html
  apps/doc/src/app/components/input/input-layout-date-time-range/examples/base/input-layout-date-time-range-base-example.component.ts
  libs/components/src/lib/@core/date-time/date-time.ts
  libs/components/src/lib/components/calendar-range/calendar-range.component.html
  libs/components/src/lib/components/input/input-date-time-range/input-layout-date-time-range.component.html
  libs/components/src/lib/components/input/input-date-time-range/input-layout-date-time-range.component.ts
  libs/components/src/lib/components/input/input-date-time/input-layout-date-time.component.html
  libs/components/src/lib/components/input/input-date-time/input-layout-date-time.component.ts
  libs/components/src/lib/pipes/month/month.pipe.ts
  libs/components/src/lib/pipes/time-constraints/index.ts
  libs/components/src/lib/pipes/time-constraints/time-constraints.pipe.ts
Labels: availability:reviewed, availability:tested, version:5

#2002 fix(components/button): correct outline buttons height #1399 v5
  libs/components/src/lib/components/button/button.component.less
Labels: availability:reviewed, availability:tested, version:5

#2001 fix(components): added icons to peerDependencies #1989
  libs/components/package.json
  libs/components/package.json.ng17
Labels: devOnly, availability:reviewed, version:4

#1805 feat: update mr checklist template
  .gitlab/merge_request_templates/mr_template.md
Labels: state:ready, devOnly, availability:reviewed, version:4
