Repository zyfra/Prizm, pull requests merged in 2024-08, with the labels that each got.

#1931 fix(components/chips): fix spelling error in css variable name for height
  apps/doc/src/app/components/input/input-chips/input-chips-example.component.html
  libs/components/src/lib/components/chips/chips-item/chips-item.component.less
  libs/components/src/lib/components/chips/chips.component.less
  libs/components/src/lib/components/dropdowns/multi-select/input-multi-select.component.less
Labels: devOnly, type:bc, availability:reviewed, version:5

#1929 feat(components/mask): remove deprecated function prizmCreateDateMask
  libs/components/src/lib/@core/mask/create-date-mask.ts
Labels: devOnly, type:bc, availability:reviewed, version:5

#1928 feat(components): remove deprecated exports #1849
  apps/doc/src/app/components/input/input-select/examples/with-transformer/select-with-transformer-example.component.ts
  libs/components/src/lib/components/dropdowns/select/select.model.ts
  libs/components/src/lib/components/dropdowns/select/select.options.ts
  libs/components/src/lib/components/grid/components/grid-item/grid-item.component.ts
  libs/components/src/lib/components/grid/grid.component.ts
  libs/components/src/lib/components/indicator/indicator.component.ts
  libs/components/src/lib/components/switcher/components/switcher-item/switcher-item.component.ts
Labels: devOnly, type:bc, availability:review, version:5

#1862 fix(chore): moved required deps to dependencies group #1861
  libs/charts/base/ng-package.json
  libs/charts/base/package.json
  libs/components/package.json
Labels: devOnly, availability:reviewed, availability:review, version:4

#1943 fix(components/multiselect): usage with transformers should cover case with selectAll option #1919
  apps/doc/src/app/components/input/input-multi-select/examples/with-transformer/multi-select-with-transformer-example.component.html
  apps/doc/src/app/components/input/input-multi-select/examples/with-transformer/multi-select-with-transformer-example.component.ts
  libs/components/src/lib/components/dropdowns/multi-select/input-multi-select.component.ts
Labels: availability:reviewed, availability:review, availability:tested, version:4

#1938 fix(components/tabs): template usage for tabs listing #1859
  apps/doc/src/app/components/tabs/examples/tabs-example-component/tabs-example-component.component.ts
  apps/doc/src/app/components/tabs/examples/tabs-example-component/tabs-example-content-component.component.ts
  libs/components/src/lib/components/tabs/tabs.component.html
Labels: availability:reviewed, availability:tested, version:4

#1907 fix(components/input-icon-button): icon button should be hidden in disabled forms #1727 #1728
  libs/components/src/lib/components/input/common/input-icon-button/input-icon-button.component.less
  libs/components/src/lib/components/input/common/input-layout/input-layout.component.less
  libs/components/src/lib/components/input/common/input-layout/input-layout.component.ts
Labels: state:ready, availability:tested, version:4

#1908 fix(components/input-icon-button): icon button should be hidden in disabled forms #1727 #1728
  libs/components/src/lib/components/input/common/input-icon-button/input-icon-button.component.less
  libs/components/src/lib/components/input/common/input-layout/input-layout.component.less
Labels: availability:reviewed, availability:tested, version:3

#1944 fix(components/tabs): template usage for tabs listing #1859
  apps/doc/src/app/components/tabs/examples/tabs-example-component/tabs-example-component.component.ts
  apps/doc/src/app/components/tabs/examples/tabs-example-component/tabs-example-content-component.component.ts
  libs/components/src/lib/components/tabs/tabs.component.html
Labels: availability:reviewed, availability:tested, version:3

#1957 feat(doc): up versions from v3 for v4 #000
  apps/doc/src/app/version-manager/versions.constants.ts
Labels: availability:reviewed, version:4

#1945 fix(components/file-upload): emit events for clear files fix #1848
  libs/components/src/lib/components/file-upload/file-upload.component.ts
Labels: state:ready, availability:reviewed, availability:tested, version:3

#1959 up versions to 4.3.8
  apps/doc/src/app/version-manager/versions.constants.ts
Labels: state:ready, devOnly, availability:reviewed, version:3

#1960 fix(theme): v3 devided font location #1412
  apps/doc/src/app/components/dialogs/sidebar/examples/base/base.component.ts
  libs/theme/src/styles/font.less
  libs/theme/src/styles/fonts/location.less
  libs/theme/src/styles/styles.less
  libs/theme/src/styles/styles_.less
Labels: state:ready, availability:reviewed, availability:tested, version:3

#1956 feat(chore): release 3.15.1
  .github/workflows/beta-publish-ng14.yml
  .github/workflows/beta-publish-ng15.yml
  .github/workflows/beta-publish-ng16.yml
  .github/workflows/main-publish-ng14.yml
  .github/workflows/main-publish-ng15.yml
  .github/workflows/main-publish-ng16.yml
  .github/workflows/pre-release-publish-ng14.yml
  .github/workflows/pre-release-publish-ng15.yml
  .github/workflows/pre-release-publish-ng16.yml
  apps/doc/src/app/about-prizm/changelog/CHANGELOG.md
  apps/doc/src/app/components/input/input-multi-select/examples/with-transformer/multi-select-with-transformer-example.component.ts
  apps/doc/src/app/version-manager/current.const.ts.ng14
  apps/doc/src/app/version-manager/current.const.ts.ng15
  apps/doc/src/app/version-manager/current.const.ts.ng16
  apps/doc/src/app/version-manager/versions.constants.ts
  libs/ast/package.json.ng14
  libs/ast/package.json.ng15
  libs/ast/package.json.ng16
  libs/charts/base/package.json.ng14
  libs/charts/base/package.json.ng15
  libs/charts/base/package.json.ng16
  libs/components/package.json.ng14
  libs/components/package.json.ng15
  libs/components/package.json.ng16
  libs/components/src/lib/components/chips/chips.component.less
  libs/components/src/lib/components/input/common/input-layout/input-layout-textarea.component.less
  libs/core/package.json.ng14
  libs/core/package.json.ng15
  libs/core/package.json.ng16
  libs/helpers/package.json.ng14
  libs/helpers/package.json.ng15
  libs/helpers/package.json.ng16
  libs/i18n/package.json.ng14
  libs/i18n/package.json.ng15
  libs/i18n/package.json.ng16
  libs/icons/base/package.json.ng14
  libs/icons/base/package.json.ng15
  libs/icons/base/package.json.ng16
  libs/icons/flags/package.json.ng14
  libs/icons/flags/package.json.ng15
  libs/icons/flags/package.json.ng16
  libs/nxmv/package.json.ng14
  libs/nxmv/package.json.ng15
  libs/nxmv/package.json.ng16
  libs/plugin/package.json.ng14
  libs/plugin/package.json.ng15
  libs/plugin/package.json.ng16
  libs/schematics/package.json.ng14
  libs/schematics/package.json.ng15
  libs/schematics/package.json.ng16
  libs/theme/package.json.ng14
  libs/theme/package.json.ng15
  libs/theme/package.json.ng16
  package.json.ng14
  package.json.ng15
  package.json.ng16
Labels: state:ready, availability:reviewed, availability:tested, version:3

#1969 feat(chore): run release after created tag #000
  .github/workflows/main-publish-ng14.yml
Labels: devOnly

#1970 feat(chore): run release after created tag #000
  .github/workflows/main-publish-ng14.yml
  .github/workflows/main-publish-ng15.yml
  .github/workflows/main-publish-ng16.yml
Labels: devOnly

#1971 feat: run release when create tag
  .github/workflows/main-publish-ng14.yml
  .github/workflows/main-publish-ng15.yml
  .github/workflows/main-publish-ng16.yml
  .github/workflows/main-publish-ng17.yml
  .github/workflows/released.yml
Labels: devOnly

#1972 feat(chore): run release after created tag #000
  .github/workflows/main-publish-ng14.yml
  .github/workflows/main-publish-ng15.yml
  .github/workflows/main-publish-ng16.yml
  .github/workflows/main-publish-ng17.yml
  .github/workflows/released.yml
Labels: devOnly

#1973 feat(chore): run release after created tag #000
  .github/workflows/main-publish-ng14.yml
  .github/workflows/main-publish-ng15.yml
  .github/workflows/main-publish-ng16.yml
  .github/workflows/main-publish-ng17.yml
Labels: devOnly

#1974 feat(ci): relase after push tag #000
  .github/workflows/main-publish-ng14.yml
  .github/workflows/main-publish-ng15.yml
  .github/workflows/main-publish-ng16.yml
  .github/workflows/main-publish-ng17.yml
  .github/workflows/released.yml
Labels: devOnly
