Repository zyfra/Prizm, pull requests merged in 2024-03, with the labels that each got.

#1401 Fix/doc shadow color #900
  apps/doc/src/app/guidelines/colors/components/palette/palette.component.css
  apps/doc/src/app/guidelines/colors/components/palette/palette.component.html
  apps/doc/src/app/guidelines/colors/components/theme-colors/theme-colors.component.css
  apps/doc/src/app/guidelines/colors/components/theme-colors/theme-colors.component.html
  apps/doc/src/app/guidelines/theme/components/theme-for-designers/theme-for-designers.component.ts
Labels: availability:review, availability:tested

#1418 feat: input chips css class for single line added #1370 //breaking change
  apps/doc/src/app/components/input/input-chips/examples/input-chips-basic-example/input-chips-basic-example.component.less
  apps/doc/src/app/components/input/input-chips/examples/input-chips-item-example/input-chips-item-example.component.less
  apps/doc/src/app/components/input/input-chips/examples/input-chips-outer-example/input-chips-outer-example.component.less
  apps/doc/src/app/components/input/input-chips/input-chips-example.component.html
  apps/doc/src/app/components/input/input-chips/input-chips-example.component.less
  apps/doc/src/app/components/input/input-chips/input-chips-example.component.ts
  libs/components/src/lib/components/chips/chips.component.less
  libs/components/src/lib/components/chips/chips.component.ts
Labels: type:bc, availability:review, availability:tested

#1409 fix: favicon fo doc #1345
  apps/doc/src/favicon.ico
Labels: availability:review, availability:tested

#1408 feat: removed lodash and lodash-es #1134
  apps/doc/src/app/components/table/examples/table-column-settings-example/pipes/header-sticky-pipe.pipe.ts
  apps/doc/src/app/components/table/examples/table-tree-example/table-tree-example.component.ts
  libs/ast/schematics-helpers/src/run-tasks-by-project-name/run-tasks-by-project-name.ts
  libs/charts/base/src/lib/service/charts-theme.service.ts
  libs/components/src/lib/components/column-settings/column-settings.component.ts
  libs/doc/base/src/lib/components/documentation/documentation-property-connector.directive.ts
  libs/doc/base/src/lib/components/documentation/documentation.component.ts
  libs/helpers/src/lib/util/compare/compare.spec.ts
  libs/helpers/src/lib/util/difference.spec.ts
  libs/helpers/src/lib/util/difference.ts
  libs/helpers/src/lib/util/index.ts
  libs/helpers/src/lib/util/is-equal.ts
  libs/helpers/src/lib/util/is-eual.spec.ts
  libs/helpers/src/lib/util/merge.spec.ts
  libs/helpers/src/lib/util/merge.ts
  libs/helpers/src/lib/util/order-by.spec.ts
  libs/helpers/src/lib/util/order-by.ts
  libs/helpers/tsconfig.lib.json
  libs/nxmv/src/generators/apply/index.ts
  package-lock.json
  package-lock.json.ng17
  package.json
  package.json.ng17
  tsconfig.base.json
Labels: devOnly, availability:review, availability:tested

#1402 feat: i18n support for base input text of validation #1354
  apps/doc/src/app/components/input/input-text/examples/input-validation-custom-example/input-validation-custom-example.component.ts
  apps/doc/src/app/components/input/input-text/examples/input-validation-custom-example/input-validation-custom-texts.service.ts
  libs/components/src/lib/components/input/common/base/input-invalid-text-base-class.directive.ts
  libs/components/src/lib/components/input/common/input-layout/input-layout.component.ts
  libs/components/src/lib/components/input/common/services/input-invalid-subtext.service.ts
  libs/i18n/src/lib/interfaces/language.ts
  libs/i18n/src/lib/languages/english/english.ts
  libs/i18n/src/lib/languages/english/input.ts
  libs/i18n/src/lib/languages/russian/input.ts
  libs/i18n/src/lib/languages/russian/russian.ts
Labels: availability:review, availability:tested

#1410 fix(chore): stackblitz import style error #1209
  apps/doc/src/app/code-demo/files/src/styles.less.template
  apps/doc/src/app/guidelines/theme/components/examples/custom-theme.md
  libs/components/src/styles/icons-16/icons-16.less
  libs/components/src/styles/icons/icons.less
  libs/components/src/styles/skeleton/skeleton.less
  libs/components/src/styles/styles.less
  libs/theme/src/styles/theme/index.less
Labels: availability:review, state:in_review

#1478 issues from 3.12.0 for 4.1.0
  apps/doc/src/app/components/breadcrumbs/examples/breadcrumbs-projection-basic/breadcrumbs-example-projection.component.less
  apps/doc/src/app/components/calendars/calendar-month/examples/range/range.component.ts
  apps/doc/src/app/components/calendars/calendar/calendar.component.html
  apps/doc/src/app/components/calendars/calendar/calendar.component.ts
  apps/doc/src/app/components/calendars/calendar/examples/base/calendar-base-example.component.ts
  libs/components/src/lib/components/breadcrumbs/breadcrumbs.component.less
  libs/components/src/lib/components/button/button.component.less
  libs/components/src/lib/components/calendar-month/calendar-month.component.html
  libs/components/src/lib/components/calendar-month/calendar-month.component.less
  libs/components/src/lib/components/calendar-month/calendar-month.component.ts
  libs/components/src/lib/components/calendar/calendar.component.html
  libs/components/src/lib/components/calendar/calendar.component.less
  libs/components/src/lib/components/calendar/calendar.component.ts
  libs/components/src/lib/components/checkbox/checkbox.component.less
  libs/components/src/lib/components/chips/chips-item/chips-item.component.less
  libs/components/src/lib/components/file-upload/file-upload.component.less
  libs/components/src/lib/components/input/common/input-icon-button/input-icon-button.component.less
  libs/components/src/lib/components/internal/primitive-calendar-range/primitive-calendar-range.component.html
  libs/components/src/lib/components/internal/primitive-calendar-range/primitive-calendar-range.component.ts
  libs/components/src/lib/components/internal/primitive-calendar/primitive-calendar.component.less
  libs/components/src/lib/components/internal/primitive-month-picker/primitive-month-picker.component.less
  libs/components/src/lib/components/internal/primitive-month-picker/primitive-month-picker.component.ts
  libs/components/src/lib/components/internal/primitive-spin-button/primitive-spin-button.module.ts
  libs/components/src/lib/components/internal/primitive-spin-button/primitive-spin-button.template.html
  libs/components/src/lib/components/internal/primitive-year-picker/primitive-year-picker.component.less
  libs/components/src/lib/components/internal/primitive-year-picker/primitive-year-picker.component.ts
  libs/components/src/lib/components/navigation-menu/components/prizm-navigation-menu-item/prizm-navigation-menu-item.component.less
  libs/components/src/lib/components/radio/prizm-radio-button.component.less
  libs/components/src/lib/components/slider/slider-cnob.component.less
  libs/components/src/lib/components/stepper/stepper-selector.component.less
  libs/components/src/lib/components/toggle/toggle.component.less
  libs/components/src/styles/mixins/picker.less
Labels: state:ready, availability:review, availability:tested

#1459 Fix/calendar markup
  apps/doc/src/app/components/calendars/calendar-month/examples/range/range.component.ts
  apps/doc/src/app/components/calendars/calendar/calendar.component.html
  apps/doc/src/app/components/calendars/calendar/calendar.component.ts
  apps/doc/src/app/components/calendars/calendar/examples/base/calendar-base-example.component.ts
  libs/components/src/lib/components/calendar-month/calendar-month.component.html
  libs/components/src/lib/components/calendar-month/calendar-month.component.less
  libs/components/src/lib/components/calendar-month/calendar-month.component.ts
  libs/components/src/lib/components/calendar/calendar.component.html
  libs/components/src/lib/components/calendar/calendar.component.less
  libs/components/src/lib/components/calendar/calendar.component.ts
  libs/components/src/lib/components/internal/primitive-calendar-range/primitive-calendar-range.component.html
  libs/components/src/lib/components/internal/primitive-calendar-range/primitive-calendar-range.component.ts
  libs/components/src/lib/components/internal/primitive-calendar/primitive-calendar.component.less
  libs/components/src/lib/components/internal/primitive-month-picker/primitive-month-picker.component.less
  libs/components/src/lib/components/internal/primitive-month-picker/primitive-month-picker.component.ts
  libs/components/src/lib/components/internal/primitive-month-picker/primitive-month-picker.module.ts
  libs/components/src/lib/components/internal/primitive-spin-button/primitive-spin-button.module.ts
  libs/components/src/lib/components/internal/primitive-spin-button/primitive-spin-button.template.html
  libs/components/src/lib/components/internal/primitive-year-picker/primitive-year-picker.component.less
  libs/components/src/lib/components/internal/primitive-year-picker/primitive-year-picker.component.ts
  libs/components/src/styles/mixins/picker.less
Labels: state:ready, availability:review, availability:tested

#1427 fix(components/input-date-time-range): afte clear time values in calendar got error #1368
  apps/doc/src/app/components/input/input-layout-date-time-range/input-layout-date-time-range.component.ts
  libs/components/src/lib/@core/date-time/index.ts
  libs/components/src/lib/@core/date-time/time-limit.ts
  libs/components/src/lib/@core/date-time/time.ts
  libs/components/src/lib/components/input/input-date-time-range/input-layout-date-time-range.component.ts
  libs/components/src/lib/components/input/input-date-time/input-layout-date-time.component.ts
Labels: state:ready, availability:review, availability:tested

#1411 fix(chore): stackblitz for v3 #1209
  libs/components/src/styles/icons-16/icons-16.less
  libs/components/src/styles/icons/icons.less
  libs/components/src/styles/skeleton/skeleton.less
  libs/components/src/styles/styles.less
  libs/theme/src/styles/theme/v3/index.less
Labels: state:ready, availability:review, availability:tested

#1406 Feat/focus visible #1297
  apps/doc/src/app/components/breadcrumbs/examples/breadcrumbs-projection-basic/breadcrumbs-example-projection.component.less
  libs/components/src/lib/components/breadcrumbs/breadcrumbs.component.less
  libs/components/src/lib/components/button/button.component.less
  libs/components/src/lib/components/checkbox/checkbox.component.less
  libs/components/src/lib/components/chips/chips-item/chips-item.component.less
  libs/components/src/lib/components/file-upload/file-upload.component.less
  libs/components/src/lib/components/input/common/input-icon-button/input-icon-button.component.less
  libs/components/src/lib/components/radio/prizm-radio-button.component.less
  libs/components/src/lib/components/slider/slider-cnob.component.less
  libs/components/src/lib/components/stepper/stepper-selector.component.less
  libs/components/src/lib/components/toggle/toggle.component.less
Labels: state:ready, availability:review, availability:tested

#1400 fix: hint icon margins added for navigation menu #1329
  libs/components/src/lib/components/navigation-menu/components/prizm-navigation-menu-item/prizm-navigation-menu-item.component.less
Labels: state:ready, availability:review, availability:tested

#1509 feat: release 4.1.0
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/workflows/beta-publish-ng14.yml
  .github/workflows/beta-publish-ng15.yml
  .github/workflows/beta-publish-ng16.yml
  .github/workflows/beta-publish-ng17.yml
  .github/workflows/check-build-in-real-project-ng14.yml
  .github/workflows/check-build-in-real-project-ng15.yml
  .github/workflows/deploy-main-doc-ng14.yml
  .github/workflows/deploy-main-doc-ng15.yml
  .github/workflows/deploy-main-doc-ng16.yml
  .github/workflows/deploy-main-doc-ng17.yml
  .github/workflows/main-publish-ng14.yml
  .github/workflows/main-publish-ng15.yml
  .github/workflows/main-publish-ng16.yml
  .github/workflows/main-publish-ng17.yml
  .github/workflows/pr-ng14.yml
  .github/workflows/pr-ng15.yml
  .github/workflows/pr-ng16.yml
  .github/workflows/pr-ng17.yml
  .github/workflows/pre-release-publish-ng14.yml
  .github/workflows/pre-release-publish-ng15.yml
  .github/workflows/pre-release-publish-ng16.yml
  .github/workflows/pre-release-publish-ng17.yml
  Dockerfile
  apps/doc/src/app/about-prizm/changelog/CHANGELOG.md
  apps/doc/src/app/app.module.ts
  apps/doc/src/app/code-demo/util.ts
  apps/doc/src/app/components/icons/base/examples/all/icons-all-example.component.html
  apps/doc/src/app/components/icons/base/examples/all/icons-all-example.component.less
  apps/doc/src/app/components/icons/base/examples/all/icons-all-example.component.ts
  apps/doc/src/app/components/icons/base/icons.component.html
  apps/doc/src/app/components/icons/base/icons.component.ts
  apps/doc/src/app/components/icons/base/icons.module.ts
  apps/doc/src/app/pages.ts
  apps/doc/src/app/version-manager/current.const.ts
  apps/doc/src/app/version-manager/versions.constants.ts
  libs/ast/package.json
  libs/charts/base/package.json
  libs/components/package.json
  libs/core/package.json
  libs/helpers/package.json
  libs/i18n/package.json
  libs/icons/base/package.json
  libs/icons/base/src/lib/icons/icons.component.ts
  libs/icons/base/src/lib/icons/icons.options.ts
  libs/icons/flags/package.json
  libs/icons/loader/package.json
  libs/nxmv/package.json
  libs/plugin/package.json
  libs/schematics/package.json
  libs/theme/package.json
  package.json
Labels: availability:review, availability:tested

#1514 Fix/active switcher cron
  libs/components/src/lib/components/switcher/switcher.component.html
  libs/components/src/lib/components/switcher/switcher.component.ts
Labels: availability:tested

#1520 fix: switcher in cron returns incorrect value #1519
  libs/components/src/lib/components/switcher/switcher.component.html
  libs/components/src/lib/components/switcher/switcher.component.ts
Labels: state:ready, availability:tested

#1521 feat: release 4.1.1
  .github/workflows/beta-publish-ng17.yml
  .github/workflows/pre-release-publish-ng17.yml
  apps/doc/src/app/about-prizm/changelog/CHANGELOG.md
  apps/doc/src/app/version-manager/current.const.ts
  apps/doc/src/app/version-manager/current.const.ts.ng17
  apps/doc/src/app/version-manager/versions.constants.ts
  libs/ast/package.json
  libs/ast/package.json.ng17
  libs/charts/base/package.json
  libs/charts/base/package.json.ng17
  libs/components/package.json
  libs/components/package.json.ng17
  libs/core/package.json
  libs/core/package.json.ng17
  libs/helpers/package.json
  libs/helpers/package.json.ng17
  libs/i18n/package.json
  libs/i18n/package.json.ng17
  libs/icons/base/package.json
  libs/icons/base/package.json.ng17
  libs/icons/flags/package.json
  libs/icons/flags/package.json.ng17
  libs/icons/loader/package.json
  libs/nxmv/package.json
  libs/nxmv/package.json.ng17
  libs/plugin/package.json
  libs/plugin/package.json.ng17
  libs/schematics/package.json
  libs/schematics/package.json.ng17
  libs/theme/package.json
  libs/theme/package.json.ng17
  package.json
  package.json.ng17
Labels: availability:review, availability:tested
