Repository zyfra/Prizm, pull requests merged in 2024-05, with the labels that each got.

#1609 fix: changed content-box width in toast #1433
  libs/components/src/lib/components/toast/toast/toast.component.less
Labels: state:ready, availability:tested

#1632 feat(chore): improved checker for commit message with our scopes, types, and issues number #1622
  .husky/check_branch_naming.sh
  commitlint.config.js
  package-lock.json
  package-lock.json.ng17
  package.json
  package.json.ng17
Labels: devOnly, availability:test

#1676 feat(chore/commitlint): support slash in scope #000
  commitlint.config.js
Labels: devOnly

#1620 feat: add hint for input clear button #1515
  apps/doc/src/app/components/input/input-carousel/input-carousel-example.component.html
  apps/doc/src/app/components/input/input-carousel/input-carousel-example.component.ts
  apps/doc/src/app/components/input/input-layout-date-range/input-layout-date-range.component.html
  apps/doc/src/app/components/input/input-layout-date-range/input-layout-date-range.component.ts
  apps/doc/src/app/components/input/input-layout-date-relative/input-layout-date-relative.component.html
  apps/doc/src/app/components/input/input-layout-date-relative/input-layout-date-relative.component.ts
  apps/doc/src/app/components/input/input-layout-date-time-range/input-layout-date-time-range.component.html
  apps/doc/src/app/components/input/input-layout-date-time-range/input-layout-date-time-range.component.ts
  apps/doc/src/app/components/input/input-layout-date-time/input-layout-date-time.component.html
  apps/doc/src/app/components/input/input-layout-date-time/input-layout-date-time.component.ts
  apps/doc/src/app/components/input/input-layout-date/input-layout-date.component.html
  apps/doc/src/app/components/input/input-layout-date/input-layout-date.component.ts
  apps/doc/src/app/components/input/input-layout-month-range/input-layout-month-range.component.html
  apps/doc/src/app/components/input/input-layout-month-range/input-layout-month-range.component.ts
  apps/doc/src/app/components/input/input-layout-month/input-layout-month.component.html
  apps/doc/src/app/components/input/input-layout-month/input-layout-month.component.ts
  apps/doc/src/app/components/input/input-layout-time/input-layout-time.component.html
  apps/doc/src/app/components/input/input-layout-time/input-layout-time.component.ts
  apps/doc/src/app/components/input/input-multi-select/input-multi-select.component.html
  apps/doc/src/app/components/input/input-multi-select/input-multi-select.component.ts
  apps/doc/src/app/components/input/input-number/input-number-example.component.html
  apps/doc/src/app/components/input/input-number/input-number-example.component.ts
  apps/doc/src/app/components/input/input-select/input-select.component.html
  apps/doc/src/app/components/input/input-select/input-select.component.ts
  apps/doc/src/app/components/input/input-text/input.component.html
  apps/doc/src/app/components/input/input-text/input.component.ts
  apps/doc/src/app/components/input/textarea/textarea-example.component.html
  apps/doc/src/app/components/input/textarea/textarea-example.component.ts
  libs/components/src/lib/components/input/common/input-common.module.ts
  libs/components/src/lib/components/input/common/input-layout/input-layout.component.html
  libs/components/src/lib/components/input/common/input-layout/input-layout.component.ts
  libs/components/src/lib/tokens/i18n.ts
  libs/i18n/src/lib/interfaces/language.ts
  libs/i18n/src/lib/languages/english/input.ts
  libs/i18n/src/lib/languages/russian/input.ts
Labels: availability:tested

#1635 fix: accordion hint not shown if title changed #1415
  libs/components/src/lib/components/accordion/components/accordion-item/accordion-item.component.html
  libs/components/src/lib/components/accordion/components/accordion-item/accordion-item.component.ts
Labels: availability:tested

#1638 fix: panel instruments cut focus styles #1625
  libs/components/src/lib/components/panel/panel.component.less
Labels: availability:tested

#1615 fix: added scroll to navigation menu #1585
  libs/components/src/lib/components/navigation-menu/components/prizm-navigation-menu-group/prizm-navigation-menu-group.component.less
  libs/components/src/lib/components/navigation-menu/components/prizm-navigation-menu/prizm-navigation-menu.component.html
  libs/components/src/lib/components/navigation-menu/components/prizm-navigation-menu/prizm-navigation-menu.component.less
  libs/components/src/lib/components/navigation-menu/components/prizm-navigation-menu/prizm-navigation-menu.component.ts
  libs/components/src/lib/components/scrollbar/scroll-controls.component.html
  libs/components/src/lib/components/scrollbar/scroll-controls.component.ts
Labels: availability:tested

#1636 feat(doc/paginator): added example with i18n to change texts and tests #1605
  apps/doc/src/app/components/file-upload/examples/i18n/file-upload-i18n-example.component.ts
  apps/doc/src/app/components/paginator/examples/i18n/paginator-i18n-example.component.html
  apps/doc/src/app/components/paginator/examples/i18n/paginator-i18n-example.component.less
  apps/doc/src/app/components/paginator/examples/i18n/paginator-i18n-example.component.spec.ts
  apps/doc/src/app/components/paginator/examples/i18n/paginator-i18n-example.component.ts
  apps/doc/src/app/components/paginator/paginator-example.component.html
  apps/doc/src/app/components/paginator/paginator-example.component.ts
  apps/doc/src/app/components/paginator/paginator-example.module.ts
  libs/components/src/lib/components/paginator/index.ts
  libs/components/src/lib/components/paginator/paginator.component.html
  libs/components/src/lib/components/paginator/paginator.component.less
  libs/components/src/lib/components/paginator/paginator.component.ts
  libs/components/src/lib/components/paginator/paginator.module.ts
  libs/i18n/src/lib/languages/english/index.ts
  libs/i18n/src/lib/languages/russian/index.ts
Labels: availability:tested

#1597 Fix/multi select focus
  apps/doc/src/app/app.routes.ts
  apps/doc/src/app/components/input/input-chips/input-chips-example.component.html
  apps/doc/src/app/components/input/input-chips/input-chips-example.component.ts
  libs/components/src/lib/components/chips/chips-item/chips-item.component.less
  libs/components/src/lib/components/chips/chips.component.less
  libs/components/src/lib/components/dropdowns/multi-select/input-multi-select.component.html
  libs/components/src/lib/components/dropdowns/multi-select/input-multi-select.component.less
  libs/components/src/lib/components/dropdowns/multi-select/input-multi-select.component.ts
  libs/components/src/lib/components/dropdowns/select/input-select.component.html
  libs/components/src/lib/components/dropdowns/select/input-select.component.ts
Labels: availability:tested

#1577 fix: cron translation and switchers #1480 #1494
  apps/doc/src/app/components/cron/examples/specified-tabs/cron-specified-tabs-example.component.ts
  libs/components/src/lib/components/cron/components/day/day.component.html
  libs/components/src/lib/components/cron/components/hour/hour.component.html
  libs/components/src/lib/components/cron/components/hour/hour.component.ts
  libs/components/src/lib/components/cron/components/minute/minute.component.html
  libs/components/src/lib/components/cron/components/minute/minute.component.ts
  libs/components/src/lib/components/cron/components/month/month.component.html
  libs/components/src/lib/components/cron/components/month/month.component.ts
  libs/components/src/lib/components/cron/components/schedule/schedule.component.less
  libs/components/src/lib/components/cron/components/schedule/schedule.component.ts
  libs/components/src/lib/components/cron/components/second/second.component.html
  libs/components/src/lib/components/cron/components/second/second.component.ts
  libs/components/src/lib/components/cron/components/year/year.component.html
  libs/components/src/lib/components/cron/components/year/year.component.ts
  libs/components/src/lib/components/cron/cron.component.less
  libs/components/src/lib/components/cron/cron.component.ts
  libs/i18n/src/lib/interfaces/language.ts
  libs/i18n/src/lib/languages/english/cron.ts
  libs/i18n/src/lib/languages/russian/cron.ts
Labels: state:ready, availability:tested

#1681 fix: add initialization _autoReposition and _placement in input in dropdown#1596
  libs/components/src/lib/components/dropdowns/dropdown-host/dropdown-host.component.ts
Labels: availability:reviewed

#1646 fix(components/input-number): right style on disabled mode #1644 #1645
  apps/doc/src/app/components/input/input-number/examples/disabled-example/input-number-disabled-example.component.html
  apps/doc/src/app/components/input/input-number/examples/disabled-example/input-number-disabled-example.component.less
  apps/doc/src/app/components/input/input-number/examples/disabled-example/input-number-disabled-example.component.spec.ts
  apps/doc/src/app/components/input/input-number/examples/disabled-example/input-number-disabled-example.component.ts
  apps/doc/src/app/components/input/input-number/input-number-example.component.html
  apps/doc/src/app/components/input/input-number/input-number-example.component.ts
  apps/doc/src/app/components/input/input-number/input-number-example.module.ts
  libs/components/src/lib/components/input/common/input-layout/input-layout.component.html
  libs/components/src/lib/components/input/common/input-layout/input-layout.component.ts
  libs/components/src/lib/components/input/input-number/input-number.component.ts
  libs/components/src/lib/components/input/input-number/input-number.module.ts
  libs/components/src/lib/directives/hint/hint.directive.ts
  libs/i18n/src/lib/switch/index.ts
  libs/i18n/src/lib/switch/language.pipe.ts
Labels: availability:tested

#1600 fix: table buttons #1486 #1561
  apps/doc/src/app/components/table/examples/table-basic-example/table-basic-example.component.html
  apps/doc/src/app/components/table/examples/table-dynamic-row-group-example/table-dynamic-row-group-example.component.html
  apps/doc/src/app/components/table/examples/table-editable-row-example/table-editable-row-example.component.html
  apps/doc/src/app/components/table/examples/table-editable-row-example/table-editable-row-example.component.less
  apps/doc/src/app/components/table/examples/table-filter-example/table-filter-example.component.html
  apps/doc/src/app/components/table/examples/table-filter-example/table-filter-example.component.less
  apps/doc/src/app/components/table/examples/table-sort-example/table-sort-example.component.html
  apps/doc/src/app/components/table/examples/table-sort-example/table-sort-example.component.ts
  apps/doc/src/app/components/table/examples/table-track-by-example/table-track-by-example.component.less
  apps/doc/src/app/components/table/table-example.component.html
  apps/doc/src/app/components/table/table-example.component.ts
  libs/components/src/lib/components/table/directives/table.directive.ts
  libs/components/src/lib/components/table/table.module.ts
  libs/components/src/lib/components/table/tbody/tbody.component.html
  libs/components/src/lib/components/table/tbody/tbody.component.less
  libs/components/src/lib/components/table/td/td.component.less
  libs/components/src/lib/components/table/th/th.component.html
  libs/components/src/lib/components/table/th/th.component.ts
  libs/components/src/lib/components/table/th/th.style.less
  libs/components/src/lib/components/table/tr/tr.component.less
  libs/components/src/lib/components/tree-button/tree-button.component.less
Labels: availability:tested

#1616 feat: use decimal input in slider and input number live demo #1500
  apps/doc/src/app/components/input/input-number/input-number-example.component.html
  apps/doc/src/app/components/slider/slider.component.html
  apps/doc/src/app/components/slider/slider.component.ts
Labels: availability:tested

#1686 fix(components/hint): switcher extra empty hint shown #1682
  libs/components/src/lib/components/input/common/input-layout/input-layout.component.html
  libs/components/src/lib/directives/hint/hint.directive.ts
Labels: state:ready, availability:tested

#1606 fix: table buttons #1486 #1561
  apps/doc/src/app/components/table/examples/table-dynamic-row-group-example/table-dynamic-row-group-example.component.html
  apps/doc/src/app/components/table/examples/table-editable-row-example/table-editable-row-example.component.html
  apps/doc/src/app/components/table/examples/table-editable-row-example/table-editable-row-example.component.less
  apps/doc/src/app/components/table/examples/table-filter-example/table-filter-example.component.html
  apps/doc/src/app/components/table/examples/table-filter-example/table-filter-example.component.less
  apps/doc/src/app/components/table/examples/table-sort-example/table-sort-example.component.html
  apps/doc/src/app/components/table/examples/table-sort-example/table-sort-example.component.ts
  apps/doc/src/app/components/table/examples/table-track-by-example/table-track-by-example.component.less
  apps/doc/src/app/components/table/table-example.component.html
  apps/doc/src/app/components/table/table-example.component.ts
  libs/components/src/lib/components/table/table.module.ts
  libs/components/src/lib/components/table/tbody/tbody.component.less
  libs/components/src/lib/components/table/th/th.component.html
  libs/components/src/lib/components/table/th/th.style.less
  libs/components/src/lib/components/table/tr/tr.component.less
  libs/components/src/lib/components/tree-button/tree-button.component.less
Labels: state:ready, availability:tested

#1614 fix: added scroll to navigation menu #1585
  libs/components/src/lib/components/navigation-menu/components/prizm-navigation-menu-group/prizm-navigation-menu-group.component.less
  libs/components/src/lib/components/navigation-menu/components/prizm-navigation-menu/prizm-navigation-menu.component.html
  libs/components/src/lib/components/navigation-menu/components/prizm-navigation-menu/prizm-navigation-menu.component.less
  libs/components/src/lib/components/navigation-menu/components/prizm-navigation-menu/prizm-navigation-menu.component.ts
  libs/components/src/lib/components/scrollbar/scroll-controls.component.html
  libs/components/src/lib/components/scrollbar/scroll-controls.component.ts
Labels: state:ready, availability:tested

#1608 fix: changed content-box width in toast #1433
  libs/components/src/lib/components/toast/toast/toast.component.less
Labels: state:ready, availability:tested

#1695 fix(doc/dialog): add dismissable prop to live demo #1551
  apps/doc/src/app/components/dialogs/dialog/dialog-example.component.html
  apps/doc/src/app/components/dialogs/dialog/dialog-example.component.ts
Labels: availability:tested

#1696 Fix/demo dialog v3
  apps/doc/src/app/components/dialogs/dialog/dialog-example.component.html
  apps/doc/src/app/components/dialogs/dialog/dialog-example.component.ts
Labels: availability:tested

#1703 fix(icons/icons-full): added skipped provider for PrizmDestroyService #1652
  libs/icons/base/src/lib/icons/icons-full.component.ts
Labels: state:ready, devOnly, availability:reviewed

#1702 feat(doc/dialog): add examples how to use custom dialog #1602
  apps/doc/src/app/components/dialogs/dialog/dialog-example.component.html
  apps/doc/src/app/components/dialogs/dialog/dialog-example.component.ts
  apps/doc/src/app/components/dialogs/dialog/dialog-example.module.ts
  apps/doc/src/app/components/dialogs/dialog/examples/custom-service/dialog-custom-service-example.component.html
  apps/doc/src/app/components/dialogs/dialog/examples/custom-service/dialog-custom-service-example.component.ts
  apps/doc/src/app/components/dialogs/dialog/examples/custom-service/my-custom-service.ts
  libs/components/src/lib/abstract/dialog.service.ts
  libs/components/src/lib/components/dialogs/dialog/dialog.service.ts
Labels: availability:tested

#1705 feature(components/tooltip): tooltip close on click in showed dropdown #1704
  libs/components/src/lib/directives/tooltip/tooltip.directive.ts
Labels: availability:tested

#1711 #1710 #1704
  apps/doc/src/app/components/tooltip/tooltip-example.component.html
  libs/components/src/lib/directives/confirm-popup/confirm-popup.directive.ts
  libs/components/src/lib/directives/hint/hint.directive.ts
  libs/components/src/lib/directives/tooltip/tooltip.directive.ts
  libs/doc/base/src/lib/components/host/host-element.service.ts
  libs/helpers/src/lib/util/index.ts
  libs/helpers/src/lib/util/invert-object.spec.ts
  libs/helpers/src/lib/util/invert-object.ts
Labels: availability:tested

#1716 feat(doc/icons): added info about enum name to copied values #1648
  apps/doc/src/app/components/icons/base/all/all-icon.component.ts
Labels: availability:tested

#1722 fix(components/cron): slowly switcher in cron #000
  libs/components/src/lib/components/cron/cron.component.ts
  libs/i18n/src/lib/languages/russian/cron.ts
Labels: availability:tested

#1724 fix(components/cron): slowly switcher in cron #000
  libs/components/src/lib/components/cron/cron.component.ts
Labels: availability:tested

#1700 feat(chore): release 4.3.0 #000
  .github/workflows/beta-publish-ng17.yml
  .github/workflows/main-publish-ng17.yml
  .github/workflows/pre-release-publish-ng17.yml
  apps/doc/src/app/about-prizm/changelog/CHANGELOG.md
  apps/doc/src/app/version-manager/current.const.ts
  apps/doc/src/app/version-manager/current.const.ts.ng17
  apps/doc/src/app/version-manager/versions.constants.ts
  libs/ast/package.json
  libs/ast/package.json.ng17
  libs/charts/base/package.json
  libs/charts/base/package.json.ng17
  libs/components/package.json
  libs/components/package.json.ng17
  libs/components/src/lib/components/cron/cron.component.html
  libs/components/src/lib/components/cron/cron.component.ts
  libs/core/package.json
  libs/core/package.json.ng17
  libs/helpers/package.json
  libs/helpers/package.json.ng17
  libs/i18n/package.json
  libs/i18n/package.json.ng17
  libs/icons/base/package.json
  libs/icons/base/package.json.ng17
  libs/icons/flags/package.json
  libs/icons/flags/package.json.ng17
  libs/icons/loader/package.json
  libs/nxmv/package.json
  libs/nxmv/package.json.ng17
  libs/plugin/package.json
  libs/plugin/package.json.ng17
  libs/schematics/package.json
  libs/schematics/package.json.ng17
  libs/theme/package.json
  libs/theme/package.json.ng17
  package.json
  package.json.ng17
Labels: availability:reviewed

#1697 feat: release 3.13.1
  .github/workflows/beta-publish-ng14.yml
  .github/workflows/beta-publish-ng15.yml
  .github/workflows/beta-publish-ng16.yml
  .github/workflows/main-publish-ng14.yml
  .github/workflows/main-publish-ng15.yml
  .github/workflows/main-publish-ng16.yml
  .github/workflows/pre-release-publish-ng14.yml
  .github/workflows/pre-release-publish-ng15.yml
  .github/workflows/pre-release-publish-ng16.yml
  apps/doc/src/app/about-prizm/changelog/CHANGELOG.md
  apps/doc/src/app/version-manager/current.const.ts.ng14
  apps/doc/src/app/version-manager/current.const.ts.ng15
  apps/doc/src/app/version-manager/current.const.ts.ng16
  apps/doc/src/app/version-manager/versions.constants.ts
  libs/ast/package.json.ng14
  libs/ast/package.json.ng15
  libs/ast/package.json.ng16
  libs/charts/base/package.json.ng14
  libs/charts/base/package.json.ng15
  libs/charts/base/package.json.ng16
  libs/components/package.json.ng14
  libs/components/package.json.ng15
  libs/components/package.json.ng16
  libs/components/src/lib/components/cron/cron.component.ts
  libs/core/package.json.ng14
  libs/core/package.json.ng15
  libs/core/package.json.ng16
  libs/helpers/package.json.ng14
  libs/helpers/package.json.ng15
  libs/helpers/package.json.ng16
  libs/i18n/package.json.ng14
  libs/i18n/package.json.ng15
  libs/i18n/package.json.ng16
  libs/icons/base/package.json.ng14
  libs/icons/base/package.json.ng15
  libs/icons/base/package.json.ng16
  libs/icons/flags/package.json.ng14
  libs/icons/flags/package.json.ng15
  libs/icons/flags/package.json.ng16
  libs/nxmv/package.json.ng14
  libs/nxmv/package.json.ng15
  libs/nxmv/package.json.ng16
  libs/plugin/package.json.ng14
  libs/plugin/package.json.ng15
  libs/plugin/package.json.ng16
  libs/schematics/package.json.ng14
  libs/schematics/package.json.ng15
  libs/schematics/package.json.ng16
  libs/theme/package.json.ng14
  libs/theme/package.json.ng15
  libs/theme/package.json.ng16
  package.json.ng14
  package.json.ng15
  package.json.ng16
Labels: availability:tested

#1740 fix(doc/icons): added info about lazy loader #1692
  apps/doc/src/app/components/icons/base/examples/setup-module.md
  apps/doc/src/app/how-to-work/for-developers/for-developers.component.html
Labels: state:ready, availability:tested

#1738 fix(components/chips): dots overflows chip list container #1713
  apps/doc/src/app/components/input/input-multi-select/examples/base/multi-select-base-example.component.ts
  libs/components/src/lib/components/chips/chips.component.html
  libs/components/src/lib/components/chips/chips.component.less
  libs/components/src/lib/components/dropdowns/multi-select/input-multi-select.component.less
  libs/components/src/lib/components/dropdowns/select/input-select.component.less
Labels: state:ready, availability:tested

#1736 fix(components/dialog): some values from `defaultOptions` not applied to final config #1602
  libs/components/src/lib/abstract/dialog.service.ts
Labels: state:ready, availability:tested

#1715 fix(components/input-layout): add margin bottom for label in outer inputs #1659
  libs/components/src/lib/components/input/common/input-layout/input-layout-hidden-control.component.less
  libs/components/src/lib/components/input/common/input-layout/input-layout.component.less
Labels: state:ready, availability:tested

#1708 fix(components/chips): deletable chips xmark font icon reblaced by ba…se icon #1698
  libs/components/src/lib/components/chips/chips-item/chips-item.component.html
  libs/components/src/lib/components/chips/chips-item/chips-item.component.ts
Labels: state:ready, availability:tested

#1750 fix(components/input-date-range): default time is set only after focus is removed for V4 #1565
  libs/components/src/lib/components/input/input-date-time-range/input-layout-date-time-range.component.ts
Labels: availability:tested, version:4

#1745 fix(components/paginator): fixed `PrizmPaginatorComponent` instance was incompatible with `PrizmDataSource.paginator`
  apps/doc/src/app/components/table/examples/table-data-source-example/table-data-source-example.component.ts
  libs/components/src/lib/components/table/data-source.ts
Labels: devOnly, availability:reviewed, version:4

#1752 Fix/datasource incompatible with paginator v3
  apps/doc/src/app/components/table/examples/table-data-source-example/table-data-source-example.component.ts
  libs/components/src/lib/components/table/data-source.ts
Labels: state:ready, devOnly, availability:reviewed, version:3

#1748 fix(components/input-number): fix sync state with input-layout FOR V3 #1645 #1644
  libs/components/src/lib/components/input/input-number/input-number.component.ts
Labels: state:ready, availability:tested, version:3

#1717 fix(components/input-layout): add margin bottom for label in outer in…
  libs/components/src/lib/components/input/common/input-layout/input-layout-hidden-control.component.less
  libs/components/src/lib/components/input/common/input-layout/input-layout.component.less
Labels: state:ready, availability:tested, version:3

#1739 fix(components/chips): dots overflows chip list container #1713 v3
  apps/doc/src/app/components/input/input-multi-select/examples/base/multi-select-base-example.component.ts
  libs/components/src/lib/components/chips/chips.component.html
  libs/components/src/lib/components/chips/chips.component.less
Labels: state:ready, availability:tested, version:3

#1749 fix(components/input-date-range): default time is set only after focus is removed in V3 #1565
  libs/components/src/lib/components/input/input-date-time-range/input-layout-date-time-range.component.ts
Labels: state:ready, availability:tested, version:3

#1721 fix(components/calendar): change calendar resrtictions ux #1674
  apps/doc/src/app/components/input/input-layout-date-range/examples/base/input-layout-date-range-base-example.component.ts
  libs/components/src/lib/components/calendar/calendar.component.ts
  libs/components/src/lib/components/internal/primitive-month-picker/primitive-month-picker.component.ts
  libs/components/src/lib/components/internal/primitive-year-month-pagination/primitive-year-month-pagination.component.html
  libs/components/src/lib/components/internal/primitive-year-picker/primitive-year-picker.component.ts
  libs/components/src/styles/mixins/mixins.less
Labels: state:ready, availability:tested, version:4
