Repository zyfra/Prizm, pull requests merged in 2024-02, with the labels that each got.

#1347 feat(chore): created new executor for generate fonts
  libs/icons/base/project.json
  libs/icons/base/src/styles/icons-base/prizmIconsBase.css
  libs/icons/base/src/styles/icons-base/prizmIconsBase.eot
  libs/icons/base/src/styles/icons-base/prizmIconsBase.less
  libs/icons/base/src/styles/icons-base/prizmIconsBase.module.less
  libs/icons/base/src/styles/icons-base/prizmIconsBase.scss
  libs/icons/base/src/styles/icons-base/prizmIconsBase.styl
  libs/icons/base/src/styles/icons-base/prizmIconsBase.svg
  libs/icons/base/src/styles/icons-base/prizmIconsBase.symbol.svg
  libs/icons/base/src/styles/icons-base/prizmIconsBase.ttf
  libs/icons/base/src/styles/icons-base/prizmIconsBase.woff
  libs/icons/base/src/styles/icons-base/prizmIconsBase.woff2
  libs/icons/base/src/styles/icons-full/prizmIconsFull.css
  libs/icons/base/src/styles/icons-full/prizmIconsFull.eot
  libs/icons/base/src/styles/icons-full/prizmIconsFull.less
  libs/icons/base/src/styles/icons-full/prizmIconsFull.module.less
  libs/icons/base/src/styles/icons-full/prizmIconsFull.scss
  libs/icons/base/src/styles/icons-full/prizmIconsFull.styl
  libs/icons/base/src/styles/icons-full/prizmIconsFull.svg
  libs/icons/base/src/styles/icons-full/prizmIconsFull.symbol.svg
  libs/icons/base/src/styles/icons-full/prizmIconsFull.ttf
  libs/icons/base/src/styles/icons-full/prizmIconsFull.woff
  libs/icons/base/src/styles/icons-full/prizmIconsFull.woff2
  local/executors.json
  local/src/executors/svg-to-font/executor.ts
  local/src/executors/svg-to-font/schema.d.ts
  local/src/executors/svg-to-font/schema.json
  package-lock.json
  package-lock.json.ng17
  package.json
  package.json.ng17
Labels: ready, devOnly

#1332 fix: search label for input select and input multiselect added #1323
  libs/components/src/lib/components/dropdowns/multi-select/input-multi-select.component.html
  libs/components/src/lib/components/dropdowns/multi-select/input-multi-select.component.ts
  libs/components/src/lib/components/dropdowns/select/input-select.component.html
  libs/components/src/lib/components/dropdowns/select/input-select.component.ts
  libs/components/src/lib/tokens/i18n.ts
  libs/i18n/src/lib/interfaces/language.ts
  libs/i18n/src/lib/languages/russian/kit.ts
Labels: state:ready, availability:review, availability:tested

#1334 fix: extra title in input select #1286
  apps/doc/src/app/components/input/input-select/examples/base/select-base-example.component.html
  libs/components/src/lib/components/dropdowns/select/input-select.component.html
Labels: state:ready, availability:review, availability:tested

#1351 fix: switcher active disable state regression fixed #1348
  libs/components/src/lib/components/switcher/components/switcher-item/switcher-item.component.html
  libs/components/src/lib/components/switcher/components/switcher-item/switcher-item.component.less
  libs/components/src/lib/components/switcher/components/switcher-item/switcher-item.component.ts
Labels: state:ready, availability:review, availability:tested

#1353 fix: prizm navigation menu search error #1344
  apps/doc/src/app/components/navigation-menu/examples/navigation-menu-basic-example/navigation-menu-basic-example.component.html
  apps/doc/src/app/components/navigation-menu/examples/navigation-menu-basic-example/navigation-menu-basic-example.component.ts
  libs/components/src/lib/components/navigation-menu/components/prizm-navigation-menu-item/prizm-navigation-menu-item.component.html
  libs/components/src/lib/components/navigation-menu/components/prizm-navigation-menu-item/prizm-navigation-menu-item.component.less
  libs/components/src/lib/components/navigation-menu/components/prizm-navigation-menu-item/prizm-navigation-menu-item.component.ts
  libs/components/src/lib/components/navigation-menu/components/prizm-navigation-menu-items/prizm-navigation-menu-items.component.html
  libs/components/src/lib/components/navigation-menu/components/prizm-navigation-menu-items/prizm-navigation-menu-items.component.ts
  libs/components/src/lib/components/navigation-menu/components/prizm-navigation-menu/prizm-navigation-menu.component.ts
  libs/components/src/lib/components/navigation-menu/services/prizm-navigation-menu-group.service.ts
Labels: state:ready, availability:review, availability:tested

#1359 fix: breadcrumbs force update for content projection usage #1282
  apps/doc/src/app/components/breadcrumbs/examples/breadcrumbs-projection-basic/breadcrumbs-example-projection.component.html
  apps/doc/src/app/components/breadcrumbs/examples/breadcrumbs-projection-basic/breadcrumbs-example-projection.component.ts
  libs/components/src/lib/components/breadcrumbs/breadcrumbs.component.ts
Labels: state:ready, availability:review, availability:tested

#1361 fix: input height fixes #1179, #1308
  apps/doc/src/app/components/input/input-chips/input-chips-example.component.less
  apps/doc/src/app/components/input/input-text/input-example.module.ts
  libs/components/src/lib/components/input/carousel/input-carousel-auxiliary-left.component.ts
  libs/components/src/lib/components/input/carousel/input-carousel-auxiliary-right.component.ts
  libs/components/src/lib/components/input/common/input-icon-button/input-icon-button.component.less
  libs/components/src/lib/components/input/common/input-layout/input-layout.component.less
  libs/components/src/lib/components/input/input-number/input-number-auxiliary-controls.component.less
Labels: state:ready, availability:review, availability:tested

#1369 fix: date time range transformer token error #1364
  libs/components/src/lib/components/input/input-date-time-range/input-layout-date-time-range.component.ts
Labels: state:ready, devOnly, availability:review, availability:tested

#1377 fix(components/tabs): issue with close tabs logic #1360
  libs/components/src/lib/components/tabs/components/tab.component.ts
  libs/components/src/lib/components/tabs/components/tabs.component.spec.ts
  libs/components/src/lib/components/tabs/tabs.component.html
  libs/components/src/lib/components/tabs/tabs.service.ts
Labels: state:ready, availability:review, availability:tested

#1381 chore: update changelog for 3.11.1
  apps/doc/src/app/about-prizm/changelog/CHANGELOG.md
Labels: state:ready, availability:review, availability:tested

#1340 fix: dropdown select panel example fix #1283
  apps/doc/src/app/components/dropdowns/dropdown-host/dropdown-host.module.ts
  apps/doc/src/app/components/dropdowns/dropdown-host/examples/select-panel-example/select-panel-example.component.html
  apps/doc/src/app/components/dropdowns/dropdown-host/examples/select-panel-example/select-panel-example.component.less
Labels: availability:review, availability:tested

#1391 fix(components/paginator): updated i18n #1390
  libs/components/src/lib/components/paginator/prizm-paginator.component.html
  libs/i18n/src/lib/interfaces/language.ts
  libs/i18n/src/lib/languages/russian/paginator.ts
Labels: availability:review, availability:tested

#1333 fix: search label for input select and input multiselect added #1323 for 4.0, breaking
  libs/components/src/lib/components/dropdowns/multi-select/input-multi-select.component.html
  libs/components/src/lib/components/dropdowns/multi-select/input-multi-select.component.ts
  libs/components/src/lib/components/dropdowns/select/input-select.component.html
  libs/components/src/lib/components/dropdowns/select/input-select.component.ts
  libs/components/src/lib/tokens/i18n.ts
  libs/i18n/src/lib/interfaces/language.ts
  libs/i18n/src/lib/languages/english/kit.ts
  libs/i18n/src/lib/languages/russian/kit.ts
Labels: type:bc, availability:review, availability:tested

#1363 feat: label text removed from select and multiselect default options // breaking change
  libs/components/src/lib/components/dropdowns/multi-select/multi-select.options.ts
  libs/components/src/lib/components/dropdowns/select/select.options.ts
Labels: type:bc, availability:review, availability:tested

#1342 fix: panel styles changed #787
  apps/doc/src/app/components/panel/examples/panel-example-with-breadcrumbs/panel-example-with-breadcrumbs.component.less
  apps/doc/src/app/components/panel/examples/panel-example-with-instruments-hard/panel-example-with-instruments-hard.component.less
  apps/doc/src/app/components/panel/examples/panel-example-with-instruments-simple/panel-example-with-instruments-simple.component.less
  apps/doc/src/app/components/panel/panel-example.component.html
  apps/doc/src/app/components/panel/panel-example.component.ts
  libs/components/src/lib/components/panel/panel.component.less
Labels: type:bc, availability:review, availability:tested
