Repository zyfra/Prizm, pull requests merged in 2024-11, with the labels that each got.

#2153 release 5.2.0
  .github/PULL_REQUEST_TEMPLATE/prepare_release_for_5.md
  apps/doc/src/app/about-prizm/changelog/CHANGELOG.md
  apps/doc/src/app/components/buttons/button/button.component.html
  apps/doc/src/app/components/buttons/button/button.component.ts
  apps/doc/src/app/components/buttons/icon-button/icon-button.component.html
  apps/doc/src/app/components/buttons/icon-button/icon-button.component.ts
  apps/doc/src/app/components/dropdowns/dropdown-host/dropdown-host.component.html
  apps/doc/src/app/components/dropdowns/dropdown-host/dropdown-host.component.ts
  apps/doc/src/app/components/input/input-tree-multi-select/input-tree-multi-select.component.ts
  apps/doc/src/app/components/input/input-tree-select/input-tree-select.component.html
  apps/doc/src/app/components/slider/slider.component.html
  apps/doc/src/app/tools/polymorph/polymorph.component.html
  apps/doc/src/app/version-manager/current.const.ts
  apps/doc/src/app/version-manager/versions.constants.ts
  apps/doc/src/app/version-manager/versions.constants.ts.ng17
  apps/doc/src/app/version-manager/versions.constants.ts.ng18
  libs/ast/package.json
  libs/charts/base/package.json
  libs/components/package.json
  libs/components/src/lib/components/checkbox/checkbox.component.ts
  libs/components/src/lib/components/chips/chips-item/chips-item.component.less
  libs/components/src/lib/components/chips/chips-item/chips-item.component.ts
  libs/components/src/lib/components/chips/chips.component.less
  libs/components/src/lib/components/dropdowns/dropdown-host/dropdown-host-trigger-click.directive.ts
  libs/components/src/lib/components/dropdowns/multi-select/input-multi-select.component.html
  libs/components/src/lib/components/dropdowns/multi-select/input-multi-select.component.ts
  libs/components/src/lib/components/dropdowns/select/input-select.component.less
  libs/components/src/lib/components/dropdowns/tree-multi-select/item/tree-multi-select-item.component.html
  libs/components/src/lib/components/dropdowns/tree-multi-select/item/tree-multi-select-item.component.less
  libs/components/src/lib/components/dropdowns/tree-multi-select/tree-multi-select.component.html
  libs/components/src/lib/components/dropdowns/tree-multi-select/tree-multi-select.component.ts
  libs/components/src/lib/components/dropdowns/tree-select/tree-select.component.html
  libs/components/src/lib/components/dropdowns/tree-select/tree-select.component.less
  libs/components/src/lib/components/dropdowns/tree-select/tree-select.component.ts
  libs/components/src/lib/components/input/carousel/input-carousel.component.ts
  libs/components/src/lib/components/input/common/input-layout/input-layout.component.less
  libs/components/src/lib/directives/polymorph/directives/outlet.old.ts
  libs/components/src/lib/directives/polymorph/directives/outlet.ts
  libs/core/package.json
  libs/helpers/package.json
  libs/helpers/src/lib/directives/overflow/overflow.service.ts
  libs/i18n/package.json
  libs/icons/base/package.json
  libs/icons/flags/package.json
  libs/icons/loader/package.json
  libs/nxmv/package.json
  libs/plugin/package.json
  libs/schematics/package.json
  libs/schematics/src/ng-add/consts.ts
  libs/theme/package.json
  local/package.json
  package-lock.json
  package-lock.json.ng17
  package-lock.json.ng18
  package.json
Labels: availability:reviewed, availability:review, availability:tested

#2045 feat(components/query-builder): query builder component #402
  apps/doc/src/app/app.routes.ts
  apps/doc/src/app/components/query-builder/examples/query-builder-basic-example/query-builder-basic-example.component.html
  apps/doc/src/app/components/query-builder/examples/query-builder-basic-example/query-builder-basic-example.component.less
  apps/doc/src/app/components/query-builder/examples/query-builder-basic-example/query-builder-basic-example.component.ts
  apps/doc/src/app/components/query-builder/examples/query-builder-scrollable-example/query-builder-scrollable-example.component.html
  apps/doc/src/app/components/query-builder/examples/query-builder-scrollable-example/query-builder-scrollable-example.component.less
  apps/doc/src/app/components/query-builder/examples/query-builder-scrollable-example/query-builder-scrollable-example.component.ts
  apps/doc/src/app/components/query-builder/examples/setup-module.md
  apps/doc/src/app/components/query-builder/query-builder-example.component.html
  apps/doc/src/app/components/query-builder/query-builder-example.component.ts
  apps/doc/src/app/components/query-builder/query-builder-example.constants.ts
  apps/doc/src/app/components/query-builder/query-builder-example.module.ts
  apps/doc/src/app/pages.ts
  libs/components/src/lib/components/button/button.component.html
  libs/components/src/lib/components/button/button.component.less
  libs/components/src/lib/components/index.ts
  libs/components/src/lib/components/query-builder/condition-def.directive.ts
  libs/components/src/lib/components/query-builder/index.ts
  libs/components/src/lib/components/query-builder/model.ts
  libs/components/src/lib/components/query-builder/query-builder.component.html
  libs/components/src/lib/components/query-builder/query-builder.component.less
  libs/components/src/lib/components/query-builder/query-builder.component.ts
  libs/components/src/lib/components/query-builder/query-builder.module.ts
  libs/components/src/lib/components/query-builder/services/PrizmQueryBuilderDragDrop.ts
  libs/components/src/lib/components/query-builder/services/PrizmQueryBuilderDropListRef.ts
  libs/components/src/lib/components/toggle/toggle.component.less
  libs/components/src/lib/directives/wrapper/wrapper.component.less
  libs/components/src/lib/tokens/i18n.ts
  libs/i18n/src/lib/interfaces/language.ts
  libs/i18n/src/lib/languages/english/english.ts
  libs/i18n/src/lib/languages/english/query-builder.ts
  libs/i18n/src/lib/languages/russian/query-builder.ts
  libs/i18n/src/lib/languages/russian/russian.ts
  package-lock.json
Labels: source:idp, availability:reviewed, availability:tested, version:5

#2079 fix(components/input): added CD on `empty` prop change #2078
  apps/doc/src/app/components/input/input-carousel/examples/input-as-carousel/input-as-carousel.component.html
  apps/doc/src/app/components/input/input-mask/input-mask-example.component.html
  apps/doc/src/app/components/input/input-text/examples/input-form-control-example/input-form-control-example.component.ts
  libs/components/src/lib/@core/date-time/day-range.ts
  libs/components/src/lib/components/input/input-text/input-text.component.ts
  libs/helpers/src/lib/pipes/to-observable/to-observable.pipe.ts
Labels: availability:reviewed, availability:tested

#2151 fix(components/button): fixed problem with confused test id for buttons with and without icons #2150
  libs/components/src/lib/components/button/button.component.ts
Labels: availability:reviewed, availability:tested, version:5

#2157 feat(components/navigation): add expanded items support #1838
  apps/doc/src/app/components/navigation/examples/navigation-basic-example/navigation-basic-example.component.html
  apps/doc/src/app/components/navigation/examples/navigation-basic-example/navigation-basic-example.component.ts
  apps/doc/src/app/components/navigation/navigation-example.component.html
  apps/doc/src/app/components/navigation/navigation-example.const.ts
  libs/components/src/lib/components/navigation/components/prizm-navigation-item-expandable/prizm-navigation-item-expandable.component.html
  libs/components/src/lib/components/navigation/components/prizm-navigation-item-expandable/prizm-navigation-item-expandable.component.spec.ts
  libs/components/src/lib/components/navigation/components/prizm-navigation-item-expandable/prizm-navigation-item-expandable.component.ts
  libs/components/src/lib/components/navigation/components/prizm-navigation-item-simple/prizm-navigation-item-simple.component.html
  libs/components/src/lib/components/navigation/components/prizm-navigation-item-simple/prizm-navigation-item-simple.component.less
  libs/components/src/lib/components/navigation/pipes/calculate-margin.pipe.ts
  libs/components/src/lib/components/navigation/prizm-navigation.component.html
  libs/components/src/lib/components/navigation/prizm-navigation.component.spec.ts
  libs/components/src/lib/components/navigation/prizm-navigation.component.ts
  libs/components/src/lib/components/navigation/prizm-navigation.module.ts
  libs/components/src/lib/components/navigation/services/expanded-navigation.service.ts
Labels: availability:reviewed, availability:tested

#2179 refactor(components/abstract): remove not used abstract classes
  libs/components/src/lib/abstract/abstract-textfield-host.ts
  libs/components/src/lib/abstract/nullable-control.ts
Labels: devOnly, availability:reviewed, availability:tested

#2175 fix(components/file-upload): empty array input should be supported for input files #2174
  libs/components/src/lib/components/file-upload/file-upload.component.ts
Labels: availability:reviewed, availability:tested, version:5

#2173 fix(doc/menu): update nxvm menu item title source from english version menu #2053
  apps/doc/src/app/pages.ts
Labels: availability:reviewed, availability:tested

#2170 fix(components/dialog): limit dialog header with 1 line of text only #755
  apps/doc/src/app/components/dialogs/confirm-dialog/confirm.component.html
  apps/doc/src/app/components/dialogs/dialog/dialog-example.component.html
  apps/doc/src/app/components/dialogs/sidebar/sidebar.component.html
  apps/doc/src/styles.less
  libs/components/src/lib/components/dialogs/confirm-dialog/confirm-dialog.component.html
  libs/components/src/lib/components/dialogs/confirm-dialog/confirm-dialog.component.less
  libs/components/src/lib/components/dialogs/confirm-dialog/confirm-dialog.component.ts
  libs/components/src/lib/components/dialogs/dialog/dialog.component.html
  libs/components/src/lib/components/dialogs/dialog/dialog.component.less
  libs/components/src/lib/components/dialogs/dialog/dialog.component.ts
  libs/components/src/lib/components/dialogs/sidebar/sidebar.component.html
  libs/components/src/lib/components/dialogs/sidebar/sidebar.component.less
  libs/components/src/lib/components/dialogs/sidebar/sidebar.component.ts
  libs/components/src/lib/components/widget/widget.component.less
  libs/components/src/lib/util/dom/is-textoverflow.ts
Labels: availability:reviewed, availability:tested, version:5

#2167 feat(doc/dialog): remove extra properties in live demo #653
  apps/doc/src/app/components/dialogs/dialog/dialog-example.component.html
  apps/doc/src/app/components/dialogs/dialog/dialog-example.component.ts
  apps/doc/src/app/components/input/input-chips/input-chips-example.component.html
  apps/doc/src/app/components/input/input-chips/input-chips-example.component.ts
  apps/doc/src/app/components/input/input-mask/input-mask-example.component.html
  apps/doc/src/app/components/input/input-mask/input-mask-example.component.ts
  apps/doc/src/app/components/input/input-password/input-password-example.component.html
  apps/doc/src/app/components/input/input-password/input-password-example.component.ts
Labels: availability:reviewed, availability:tested, version:5

#2164 refactor(components/accrodion): replace native resize observer by hintOnOverflow directive #1414
  apps/doc/src/app/components/navigation/navigation-example.component.ts
  libs/components/src/lib/components/accordion/components/accordion-item/accordion-item.component.html
  libs/components/src/lib/components/accordion/components/accordion-item/accordion-item.component.spec.ts
  libs/components/src/lib/components/accordion/components/accordion-item/accordion-item.component.ts
  libs/components/src/lib/components/navigation-menu/components/prizm-navigation-menu-item/prizm-navigation-menu-item.component.html
  libs/components/src/lib/components/navigation/components/prizm-navigation-item-expandable/prizm-navigation-item-expandable.component.html
  libs/components/src/lib/components/navigation/components/prizm-navigation-item-expandable/prizm-navigation-item-expandable.component.spec.ts
  libs/components/src/lib/components/navigation/components/prizm-navigation-item-expandable/prizm-navigation-item-expandable.component.ts
  libs/components/src/lib/components/navigation/components/prizm-navigation-item-simple/prizm-navigation-item-simple.component.html
  libs/components/src/lib/components/navigation/components/prizm-navigation-item-simple/prizm-navigation-item-simple.component.spec.ts
  libs/components/src/lib/components/navigation/components/prizm-navigation-item-simple/prizm-navigation-item-simple.component.ts
  libs/components/src/lib/components/navigation/prizm-navigation.module.ts
Labels: availability:reviewed, availability:review, availability:tested

#2191 fix(components/panel): fix incorrect css variable name for subheader color #2186
  apps/doc/src/app/components/progress/line-segmented/examples/base/progress-base-example.component.ts
  libs/components/src/lib/components/panel/panel.component.less
Labels: availability:review, availability:tested

#2067 fix(components/input-date-time-range): native date transformer providing #2059
  apps/doc/src/app/components/input/input-layout-date-time-range/examples/native-date/input-native-date-time-range-base-example.component.html
  apps/doc/src/app/components/input/input-layout-date-time-range/input-layout-date-time-range.component.html
  libs/components/src/lib/@core/date-time/day-time-range.ts
  libs/components/src/lib/@core/date-time/time-range.ts
  libs/components/src/lib/@core/date-time/time.ts
  libs/components/src/lib/components/calendar-range/calendar-range.component.ts
  libs/components/src/lib/components/input/input-date-time-range/input-date-range-time.transformer.ts
  libs/components/src/lib/components/input/input-date-time-range/input-layout-date-time-range.component.ts
  libs/components/src/lib/components/internal/primitive-calendar-range/primitive-calendar-range.component.ts
Labels: availability:reviewed, availability:tested, version:5

#2198 fix(components/panel): fix incorrect css variable name for subheader color #2186 v4
  apps/doc/src/app/components/progress/line-segmented/examples/base/progress-base-example.component.ts
  libs/components/src/lib/components/panel/panel.component.less
Labels: availability:reviewed, availability:tested, version:4

#2197 Fix/dialog header limits 755 v4
  apps/doc/src/app/components/dialogs/confirm-dialog/confirm.component.html
  apps/doc/src/app/components/dialogs/dialog/dialog-example.component.html
  apps/doc/src/app/components/dialogs/sidebar/sidebar.component.html
  apps/doc/src/styles.less
  libs/components/src/lib/components/dialogs/confirm-dialog/confirm-dialog.component.html
  libs/components/src/lib/components/dialogs/confirm-dialog/confirm-dialog.component.less
  libs/components/src/lib/components/dialogs/confirm-dialog/confirm-dialog.component.ts
  libs/components/src/lib/components/dialogs/dialog/dialog.component.html
  libs/components/src/lib/components/dialogs/dialog/dialog.component.less
  libs/components/src/lib/components/dialogs/dialog/dialog.component.ts
  libs/components/src/lib/components/dialogs/sidebar/sidebar.component.html
  libs/components/src/lib/components/dialogs/sidebar/sidebar.component.less
  libs/components/src/lib/components/dialogs/sidebar/sidebar.component.ts
  libs/components/src/lib/components/widget/widget.component.less
  libs/components/src/lib/util/dom/is-textoverflow.ts
Labels: availability:reviewed, availability:tested, version:4

#2196 fix(components/button): text in buttons should be in a single line #1365 v4
  apps/doc/src/app/components/buttons/button/button.component.html
  apps/doc/src/app/components/buttons/button/button.component.ts
  apps/doc/src/app/components/buttons/button/button.module.ts
  apps/doc/src/app/components/buttons/button/examples/overflow/button-text-overflow-example.component.html
  apps/doc/src/app/components/buttons/button/examples/overflow/button-text-overflow-example.component.ts
  apps/doc/src/app/components/navigation-menu/navigation-menu-example.component.ts
  apps/doc/src/app/components/switcher/examples/switcher-overflow-example/switcher-overflow-example.component.html
  apps/doc/src/app/components/switcher/examples/switcher-overflow-example/switcher-overflow-example.component.less
  apps/doc/src/app/components/switcher/examples/switcher-overflow-example/switcher-overflow-example.component.ts
  apps/doc/src/app/components/switcher/switcher-example.component.html
  apps/doc/src/app/components/switcher/switcher-example.component.ts
  apps/doc/src/app/components/switcher/switcher-example.module.ts
  libs/components/src/lib/components/button/button.component.html
  libs/components/src/lib/components/button/button.component.less
  libs/helpers/src/lib/directives/overflow/overflow.service.ts
Labels: availability:reviewed, availability:tested, version:4

#2194 feat(components/navigation): add expanded items support #1838 v4
  apps/doc/src/app/components/navigation/examples/navigation-basic-example/navigation-basic-example.component.html
  apps/doc/src/app/components/navigation/examples/navigation-basic-example/navigation-basic-example.component.ts
  apps/doc/src/app/components/navigation/navigation-example.component.html
  apps/doc/src/app/components/navigation/navigation-example.const.ts
  libs/components/src/lib/components/navigation/components/prizm-navigation-item-expandable/prizm-navigation-item-expandable.component.html
  libs/components/src/lib/components/navigation/components/prizm-navigation-item-expandable/prizm-navigation-item-expandable.component.spec.ts
  libs/components/src/lib/components/navigation/components/prizm-navigation-item-expandable/prizm-navigation-item-expandable.component.ts
  libs/components/src/lib/components/navigation/components/prizm-navigation-item-simple/prizm-navigation-item-simple.component.html
  libs/components/src/lib/components/navigation/components/prizm-navigation-item-simple/prizm-navigation-item-simple.component.less
  libs/components/src/lib/components/navigation/pipes/calculate-margin.pipe.ts
  libs/components/src/lib/components/navigation/prizm-navigation.component.html
  libs/components/src/lib/components/navigation/prizm-navigation.component.spec.ts
  libs/components/src/lib/components/navigation/prizm-navigation.component.ts
  libs/components/src/lib/components/navigation/prizm-navigation.module.ts
  libs/components/src/lib/components/navigation/services/expanded-navigation.service.ts
Labels: availability:reviewed, availability:tested, version:4

#2195 feat(chore): prepare release 5.3.0 #0
  .github/PULL_REQUEST_TEMPLATE/prepare_release_for_5.md
  .github/workflows/main-publish-ng18.yml
  .github/workflows/main-publish-ng18.yml.ng18
  .github/workflows/pr-describe.yaml
  .github/workflows/pr-ng17.yml
  .github/workflows/pr-review.yml
  apps/doc/src/app/about-prizm/changelog/CHANGELOG.md
  apps/doc/src/app/version-manager/current.const.ts
  apps/doc/src/app/version-manager/versions.constants.ts
  libs/addons/query-builder/.eslintrc.json
  libs/addons/query-builder/package.json
  libs/ast/package.json
  libs/charts/base/package.json
  libs/components/package.json
  libs/components/src/lib/components/chips/chips-item/chips-item.spec.ts
  libs/components/src/lib/components/chips/chips.component.spec.ts
  libs/components/src/lib/components/navigation/components/prizm-navigation-item-expandable/prizm-navigation-item-expandable.component.spec.ts
  libs/components/src/lib/components/navigation/components/prizm-navigation-item-simple/prizm-navigation-item-simple.component.spec.ts
  libs/core/package.json
  libs/helpers/package.json
  libs/helpers/src/lib/pipes/to-type/to-type.pipe.spec.ts
  libs/helpers/src/lib/services/destroy/destroy.service.spec.ts
  libs/i18n/package.json
  libs/icons/base/package.json
  libs/icons/flags/package.json
  libs/icons/loader/package.json
  libs/nxmv/package.json
  libs/plugin/package.json
  libs/schematics/package.json
  libs/schematics/src/ng-add/consts.ts
  libs/theme/package.json
  local/package.json
  package-lock.json
  package.json
  package.json.ng17
  pnpm-lock.yaml
Labels: availability:reviewed, availability:tested

#2204 fix(theme/theme-service): set correct initial theme for micro frontend #2201
  libs/theme/src/lib/services/theme.service.ts
Labels: availability:reviewed, availability:tested, version:5

#2216 Fix/initial theme 2201 v4
  libs/theme/src/lib/services/theme.service.ts
Labels: availability:reviewed, availability:tested, version:4

#2217 feat(chore): release 5.3.2
  apps/doc/src/app/about-prizm/changelog/CHANGELOG.md
  apps/doc/src/app/version-manager/current.const.ts
  apps/doc/src/app/version-manager/versions.constants.ts
  libs/addons/query-builder/package.json
  libs/ast/package.json
  libs/charts/base/package.json
  libs/components/package.json
  libs/core/package.json
  libs/helpers/package.json
  libs/i18n/package.json
  libs/icons/base/package.json
  libs/icons/flags/package.json
  libs/icons/loader/package.json
  libs/nxmv/package.json
  libs/plugin/package.json
  libs/schematics/package.json
  libs/schematics/src/ng-add/consts.ts
  libs/theme/package.json
  local/package.json
  package-lock.json
  package.json
Labels: availability:reviewed

#2205 feat: release 4.8.0
  .github/PULL_REQUEST_TEMPLATE/prepare_release_for_4.md
  .github/workflows/pr-describe.yaml
  .github/workflows/pr-ng15.yml
  .github/workflows/pr-ng16.yml
  .github/workflows/pr-ng17.yml
  .github/workflows/pr-review.yml
  apps/doc/src/app/about-prizm/changelog/CHANGELOG.md
  apps/doc/src/app/version-manager/current.const.ts
  apps/doc/src/app/version-manager/versions.constants.ts
  libs/ast/package.json
  libs/charts/base/package.json
  libs/components/package.json
  libs/components/src/lib/components/chips/chips.component.spec.ts
  libs/components/src/lib/components/dropdowns/tree-multi-select/item/tree-multi-select-item.component.ts
  libs/components/src/lib/components/navigation/components/prizm-navigation-item-expandable/prizm-navigation-item-expandable.component.spec.ts
  libs/components/src/lib/components/navigation/components/prizm-navigation-item-simple/prizm-navigation-item-simple.component.spec.ts
  libs/core/package.json
  libs/helpers/package.json
  libs/i18n/package.json
  libs/icons/base/package.json
  libs/icons/flags/package.json
  libs/icons/loader/package.json
  libs/nxmv/package.json
  libs/plugin/package.json
  libs/schematics/package.json
  libs/schematics/src/ng-add/consts.ts
  libs/theme/package.json
  package.json
Labels: availability:reviewed, availability:tested

#2221 fix(ci): after published v4 main demo update instead v4 #0
  .github/workflows/main-publish-ng17.yml
  .github/workflows/main-publish-ng17.yml.ng17
Labels: devOnly
