Repository zyfra/Prizm, pull requests merged in 2024-06, with the labels that each got.

#1751 feat(chore): release 4.3.1
  .github/workflows/beta-publish-ng17.yml
  .github/workflows/main-publish-ng17.yml
  .github/workflows/pre-release-publish-ng17.yml
  apps/doc/src/app/about-prizm/changelog/CHANGELOG.md
  apps/doc/src/app/version-manager/current.const.ts
  apps/doc/src/app/version-manager/current.const.ts.ng17
  apps/doc/src/app/version-manager/versions.constants.ts
  libs/ast/package.json
  libs/ast/package.json.ng17
  libs/charts/base/package.json
  libs/charts/base/package.json.ng17
  libs/components/package.json
  libs/components/package.json.ng17
  libs/core/package.json
  libs/core/package.json.ng17
  libs/helpers/package.json
  libs/helpers/package.json.ng17
  libs/i18n/package.json
  libs/i18n/package.json.ng17
  libs/icons/base/package.json
  libs/icons/base/package.json.ng17
  libs/icons/flags/package.json
  libs/icons/flags/package.json.ng17
  libs/icons/loader/package.json
  libs/nxmv/package.json
  libs/nxmv/package.json.ng17
  libs/plugin/package.json
  libs/plugin/package.json.ng17
  libs/schematics/package.json
  libs/schematics/package.json.ng17
  libs/theme/package.json
  libs/theme/package.json.ng17
  package.json
  package.json.ng17
Labels: availability:tested, version:4

#1753 feat: release 3.13.2
  .github/workflows/beta-publish-ng14.yml
  .github/workflows/beta-publish-ng15.yml
  .github/workflows/beta-publish-ng16.yml
  .github/workflows/main-publish-ng14.yml
  .github/workflows/main-publish-ng15.yml
  .github/workflows/main-publish-ng16.yml
  .github/workflows/pre-release-publish-ng14.yml
  .github/workflows/pre-release-publish-ng15.yml
  .github/workflows/pre-release-publish-ng16.yml
  apps/doc/src/app/about-prizm/changelog/CHANGELOG.md
  apps/doc/src/app/version-manager/current.const.ts.ng14
  apps/doc/src/app/version-manager/current.const.ts.ng15
  apps/doc/src/app/version-manager/current.const.ts.ng16
  apps/doc/src/app/version-manager/versions.constants.ts
  libs/ast/package.json.ng14
  libs/ast/package.json.ng15
  libs/ast/package.json.ng16
  libs/charts/base/package.json.ng14
  libs/charts/base/package.json.ng15
  libs/charts/base/package.json.ng16
  libs/components/package.json.ng14
  libs/components/package.json.ng15
  libs/components/package.json.ng16
  libs/core/package.json.ng14
  libs/core/package.json.ng15
  libs/core/package.json.ng16
  libs/helpers/package.json.ng14
  libs/helpers/package.json.ng15
  libs/helpers/package.json.ng16
  libs/i18n/package.json.ng14
  libs/i18n/package.json.ng15
  libs/i18n/package.json.ng16
  libs/icons/base/package.json.ng14
  libs/icons/base/package.json.ng15
  libs/icons/base/package.json.ng16
  libs/icons/flags/package.json.ng14
  libs/icons/flags/package.json.ng15
  libs/icons/flags/package.json.ng16
  libs/nxmv/package.json.ng14
  libs/nxmv/package.json.ng15
  libs/nxmv/package.json.ng16
  libs/plugin/package.json.ng14
  libs/plugin/package.json.ng15
  libs/plugin/package.json.ng16
  libs/schematics/package.json.ng14
  libs/schematics/package.json.ng15
  libs/schematics/package.json.ng16
  libs/theme/package.json.ng14
  libs/theme/package.json.ng15
  libs/theme/package.json.ng16
  package.json.ng14
  package.json.ng15
  package.json.ng16
Labels: availability:tested, version:3

#1806 feat(chore): update mr checklist template
  .gitlab/merge_request_templates/mr_template.md
Labels: state:ready, devOnly, availability:review, version:3

#1800 fix(components/chips): update chips on async changes #1754
  libs/components/src/lib/components/chips/chips.component.ts
Labels: state:ready, availability:tested, version:3

#1796 fix(components/input-date-time): default time is set only after focus is removed #1762
  libs/components/src/lib/components/input/input-date-time/input-layout-date-time.component.ts
Labels: state:ready, availability:tested, version:3

#1793 fix(components/input-date-relative): active items not updated when va…
  apps/doc/src/app/components/input/input-layout-date-relative/examples/base/input-layout-date-relative-base-example.component.html
  apps/doc/src/app/components/input/input-layout-date-relative/examples/base/input-layout-date-relative-base-example.component.ts
  apps/doc/src/app/components/input/input-layout-date-relative/input-layout-date-relative.module.ts
  libs/components/src/lib/components/input/input-date-relative/input-layout-date-relative.component.ts
Labels: state:ready, availability:tested, version:3

#1790 fix(components/panel): set default border radius as 0px to panel #1767
  libs/components/src/lib/components/panel/panel.component.less
Labels: state:ready, availability:tested, version:3

#1785 fix(components/input-date-time): display time 00:00 when a date is selected #1575
  libs/components/src/lib/components/input/input-date-time/input-layout-date-time.component.ts
Labels: state:ready, availability:tested, version:3

#1783 fix(components/hint): update overlay only when changes deps #1719 #716
  libs/components/src/lib/directives/hint/hint.directive.ts
  libs/helpers/src/lib/util/directive.spec.ts
  libs/helpers/src/lib/util/directive.ts
  libs/helpers/src/lib/util/index.ts
Labels: state:ready, availability:tested, version:3

#1780 fix(docs/tab): remove $any from basic example #841
  apps/doc/src/app/components/tabs/examples/tabs-example-basic/tabs-example-basic.component.html
Labels: state:ready, availability:tested, version:3

#1778 fix(components/input-date-range): added corrector if from is more than to in v3 #1628
  libs/components/src/lib/@core/date-time/day.ts
  libs/components/src/lib/components/input/input-date-range/input-layout-date-range.component.ts
Labels: state:ready, availability:tested, version:3

#1775 fix(components/panel): rename panel component to name with prefix V3 #1665
  apps/doc/src/app/components/panel/examples/setup-module.md
  apps/doc/src/app/components/panel/panel-example.module.ts
  libs/components/src/lib/components/panel/panel.component.ts
  libs/components/src/lib/components/panel/panel.module.ts
Labels: state:ready, availability:tested, version:3

#1773 Fix/file upload arrays v3
  apps/doc/src/app/components/file-upload/examples/auto-upload/auto-upload.component.html
  apps/doc/src/app/components/file-upload/examples/auto-upload/auto-upload.component.ts
  apps/doc/src/app/components/file-upload/examples/basic/basic.component.html
  apps/doc/src/app/components/file-upload/examples/basic/basic.component.ts
  apps/doc/src/app/components/file-upload/examples/i18n/file-upload-i18n-example.component.html
  apps/doc/src/app/components/file-upload/examples/i18n/file-upload-i18n-example.component.ts
  apps/doc/src/app/components/file-upload/file-upload-example.component.ts
  libs/components/src/lib/components/file-upload/file-upload.component.html
  libs/components/src/lib/components/file-upload/file-upload.component.less
  libs/components/src/lib/components/file-upload/file-upload.component.ts
  libs/components/src/lib/components/file-upload/pipes/file-size.pipe.ts
  libs/i18n/src/lib/interfaces/language.ts
  libs/i18n/src/lib/languages/russian/file-upload.ts
Labels: state:ready, availability:tested, version:3

#1765 fix(chore): remove cloud nx token v3
  nx.json.ng14
  nx.json.ng15
  nx.json.ng16
Labels: state:ready, devOnly, version:3

#1802 fix(icons): restored icon selection-checkbox-marked-circle #1735
  libs/components/src/lib/abstract/dialog.service.ts
  libs/icons/base/assets/16/temp-selection-checkbox-marked-circle.svg
  libs/icons/base/assets/24/temp-selection-checkbox-marked-circle.svg
  libs/icons/base/base/index.ts
  libs/icons/base/base/names/index.ts
  libs/icons/base/base/source/icon-set.ts
  libs/icons/base/base/source/index.ts
  libs/icons/base/base/source/prizm-icons.model.ts
  libs/icons/base/base/source/temp-selection-checkbox-marked-circle/index.ts
  libs/icons/base/base/source/temp-selection-checkbox-marked-circle/ng-package.json
  libs/icons/base/base/source/temp-selection-checkbox-marked-circle/prizmIcons-temp-selection-checkbox-marked-circle.icon.ts
  libs/icons/base/full/index.ts
  libs/icons/base/full/names/index.ts
  libs/icons/base/full/source/icon-set.ts
  libs/icons/base/full/source/index.ts
  libs/icons/base/full/source/prizm-icons.model.ts
  libs/icons/base/full/source/temp-selection-checkbox-marked-circle/index.ts
  libs/icons/base/full/source/temp-selection-checkbox-marked-circle/ng-package.json
  libs/icons/base/full/source/temp-selection-checkbox-marked-circle/prizmIcons-temp-selection-checkbox-marked-circle.icon.ts
  libs/icons/base/src/styles/icons-base/prizm-base-icons-location.css
  libs/icons/base/src/styles/icons-base/prizm-base-icons-location.scss
  libs/icons/base/src/styles/icons-base/prizm-base-icons.css
  libs/icons/base/src/styles/icons-base/prizm-base-icons.eot
  libs/icons/base/src/styles/icons-base/prizm-base-icons.scss
  libs/icons/base/src/styles/icons-base/prizm-base-icons.ttf
  libs/icons/base/src/styles/icons-base/prizm-base-icons.woff
  libs/icons/base/src/styles/icons-base/prizm-base-icons.woff2
  libs/icons/base/src/styles/icons-full/prizm-full-icons-location.css
  libs/icons/base/src/styles/icons-full/prizm-full-icons-location.scss
  libs/icons/base/src/styles/icons-full/prizm-full-icons.css
  libs/icons/base/src/styles/icons-full/prizm-full-icons.eot
  libs/icons/base/src/styles/icons-full/prizm-full-icons.scss
  libs/icons/base/src/styles/icons-full/prizm-full-icons.ttf
  libs/icons/base/src/styles/icons-full/prizm-full-icons.woff
  libs/icons/base/src/styles/icons-full/prizm-full-icons.woff2
  libs/icons/loader/full/src/icons.ts
  libs/icons/loader/src/lib/icons.ts
Labels: availability:tested, version:4

#1799 fix(components/chips): update chips on async changes #1754
  libs/components/src/lib/components/chips/chips.component.ts
Labels: availability:tested, version:4

#1795 fix(components/input-date-time): default time is set only after focus is removed #1762
  libs/components/src/lib/components/input/input-date-time/input-layout-date-time.component.ts
Labels: availability:tested, version:4

#1792 fix(components/input-date-relative): active items not updated when value set by formControl #1685
  apps/doc/src/app/components/input/input-layout-date-relative/examples/base/input-layout-date-relative-base-example.component.html
  apps/doc/src/app/components/input/input-layout-date-relative/examples/base/input-layout-date-relative-base-example.component.ts
  apps/doc/src/app/components/input/input-layout-date-relative/input-layout-date-relative.module.ts
  libs/components/src/lib/components/input/input-date-relative/input-layout-date-relative.component.html
  libs/components/src/lib/components/input/input-date-relative/input-layout-date-relative.component.ts
Labels: availability:tested, version:4

#1791 fix(components/panel): set default border radius as 0px to panel #1767
  libs/components/src/lib/components/panel/panel.component.less
Labels: availability:tested, version:4

#1782 fix(components/hint): update overlay only when changes deps #1719 #716
  libs/components/src/lib/directives/hint/hint.directive.ts
Labels: availability:tested, version:4

#1781 fix(docs/tab): remove $any from basic example #841
  apps/doc/src/app/components/tabs/examples/tabs-example-basic/tabs-example-basic.component.html
Labels: availability:tested, version:4

#1777 fix(components/input-date-range): added corrector if from is more than to #1628
  libs/components/src/lib/@core/date-time/day.ts
  libs/components/src/lib/components/input/input-date-range/input-layout-date-range.component.ts
Labels: availability:tested, version:4

#1774 fix(components/panel): rename panel component to name with prefix #1665
  apps/doc/src/app/components/panel/examples/setup-module.md
  apps/doc/src/app/components/panel/panel-example.module.ts
  libs/components/src/lib/components/panel/panel.component.ts
  libs/components/src/lib/components/panel/panel.module.ts
Labels: availability:tested, version:4

#1760 fix(components/file-upload): newly uploaded files should not overwrte existing files array #1662
  apps/doc/src/app/components/file-upload/examples/auto-upload/auto-upload.component.html
  apps/doc/src/app/components/file-upload/examples/auto-upload/auto-upload.component.ts
  apps/doc/src/app/components/file-upload/examples/basic/basic.component.html
  apps/doc/src/app/components/file-upload/examples/basic/basic.component.ts
  apps/doc/src/app/components/file-upload/examples/i18n/file-upload-i18n-example.component.html
  apps/doc/src/app/components/file-upload/examples/i18n/file-upload-i18n-example.component.ts
  apps/doc/src/app/components/file-upload/file-upload-example.component.ts
  libs/components/src/lib/components/file-upload/file-upload.component.html
  libs/components/src/lib/components/file-upload/file-upload.component.less
  libs/components/src/lib/components/file-upload/file-upload.component.ts
  libs/components/src/lib/components/file-upload/pipes/file-size.pipe.ts
Labels: availability:tested, version:4

#1786 fix(doc): version detection on doc.zyfra or prizm.site #1133
  .github/PULL_REQUEST_TEMPLATE/prepare_release_for_3.md
  .github/PULL_REQUEST_TEMPLATE/prepare_release_for_4.md
  apps/doc/src/app/version-manager/util.ts
  apps/doc/src/app/version-manager/version-manager.component.ts
  apps/doc/src/app/version-manager/versions.constants.ts
Labels: state:ready, devOnly, availability:reviewed, version:4

#1787 fix(doc): version detection on doc.zyfra or prizm.site #1133
  .github/PULL_REQUEST_TEMPLATE/prepare_release_for_3.md
  apps/doc/src/app/version-manager/util.ts
  apps/doc/src/app/version-manager/version-manager.component.ts
  apps/doc/src/app/version-manager/versions.constants.ts
Labels: state:ready, devOnly, availability:reviewed, availability:review, version:3

#1814 fix(charts/line): add missing seriesFiled input to Line chart #1811
  apps/doc/src/app/charts/line/examples/series/prizm-charts-line-series-example.component.html
  apps/doc/src/app/charts/line/examples/series/prizm-charts-line-series-example.component.ts
  apps/doc/src/app/charts/line/line.component.html
  apps/doc/src/app/charts/line/line.component.ts
  apps/doc/src/app/charts/line/line.module.ts
  libs/charts/base/src/lib/components/line/prizm-charts-line.component.ts
Labels: state:ready, priority:urgently, availability:tested, version:3

#1813 fix(charts/line): add missing seriesField input to Line chart #1811
  apps/doc/src/app/charts/line/examples/series/prizm-charts-line-series-example.component.html
  apps/doc/src/app/charts/line/examples/series/prizm-charts-line-series-example.component.ts
  apps/doc/src/app/charts/line/line.component.html
  apps/doc/src/app/charts/line/line.component.ts
  apps/doc/src/app/charts/line/line.module.ts
  libs/charts/base/src/lib/components/line/prizm-charts-line.component.ts
Labels: state:ready, priority:urgently, availability:tested, version:4

#1820 fix(components/chips): hint appears in multiselect after deletion #1815
  libs/components/src/lib/components/chips/chips-item/chips-item.component.html
  libs/components/src/lib/components/chips/chips-item/chips-item.component.ts
Labels: availability:tested, version:3

#1818 fix(components/chips): hint appears in multiselect after deletion #1815
  libs/components/src/lib/components/chips/chips-item/chips-item.component.html
  libs/components/src/lib/components/chips/chips-item/chips-item.component.ts
Labels: availability:tested, version:4

#1776 fix(doc/icons): pagination on search icon #1701
  apps/doc/src/app/components/icons/base/all/all-icon.component.ts
Labels: availability:tested, version:4

#1808 feat(chore/release): 3.14.0
  .github/workflows/beta-publish-ng14.yml
  .github/workflows/beta-publish-ng15.yml
  .github/workflows/beta-publish-ng16.yml
  .github/workflows/main-publish-ng14.yml
  .github/workflows/main-publish-ng15.yml
  .github/workflows/main-publish-ng16.yml
  .github/workflows/pre-release-publish-ng14.yml
  .github/workflows/pre-release-publish-ng15.yml
  .github/workflows/pre-release-publish-ng16.yml
  apps/doc/src/app/about-prizm/changelog/CHANGELOG.md
  apps/doc/src/app/components/tabs/tabs-example.component.ts
  apps/doc/src/app/version-manager/current.const.ts.ng14
  apps/doc/src/app/version-manager/current.const.ts.ng15
  apps/doc/src/app/version-manager/current.const.ts.ng16
  apps/doc/src/app/version-manager/versions.constants.ts
  libs/ast/package.json.ng14
  libs/ast/package.json.ng15
  libs/ast/package.json.ng16
  libs/charts/base/package.json.ng14
  libs/charts/base/package.json.ng15
  libs/charts/base/package.json.ng16
  libs/components/package.json.ng14
  libs/components/package.json.ng15
  libs/components/package.json.ng16
  libs/components/src/lib/components/input/common/input-hint/input-hint.directive.ts
  libs/components/src/lib/components/switcher/directives/switcher-hint.directive.ts
  libs/components/src/lib/directives/hint/hint.directive.ts
  libs/core/package.json.ng14
  libs/core/package.json.ng15
  libs/core/package.json.ng16
  libs/helpers/package.json.ng14
  libs/helpers/package.json.ng15
  libs/helpers/package.json.ng16
  libs/i18n/package.json.ng14
  libs/i18n/package.json.ng15
  libs/i18n/package.json.ng16
  libs/icons/base/package.json.ng14
  libs/icons/base/package.json.ng15
  libs/icons/base/package.json.ng16
  libs/icons/flags/package.json.ng14
  libs/icons/flags/package.json.ng15
  libs/icons/flags/package.json.ng16
  libs/nxmv/package.json.ng14
  libs/nxmv/package.json.ng15
  libs/nxmv/package.json.ng16
  libs/plugin/package.json.ng14
  libs/plugin/package.json.ng15
  libs/plugin/package.json.ng16
  libs/schematics/package.json.ng14
  libs/schematics/package.json.ng15
  libs/schematics/package.json.ng16
  libs/theme/package.json.ng14
  libs/theme/package.json.ng15
  libs/theme/package.json.ng16
  package.json.ng14
  package.json.ng15
  package.json.ng16
Labels: state:ready, availability:tested, version:3

#1824 fix(icons): fix icons source path #000
  libs/icons/base/base/index.ts
  libs/icons/base/full/index.ts
Labels: availability:review, availability:tested

#1825 feat(chore): up version to 4.3.3
  .github/workflows/beta-publish-ng17.yml
  .github/workflows/main-publish-ng17.yml
  .github/workflows/pre-release-publish-ng17.yml
  apps/doc/src/app/about-prizm/changelog/CHANGELOG.md
  apps/doc/src/app/version-manager/current.const.ts
  apps/doc/src/app/version-manager/current.const.ts.ng17
  apps/doc/src/app/version-manager/versions.constants.ts
  libs/ast/package.json
  libs/ast/package.json.ng17
  libs/charts/base/package.json
  libs/charts/base/package.json.ng17
  libs/components/package.json
  libs/components/package.json.ng17
  libs/core/package.json
  libs/core/package.json.ng17
  libs/helpers/package.json
  libs/helpers/package.json.ng17
  libs/i18n/package.json
  libs/i18n/package.json.ng17
  libs/icons/base/package.json
  libs/icons/base/package.json.ng17
  libs/icons/flags/package.json
  libs/icons/flags/package.json.ng17
  libs/icons/loader/package.json
  libs/nxmv/package.json
  libs/nxmv/package.json.ng17
  libs/plugin/package.json
  libs/plugin/package.json.ng17
  libs/schematics/package.json
  libs/schematics/package.json.ng17
  libs/theme/package.json
  libs/theme/package.json.ng17
  package.json
  package.json.ng17
Labels: availability:tested

#1826 fix(components/input-icon-button): disabled button should not fire events #1823
  apps/doc/src/app/components/input/input-text/examples/input-icon-buttons-example/input-icon-buttons-example.component.html
  apps/doc/src/app/components/input/input-text/examples/input-icon-buttons-example/input-icon-buttons-example.component.ts
  apps/doc/src/app/components/input/input-text/input-example.module.ts
  libs/components/src/lib/components/input/common/input-icon-button/input-icon-button.component.html
  libs/components/src/lib/components/input/common/input-icon-button/input-icon-button.component.ts
Labels: state:ready, availability:tested, version:4

#1822 fix(components/inputs): fix markup for input icon button #1529
  libs/components/src/lib/components/input/common/input-icon-button/input-icon-button.component.less
Labels: state:ready, availability:tested, version:4

#1804 fix(doc/textarea): missing border property added for textarea livedemo #1803
  apps/doc/src/app/components/input/textarea/textarea-example.component.html
Labels: state:ready, availability:tested, version:4

#1827 fix(components/input-icon-button): disabled button should not fire events #1823 v3
  apps/doc/src/app/components/input/input-text/examples/input-icon-buttons-example/input-icon-buttons-example.component.html
  apps/doc/src/app/components/input/input-text/examples/input-icon-buttons-example/input-icon-buttons-example.component.ts
  apps/doc/src/app/components/input/input-text/input-example.module.ts
  libs/components/src/lib/components/input/common/input-icon-button/input-icon-button.component.ts
Labels: state:ready, availability:tested, version:3

#1807 fix(doc/textarea): missing border property added for textarea livedemo #1803
  apps/doc/src/app/components/input/textarea/textarea-example.component.html
Labels: state:ready, availability:tested, version:3

#1830 feat(chore): release 3.14.1
  .github/workflows/beta-publish-ng14.yml
  .github/workflows/beta-publish-ng15.yml
  .github/workflows/beta-publish-ng16.yml
  .github/workflows/main-publish-ng14.yml
  .github/workflows/main-publish-ng15.yml
  .github/workflows/main-publish-ng16.yml
  .github/workflows/pre-release-publish-ng14.yml
  .github/workflows/pre-release-publish-ng15.yml
  .github/workflows/pre-release-publish-ng16.yml
  apps/doc/src/app/about-prizm/changelog/CHANGELOG.md
  apps/doc/src/app/version-manager/current.const.ts.ng14
  apps/doc/src/app/version-manager/current.const.ts.ng15
  apps/doc/src/app/version-manager/current.const.ts.ng16
  apps/doc/src/app/version-manager/versions.constants.ts
  libs/ast/package.json.ng14
  libs/ast/package.json.ng15
  libs/ast/package.json.ng16
  libs/charts/base/package.json.ng14
  libs/charts/base/package.json.ng15
  libs/charts/base/package.json.ng16
  libs/components/package.json.ng14
  libs/components/package.json.ng15
  libs/components/package.json.ng16
  libs/core/package.json.ng14
  libs/core/package.json.ng15
  libs/core/package.json.ng16
  libs/helpers/package.json.ng14
  libs/helpers/package.json.ng15
  libs/helpers/package.json.ng16
  libs/i18n/package.json.ng14
  libs/i18n/package.json.ng15
  libs/i18n/package.json.ng16
  libs/icons/base/package.json.ng14
  libs/icons/base/package.json.ng15
  libs/icons/base/package.json.ng16
  libs/icons/flags/package.json.ng14
  libs/icons/flags/package.json.ng15
  libs/icons/flags/package.json.ng16
  libs/nxmv/package.json.ng14
  libs/nxmv/package.json.ng15
  libs/nxmv/package.json.ng16
  libs/plugin/package.json.ng14
  libs/plugin/package.json.ng15
  libs/plugin/package.json.ng16
  libs/schematics/package.json.ng14
  libs/schematics/package.json.ng15
  libs/schematics/package.json.ng16
  libs/theme/package.json.ng14
  libs/theme/package.json.ng15
  libs/theme/package.json.ng16
  package.json.ng14
  package.json.ng15
  package.json.ng16
Labels: state:ready, availability:tested, version:3
