Repository zyfra/Prizm, pull requests merged in 2024-01, with the labels that each got.

#1258 chore: carousel deleted
  apps/doc/src/app/app.routes.ts
  apps/doc/src/app/components/input/carousel/carousel-example.component.html
  apps/doc/src/app/components/input/carousel/carousel-example.component.less
  apps/doc/src/app/components/input/carousel/carousel-example.component.ts
  apps/doc/src/app/components/input/carousel/carousel-example.module.ts
  apps/doc/src/app/components/input/carousel/examples/carousel-array-of-objects-example/carousel-array-of-objects-example.component.html
  apps/doc/src/app/components/input/carousel/examples/carousel-array-of-objects-example/carousel-array-of-objects-example.component.less
  apps/doc/src/app/components/input/carousel/examples/carousel-array-of-objects-example/carousel-array-of-objects-example.component.ts
  apps/doc/src/app/components/input/carousel/examples/carousel-basic-example/carousel-basic-example.component.html
  apps/doc/src/app/components/input/carousel/examples/carousel-basic-example/carousel-basic-example.component.less
  apps/doc/src/app/components/input/carousel/examples/carousel-basic-example/carousel-basic-example.component.ts
  apps/doc/src/app/components/input/carousel/examples/carousel-light-example/carousel-light-example.component.html
  apps/doc/src/app/components/input/carousel/examples/carousel-light-example/carousel-light-example.component.less
  apps/doc/src/app/components/input/carousel/examples/carousel-light-example/carousel-light-example.component.ts
  apps/doc/src/app/components/input/carousel/examples/carousel-year-month-example/carousel-year-month-example.component.html
  apps/doc/src/app/components/input/carousel/examples/carousel-year-month-example/carousel-year-month-example.component.less
  apps/doc/src/app/components/input/carousel/examples/carousel-year-month-example/carousel-year-month-example.component.ts
  apps/doc/src/app/components/input/carousel/examples/carousel-year-month-example/month.pipe.ts
  apps/doc/src/app/components/input/carousel/examples/input-as-carousel/input-as-carousel.component.html
  apps/doc/src/app/components/input/carousel/examples/input-as-carousel/input-as-carousel.component.less
  apps/doc/src/app/components/input/carousel/examples/input-as-carousel/input-as-carousel.component.ts
  apps/doc/src/app/components/input/carousel/examples/input-as-carousel/input-as-carousel.module.ts
  apps/doc/src/app/components/input/carousel/examples/setup-module.md
  apps/doc/src/app/pages.ts
  libs/components/src/lib/components/input/carousel/carousel-auxiliary-left.component.ts
  libs/components/src/lib/components/input/carousel/carousel-auxiliary-right.component.ts
  libs/components/src/lib/components/input/carousel/carousel.component.html
  libs/components/src/lib/components/input/carousel/carousel.component.less
  libs/components/src/lib/components/input/carousel/carousel.component.ts
  libs/components/src/lib/components/input/carousel/carousel.module.ts
  libs/components/src/lib/components/input/carousel/index.ts
Labels: ready, ready for test, testing_done

#1193 fix: check box extra margin #1189
  apps/doc/src/app/components/checkbox/checkbox-example.component.html
  apps/doc/src/app/components/checkbox/checkbox-example.component.less
  libs/components/src/lib/components/checkbox/checkbox.component.less
Labels: ready, testing_done

#1226 feat: add styling for table cell with prizmInput (breaking change)
  apps/doc/src/app/components/table/examples/table-data-source-example/table-data-source-example.component.html
  apps/doc/src/app/components/table/examples/table-data-source-example/table-data-source-example.component.less
  apps/doc/src/app/components/table/examples/table-editable-col-example/table-editable-col-example.component.less
  apps/doc/src/app/components/table/examples/table-editable-row-example/table-editable-row-example.component.html
  apps/doc/src/app/components/table/examples/table-editable-row-example/table-editable-row-example.component.less
  apps/doc/src/app/components/table/examples/table-search-example/table-search-example.component.html
  apps/doc/src/app/components/table/examples/table-search-example/table-search-example.component.less
  apps/doc/src/app/components/table/examples/table-server-sort-example/table-server-sort-example.component.html
  apps/doc/src/app/components/table/examples/table-server-sort-example/table-server-sort-example.component.less
  apps/doc/src/app/components/table/examples/table-sort-example/table-sort-example.component.html
  apps/doc/src/app/components/table/examples/table-sort-example/table-sort-example.component.less
  apps/doc/src/app/components/table/table-example.module.ts
  libs/components/src/lib/components/table/td/td.component.less
  libs/components/src/lib/components/table/th/th.style.less
Labels: ready, testing_done

#1266 chore: deprecated prizm-icons-svg
  apps/doc/src/app/code-demo/files/src/app/shared.module.ts.template
  apps/doc/src/app/components/buttons/icon-button/icon-button.module.ts
  apps/doc/src/app/components/icons/flags/examples/setup-module.md
  apps/doc/src/app/components/icons/svg/examples/setup-module.md
  apps/doc/src/app/components/icons/svg/icon.component.html
  apps/doc/src/app/components/icons/svg/icon.module.ts
  apps/doc/src/app/components/navigation-menu/navigation-menu-example.module.ts
  apps/doc/src/app/components/widget/widget-example.module.ts
  apps/doc/src/app/logo/logo.module.ts
  apps/doc/src/app/pages.ts
  libs/components/src/lib/components/navigation-menu/components/prizm-navigation-menu-item/prizm-navigation-menu-item.component.ts
  libs/components/src/lib/components/navigation-menu/components/prizm-navigation-menu/prizm-navigation-menu.component.ts
  libs/icons/base/src/lib/prizm-icons.component.ts
  libs/icons/base/src/lib/prizm-icons.module.ts
  libs/icons/flags/src/lib/prizm-flag-icons.component.ts
  libs/icons/flags/src/lib/prizm-flag-icons.module.ts
Labels: devOnly, reopen, ready for dev

#1247 Removed select, multiselect
  apps/doc/src/app/pages.ts
Labels: ready for test, ready for dev

#1307 feat: update doc v4
  .firebaserc
  .github/workflows/beta-publish-ng17.yml
  .github/workflows/main-publish-ng16.yml
  .github/workflows/pr-ng17.yml
  .github/workflows/pre-release-publish-ng17.yml
  apps/doc/src/app/version-manager/versions.constants.ts
  package.json
  package.json.ng17
Labels: devOnly

#1319 fix: listing item selected item hover #1280
  apps/doc/src/app/components/listing-item/examples/with-instrumnets/listing-item-with-instruments-example.component.html
  apps/doc/src/app/components/listing-item/listing-item-example.component.html
  apps/doc/src/app/components/listing-item/listing-item-example.component.ts
  apps/doc/src/app/components/listing-item/listing-item-example.module.ts
  libs/components/src/lib/components/listing-item/listing-item.component.less
Labels: ready for test, testing_done

#1320 fix: listing item selected item hover for 4.0 #1280
  apps/doc/src/app/components/listing-item/examples/with-instrumnets/listing-item-with-instruments-example.component.html
  apps/doc/src/app/components/listing-item/listing-item-example.component.html
  apps/doc/src/app/components/listing-item/listing-item-example.component.ts
  apps/doc/src/app/components/listing-item/listing-item-example.module.ts
  libs/components/src/lib/components/listing-item/listing-item.component.less
Labels: ready for test, ready for dev, testing_done
