Repository zyfra/Prizm, pull requests merged in 2024-07, with the labels that each got.

#1844 fix(components/overlay): fix memory leak #1637 #1403
  apps/doc/src/app/components/table/examples/table-track-by-example/table-track-by-example.component.ts
  apps/doc/src/app/components/tree/examples/in-modal/tree-in-modal-example.component.ts
  apps/doc/src/app/tools/overlay/examples/custom-context/custom-context.component.ts
  apps/doc/src/app/tools/overlay/examples/fullscreen/template.ts
  apps/doc/src/app/tools/overlay/examples/global/template.ts
  apps/doc/src/app/tools/overlay/examples/relative/template.ts
  apps/doc/src/app/tools/overlay/examples/slide/template.ts
  apps/doc/src/app/tools/overlay/examples/with-component/template.ts
  libs/components/src/lib/abstract/dialog.service.ts
  libs/components/src/lib/components/dropdowns/dropdown-host/dropdown-host.component.ts
  libs/components/src/lib/components/toast/toast-control.ts
  libs/components/src/lib/directives/hint/hint.directive.ts
  libs/components/src/lib/modules/overlay/overlay-control.ts
  libs/components/src/lib/modules/overlay/overlay.service.ts
Labels: availability:tested, version:4

#1857 feat(chore): up version to 4.3.5
  apps/doc/src/app/version-manager/versions.constants.ts
Labels: devOnly, availability:reviewed, version:3

#1870 feat: up version of v4 to 4.3.6 #000
  apps/doc/src/app/version-manager/versions.constants.ts
Labels: availability:reviewed, availability:review, version:3

#1876 fix(components/tree): incorrect markup fix #1742
  apps/doc/src/app/components/tree/examples/component/folder.component.less
  libs/components/src/lib/components/tree/components/tree-item-content/tree-item-content.component.less
  libs/components/src/lib/components/tree/components/tree-item/tree-item.component.less
Labels: availability:review, version:3

#1872 fix(components/input): refactor select, multi-select and fixed with update value #1190
  apps/doc/src/app/components/input/input-chips/input-chips-example.component.html
  apps/doc/src/app/components/input/input-chips/input-chips-example.component.ts
  apps/doc/src/app/components/input/input-text/input.component.html
  apps/doc/src/app/components/input/input-text/input.component.ts
  libs/components/src/lib/components/dropdowns/multi-select/input-multi-select.component.html
  libs/components/src/lib/components/dropdowns/multi-select/input-multi-select.component.ts
  libs/components/src/lib/components/dropdowns/select/input-select.component.html
  libs/components/src/lib/components/dropdowns/select/input-select.component.ts
  libs/components/src/lib/components/input/common/base/input-ng-control.class.ts
  libs/components/src/lib/components/input/common/input-layout/input-layout.component.html
  libs/components/src/lib/components/input/common/input-layout/input-layout.component.ts
  libs/components/src/lib/components/input/input-date-relative/input-layout-date-relative.component.ts
  libs/components/src/lib/components/input/input-number/input-number.component.ts
  libs/components/src/lib/components/input/input-password/input-password-auxiliary-control.component.ts
  libs/components/src/lib/components/input/input-text/input-block.component.ts
  libs/components/src/lib/components/input/input-text/input-text.component.ts
  libs/components/src/lib/directives/confirm-popup/confirm-popup.directive.ts
  libs/components/src/lib/directives/hint/hint.directive.ts
Labels: availability:reviewed, availability:tested, version:4

#1865 fix(components/tab): add correct icon name to registry for right arrow #1860
  libs/components/src/lib/components/tabs/components/tab.component.html
  libs/components/src/lib/components/tabs/tabs.component.ts
Labels: state:ready, availability:tested, version:4

#1864 fix(components/tree): incorrect markup fix #1742
  apps/doc/src/app/components/tree/examples/component/folder.component.less
  libs/components/src/lib/components/tree/components/tree-item-content/tree-item-content.component.less
  libs/components/src/lib/components/tree/components/tree-item/tree-item.component.less
Labels: type:bc, availability:reviewed, availability:tested, version:4

#1839 fix(components/switcher): fix async support for selected switcher #1476
  apps/doc/src/app/components/switcher/examples/switcher-async-example/switcher-async-example.component.html
  apps/doc/src/app/components/switcher/examples/switcher-async-example/switcher-async-example.component.less
  apps/doc/src/app/components/switcher/examples/switcher-async-example/switcher-async-example.component.ts
  apps/doc/src/app/components/switcher/switcher-example.component.html
  apps/doc/src/app/components/switcher/switcher-example.component.ts
  apps/doc/src/app/components/switcher/switcher-example.module.ts
  libs/components/src/lib/components/switcher/switcher.component.ts
  libs/components/src/lib/components/switcher/swithcer.const.ts
Labels: state:ready, availability:tested, version:4

#1878 feat(doc): up versions to 3.15, 2.16, 1.19 in version manager #000
  apps/doc/src/app/version-manager/versions.constants.ts
Labels: devOnly, availability:reviewed, version:4

#1869 feat(chore): release 4.3.6 #000
  .github/workflows/beta-publish-ng17.yml
  .github/workflows/main-publish-ng17.yml
  .github/workflows/pre-release-publish-ng17.yml
  apps/doc/src/app/about-prizm/changelog/CHANGELOG.md
  apps/doc/src/app/components/input/input-chips/input-chips-example.component.html
  apps/doc/src/app/components/input/input-chips/input-chips-example.component.ts
  apps/doc/src/app/components/input/input-text/input.component.html
  apps/doc/src/app/components/input/input-text/input.component.ts
  apps/doc/src/app/version-manager/current.const.ts
  apps/doc/src/app/version-manager/current.const.ts.ng17
  apps/doc/src/app/version-manager/versions.constants.ts
  libs/ast/package.json
  libs/ast/package.json.ng17
  libs/charts/base/package.json
  libs/charts/base/package.json.ng17
  libs/components/package.json
  libs/components/package.json.ng17
  libs/components/src/lib/components/dropdowns/multi-select/input-multi-select.component.html
  libs/components/src/lib/components/dropdowns/multi-select/input-multi-select.component.ts
  libs/components/src/lib/components/dropdowns/select/input-select.component.html
  libs/components/src/lib/components/dropdowns/select/input-select.component.ts
  libs/components/src/lib/components/input/common/base/input-ng-control.class.ts
  libs/components/src/lib/components/input/common/input-layout/input-layout.component.html
  libs/components/src/lib/components/input/common/input-layout/input-layout.component.ts
  libs/components/src/lib/components/input/input-date-relative/input-layout-date-relative.component.ts
  libs/components/src/lib/components/input/input-number/input-number.component.ts
  libs/components/src/lib/components/input/input-password/input-password-auxiliary-control.component.ts
  libs/components/src/lib/components/input/input-text/input-block.component.ts
  libs/components/src/lib/components/input/input-text/input-text.component.ts
  libs/components/src/lib/directives/confirm-popup/confirm-popup.directive.ts
  libs/components/src/lib/directives/hint/hint.directive.ts
  libs/core/package.json
  libs/core/package.json.ng17
  libs/helpers/package.json
  libs/helpers/package.json.ng17
  libs/i18n/package.json
  libs/i18n/package.json.ng17
  libs/icons/base/package.json
  libs/icons/base/package.json.ng17
  libs/icons/flags/package.json
  libs/icons/flags/package.json.ng17
  libs/icons/loader/package.json
  libs/icons/loader/package.json.ng17
  libs/nxmv/package.json
  libs/nxmv/package.json.ng17
  libs/plugin/package.json
  libs/plugin/package.json.ng17
  libs/schematics/package.json
  libs/schematics/package.json.ng17
  libs/theme/package.json
  libs/theme/package.json.ng17
  package.json
  package.json.ng17
Labels: availability:reviewed, availability:tested, version:4

#1843 feat(components/paginator): update paginator dictionary #1840
  libs/components/src/lib/components/paginator/prizm-paginator.component.html
  libs/components/src/lib/components/paginator/prizm-paginator.component.ts
  libs/i18n/src/lib/interfaces/language.ts
  libs/i18n/src/lib/languages/english/paginator.ts
  libs/i18n/src/lib/languages/russian/paginator.ts
Labels: state:ready, availability:tested, version:3

#1875 Fix/switcher input order 1476 v3
  apps/doc/src/app/components/switcher/examples/switcher-async-example/switcher-async-example.component.html
  apps/doc/src/app/components/switcher/examples/switcher-async-example/switcher-async-example.component.less
  apps/doc/src/app/components/switcher/examples/switcher-async-example/switcher-async-example.component.ts
  apps/doc/src/app/components/switcher/switcher-example.component.html
  apps/doc/src/app/components/switcher/switcher-example.component.ts
  apps/doc/src/app/components/switcher/switcher-example.module.ts
  libs/components/src/lib/components/switcher/switcher.component.ts
  libs/components/src/lib/components/switcher/swithcer.const.ts
Labels: availability:reviewed, availability:tested, version:3

#1884 fix(components/input-text): incorrect behavior occurring in PrizmInputComponent when NgxMaskDirective is applied and the value changes from an empty state. #1190
  libs/components/src/lib/components/input/input-text/input-block.component.ts
  libs/components/src/lib/components/input/input-text/input-text.component.ts
  libs/components/src/lib/components/input/input-text/input-text.component.ts.ng14
  libs/components/src/lib/components/input/input-text/input-text.component.ts.ng15
  libs/components/src/lib/components/input/input-text/input-text.component.ts.ng16
Labels: availability:reviewed, availability:tested, version:3

#1877 release 3.15.0
  .github/workflows/beta-publish-ng14.yml
  .github/workflows/beta-publish-ng15.yml
  .github/workflows/beta-publish-ng16.yml
  .github/workflows/main-publish-ng14.yml
  .github/workflows/main-publish-ng15.yml
  .github/workflows/main-publish-ng16.yml
  .github/workflows/pre-release-publish-ng14.yml
  .github/workflows/pre-release-publish-ng15.yml
  .github/workflows/pre-release-publish-ng16.yml
  apps/doc/src/app/about-prizm/changelog/CHANGELOG.md
  apps/doc/src/app/components/switcher/examples/switcher-basic-example/switcher-basic-example.component.html
  apps/doc/src/app/components/switcher/examples/switcher-basic-example/switcher-basic-example.component.ts
  apps/doc/src/app/version-manager/current.const.ts.ng14
  apps/doc/src/app/version-manager/current.const.ts.ng15
  apps/doc/src/app/version-manager/current.const.ts.ng16
  apps/doc/src/app/version-manager/versions.constants.ts
  libs/ast/package.json.ng14
  libs/ast/package.json.ng15
  libs/ast/package.json.ng16
  libs/charts/base/package.json.ng14
  libs/charts/base/package.json.ng15
  libs/charts/base/package.json.ng16
  libs/components/package.json.ng14
  libs/components/package.json.ng15
  libs/components/package.json.ng16
  libs/components/src/lib/components/switcher/switcher.component.ts
  libs/core/package.json.ng14
  libs/core/package.json.ng15
  libs/core/package.json.ng16
  libs/helpers/package.json.ng14
  libs/helpers/package.json.ng15
  libs/helpers/package.json.ng16
  libs/i18n/package.json.ng14
  libs/i18n/package.json.ng15
  libs/i18n/package.json.ng16
  libs/icons/base/package.json.ng14
  libs/icons/base/package.json.ng15
  libs/icons/base/package.json.ng16
  libs/icons/flags/package.json.ng14
  libs/icons/flags/package.json.ng15
  libs/icons/flags/package.json.ng16
  libs/nxmv/package.json.ng14
  libs/nxmv/package.json.ng15
  libs/nxmv/package.json.ng16
  libs/plugin/package.json.ng14
  libs/plugin/package.json.ng15
  libs/plugin/package.json.ng16
  libs/schematics/package.json.ng14
  libs/schematics/package.json.ng15
  libs/schematics/package.json.ng16
  libs/theme/package.json.ng14
  libs/theme/package.json.ng15
  libs/theme/package.json.ng16
  package.json.ng14
  package.json.ng15
  package.json.ng16
Labels: state:ready, availability:reviewed, availability:tested, version:3

#1891 fix(components/switcher): write value error fixed #1890
  apps/doc/src/app/components/switcher/examples/switcher-basic-example/switcher-basic-example.component.html
  apps/doc/src/app/components/switcher/examples/switcher-basic-example/switcher-basic-example.component.ts
  libs/components/src/lib/components/switcher/switcher.component.ts
Labels: state:ready, availability:reviewed, availability:tested, version:4

#1897 fix(chore): fix pr builder #000
  .github/workflows/pr-ng17.yml
Labels: devOnly

#1896 fix(components/hint): re-draw after change context #000
  apps/doc/src/app/components/hint/examples/base/hint-base-example.component.html
  libs/components/src/lib/directives/hint/hint-container.component.ts
  libs/components/src/lib/directives/hint/hint.directive.ts
  libs/components/src/lib/directives/polymorph/directives/outlet.ts
  libs/components/src/lib/modules/overlay/overlay-control.ts
  libs/components/src/lib/modules/overlay/overlay.component.ts
Labels: state:ready, availability:reviewed, availability:tested

#1892 fix(components/dropdown-host): overlay undefined error occures on destroy #1889
  libs/components/src/lib/components/dropdowns/dropdown-host/dropdown-host.component.ts
Labels: state:ready, availability:reviewed, availability:tested, version:4

#1894 feat(doc): up version 4 in version manager #000
  apps/doc/src/app/version-manager/versions.constants.ts
Labels: devOnly, availability:reviewed, version:3

#1901 fix(chore): fixed pipelines for run from release after v4, v3 and fix linters and tests #1900 #1899 #1898
  .github/workflows/pre-released.yml
  .github/workflows/released.yml
  libs/components/src/lib/components/panel/panel.component.spec.ts
  libs/components/src/lib/services/cron/model.ts
  libs/helpers/src/lib/util/invert-object.spec.ts
  libs/helpers/src/lib/util/invert-object.ts
  libs/icons/loader/.eslintrc.json
  local/.eslintrc.json
Labels: devOnly, availability:reviewed

#1903 feat(chore): added action to auto describe pr #000
  .github/workflows/pr-describe.yaml
Labels: devOnly

#1904 feat(chore): pr ai reviewer #000
  .github/workflows/pr-describe.yaml
  .github/workflows/pr-review.yml
Labels: devOnly

#1893 Feat/release 4.3.7
  .github/workflows/beta-publish-ng17.yml
  .github/workflows/main-publish-ng17.yml
  .github/workflows/pre-release-publish-ng17.yml
  apps/doc/src/app/about-prizm/changelog/CHANGELOG.md
  apps/doc/src/app/version-manager/current.const.ts
  apps/doc/src/app/version-manager/versions.constants.ts
  libs/ast/package.json
  libs/charts/base/package.json
  libs/components/package.json
  libs/core/package.json
  libs/helpers/package.json
  libs/i18n/package.json
  libs/icons/base/package.json
  libs/icons/flags/package.json
  libs/icons/loader/package.json
  libs/nxmv/package.json
  libs/plugin/package.json
  libs/schematics/package.json
  libs/theme/package.json
  package.json
Labels: state:ready, availability:reviewed, availability:tested, version:4

#1909 feat(chore): added manual run for gitlab pipelines #000
  .gitlab-ci.yml
  package-lock.json
Labels: devOnly
