Repository zyfra/Prizm, pull requests merged in 2024-10, with the labels that each got.

#2068 feat(components/file-upload): added init files && custom actions #1832
  apps/doc/src/app/components/file-upload/examples/file-upload-custom-actions/file-upload-custom-actions.component.html
  apps/doc/src/app/components/file-upload/examples/file-upload-custom-actions/file-upload-custom-actions.component.less
  apps/doc/src/app/components/file-upload/examples/file-upload-custom-actions/file-upload-custom-actions.component.ts
  apps/doc/src/app/components/file-upload/examples/file-upload-with-init-files/file-upload-with-init-files.component.html
  apps/doc/src/app/components/file-upload/examples/file-upload-with-init-files/file-upload-with-init-files.component.less
  apps/doc/src/app/components/file-upload/examples/file-upload-with-init-files/file-upload-with-init-files.component.ts
  apps/doc/src/app/components/file-upload/file-upload-example.component.html
  apps/doc/src/app/components/file-upload/file-upload-example.component.ts
  apps/doc/src/app/components/file-upload/file-upload-example.module.ts
  apps/doc/src/app/components/file-upload/files.utils.ts
  apps/doc/src/assets/images/fileuploader/1.jpeg
  apps/doc/src/assets/images/fileuploader/2.jpeg
  apps/doc/src/assets/images/fileuploader/3.jpeg
  libs/components/src/lib/components/file-upload/file-upload.component.html
  libs/components/src/lib/components/file-upload/file-upload.component.less
  libs/components/src/lib/components/file-upload/file-upload.component.ts
  libs/components/src/lib/components/file-upload/types.ts
Labels: availability:reviewed, availability:tested

#2003 Fix/tab select scroll 1863 v5
  apps/doc/src/app/components/tabs/tabs-example.component.html
  apps/doc/src/app/components/tabs/tabs-example.component.ts
  libs/components/src/lib/components/listing-item/listing-item.component.less
  libs/components/src/lib/components/listing-item/listing-item.component.ts
  libs/components/src/lib/components/tabs/tabs.component.ts
Labels: availability:reviewed, availability:tested, version:5

#1955 fix(components/tabs): view not updated for activeTabindexChage when tabs overflows #1863
  apps/doc/src/app/components/tabs/tabs-example.component.html
  apps/doc/src/app/components/tabs/tabs-example.component.ts
  libs/components/src/lib/components/listing-item/listing-item.component.less
  libs/components/src/lib/components/listing-item/listing-item.component.ts
  libs/components/src/lib/components/tabs/tabs.component.ts
Labels: availability:reviewed, availability:tested, version:4, 4.6.0

#2130 feat(components/input-layout-date-time-range): add localization for time label #2128
  libs/components/src/lib/components/input/input-date-time-range/input-layout-date-time-range.component.html
  libs/components/src/lib/components/input/input-date-time-range/input-layout-date-time-range.component.ts
  libs/components/src/lib/tokens/i18n.ts
  libs/i18n/src/lib/interfaces/language.ts
  libs/i18n/src/lib/languages/english/english.ts
  libs/i18n/src/lib/languages/english/input-layout-date-time-range.ts
  libs/i18n/src/lib/languages/russian/input-layout-date-time-range.ts
  libs/i18n/src/lib/languages/russian/russian.ts
Labels: availability:reviewed, availability:tested, version:4

#2048 fix(components/input): padding changed for inner inputs #1763
  libs/components/src/lib/components/input/common/styles/input.component.less
Labels: availability:reviewed, availability:tested, version:5

#2054 fix(components/input-layout): correct icon for danger status #1916
  libs/components/src/lib/components/input/common/input-layout/input-layout.component.ts
Labels: availability:reviewed, availability:tested, version:5

#2056 fix(components/tabs): correct focus styles for contained tabs #1729
  libs/components/src/lib/components/tabs/components/tab.component.less
Labels: availability:reviewed, availability:tested, version:5

#2063 fix(components/navigation): register icons for navigation header and resolved #1836
  apps/doc/src/app/components/navigation/examples/navigation-basic-example/navigation-basic-example.component.html
  apps/doc/src/app/components/navigation/examples/navigation-basic-example/navigation-basic-example.component.ts
  libs/components/src/lib/components/header/components/prizm-header-module-btn/prizm-header-module-btn.component.ts
Labels: availability:reviewed, availability:tested, version:5

#2121 fix(components/input-control): on each update value emits two times #2087
  apps/doc/src/app/components/input/input-layout-date-time-range/examples/base/input-layout-date-time-range-base-example.component.ts
  libs/components/src/lib/components/input/common/base/input-ng-control.class.ts
Labels: availability:reviewed, availability:tested

#2126 fix(components/switcher): switcher button markup correction #2032
  libs/components/src/lib/components/switcher/components/switcher-item/switcher-item.component.less
Labels: availability:reviewed, availability:tested, version:5

#2129 feat(components/input-layout-date-time-range): add localization for time label #2128
  libs/components/src/lib/components/input/input-date-time-range/input-layout-date-time-range.component.html
  libs/components/src/lib/components/input/input-date-time-range/input-layout-date-time-range.component.ts
  libs/components/src/lib/tokens/i18n.ts
  libs/i18n/src/lib/interfaces/language.ts
  libs/i18n/src/lib/languages/english/english.ts
  libs/i18n/src/lib/languages/english/input-layout-date-time-range.ts
  libs/i18n/src/lib/languages/russian/input-layout-date-time-range.ts
  libs/i18n/src/lib/languages/russian/russian.ts
Labels: availability:reviewed, availability:tested, version:5

#2132 feat(components/tabs): show right button separately #1846
  libs/components/src/lib/components/tabs/tabs.component.html
Labels: availability:reviewed, availability:tested

#2135 feat(doc/dropdown-host): updated example select panel added custom vars for overlay #1027
  apps/doc/src/app/components/dropdowns/dropdown-host/dropdown-host.component.html
  apps/doc/src/app/components/dropdowns/dropdown-host/examples/select-panel-example/select-panel-example.component.html
  apps/doc/src/app/components/dropdowns/dropdown-host/examples/select-panel-example/select-panel-example.component.less
Labels: availability:reviewed, availability:tested

#2136 fix(components/multi-select): hint did not show after search #1980
  apps/doc/src/app/components/input/input-multi-select/examples/with-search/multi-select-with-search-example.component.ts
  libs/components/src/lib/components/dropdowns/multi-select/input-multi-select.component.html
  libs/components/src/lib/components/dropdowns/multi-select/input-multi-select.component.ts
Labels: availability:reviewed, availability:tested

#2143 feat(doc): update information about us
  apps/doc/src/app/about-prizm/design-system/design-system.component.html
  apps/doc/src/app/components/table/examples/table-data-source-example/table-data-source-example.component.html
  apps/doc/src/app/components/table/examples/table-server-sort-example/table-server-sort-example.component.html
  apps/doc/src/app/components/table/examples/table-sort-example/table-sort-example.component.html
Labels: availability:reviewed, availability:tested

#2124 feat(components/droprodown-trigger-click): new directive to trigger dropdown host and fix bug #1850
  apps/doc/src/app/components/dropdowns/dropdown-host/dropdown-host.component.html
  apps/doc/src/app/components/dropdowns/dropdown-host/dropdown-host.component.ts
  apps/doc/src/app/components/dropdowns/dropdown-host/dropdown-host.module.ts
  apps/doc/src/app/components/dropdowns/dropdown-host/examples/setup-module.md
  libs/components/src/lib/components/dropdowns/dropdown-host/dropdown-host-trigger-click.directive.ts
  libs/components/src/lib/components/dropdowns/dropdown-host/index.ts
  libs/components/src/lib/components/dropdowns/multi-select/input-multi-select.component.html
  libs/components/src/lib/components/dropdowns/multi-select/input-multi-select.component.ts
  libs/components/src/lib/components/dropdowns/select/input-select.component.less
  libs/components/src/lib/components/dropdowns/select/input-select.component.ts
  libs/components/src/lib/components/dropdowns/tree-multi-select/tree-multi-select.component.less
  libs/components/src/lib/components/dropdowns/tree-multi-select/tree-multi-select.component.ts
  libs/components/src/lib/components/dropdowns/tree-select/tree-select.component.html
  libs/components/src/lib/components/dropdowns/tree-select/tree-select.component.ts
  libs/components/src/lib/components/input/common/base/input-control.class.ts
  libs/components/src/lib/components/input/common/input-layout/input-layout.component.less
  libs/components/src/lib/components/input/common/input-layout/input-layout.component.ts
Labels: availability:reviewed, availability:tested

#2133 feat(components/navigation-menu): padding changed from 4px to 8px between text and other el #1633
  libs/components/src/lib/components/navigation-menu/components/prizm-navigation-menu-item/prizm-navigation-menu-item.component.less
Labels: availability:reviewed, availability:tested

#2100 4.6.0
  .github/PULL_REQUEST_TEMPLATE/prepare_release_for_4.md
  apps/doc/src/app/about-prizm/changelog/CHANGELOG.md
  apps/doc/src/app/components/input/input-tree-multi-select/examples/projection/tree-select-projection-example.component.html
  apps/doc/src/app/components/input/input-tree-multi-select/examples/setup-module.md
  apps/doc/src/app/components/input/input-tree-multi-select/input-tree-multi-select.component.html
  apps/doc/src/app/components/input/input-tree-multi-select/input-tree-multi-select.component.ts
  apps/doc/src/app/components/input/input-tree-multi-select/input-tree-multi-select.module.ts
  apps/doc/src/app/components/input/input-tree-select/input-tree-select.component.html
  apps/doc/src/app/components/input/input-tree-select/input-tree-select.component.ts
  apps/doc/src/app/components/input/input-tree-select/input-tree-select.module.ts
  apps/doc/src/app/version-manager/current.const.ts
  apps/doc/src/app/version-manager/versions.constants.ts
  libs/ast/package.json
  libs/charts/base/package.json
  libs/components/package.json
  libs/components/src/lib/components/chips/chips.component.html
  libs/components/src/lib/components/chips/chips.component.ts
  libs/components/src/lib/components/dropdowns/multi-select/input-multi-select.component.ts
  libs/components/src/lib/components/dropdowns/tree-multi-select/index.ts
  libs/components/src/lib/components/dropdowns/tree-multi-select/item/tree-multi-select-item.component.html
  libs/components/src/lib/components/dropdowns/tree-multi-select/item/tree-multi-select-item.component.less
  libs/components/src/lib/components/dropdowns/tree-multi-select/item/tree-multi-select-item.component.ts
  libs/components/src/lib/components/dropdowns/tree-multi-select/search/tree-multi-select-search.directive.ts
  libs/components/src/lib/components/dropdowns/tree-multi-select/tree-multi-select-checkbox.directive.ts
  libs/components/src/lib/components/dropdowns/tree-multi-select/tree-multi-select.component.ts
  libs/components/src/lib/components/dropdowns/tree-select/items/tree-select-item.component.ts
  libs/components/src/lib/components/dropdowns/tree-select/search/tree-select-search.directive.ts
  libs/components/src/lib/components/dropdowns/tree-select/tree-select-data-list-wrapper.component.html
  libs/components/src/lib/components/dropdowns/tree-select/tree-select-data-list-wrapper.component.ts
  libs/components/src/lib/components/dropdowns/tree-select/tree-select.component.ts
  libs/components/src/lib/components/tabs/components/tab.component.less
  libs/components/src/lib/directives/auto-focus/autofocus.directive.ts
  libs/components/src/lib/directives/auto-focus/autofocus.module.ts
  libs/components/src/lib/directives/confirm-popup/confirm-popup.directive.ts
  libs/components/src/lib/directives/confirm-popup/util.ts
  libs/components/src/lib/directives/focusable/focusable.directive.ts
  libs/components/src/lib/directives/focusable/focusable.module.ts
  libs/components/src/lib/directives/hint/hint.directive.ts
  libs/components/src/lib/directives/hint/index.ts
  libs/components/src/lib/directives/hint/token.ts
  libs/components/src/lib/pipes/time-constraints/time-constraints.pipe.ts
  libs/core/package.json
  libs/helpers/package.json
  libs/helpers/src/lib/directives/overflow/host/overflow-host.directive.ts
  libs/helpers/src/lib/directives/overflow/model.ts
  libs/helpers/src/lib/directives/overflow/overflow.service.ts
  libs/helpers/src/lib/directives/overflow/util.ts
  libs/i18n/package.json
  libs/icons/base/package.json
  libs/icons/flags/package.json
  libs/icons/loader/package.json
  libs/nxmv/package.json
  libs/plugin/package.json
  libs/schematics/package.json
  libs/theme/package.json
  package.json
Labels: availability:reviewed, availability:tested

#2119 feat(components/prizm-let): prizmLet directive declared deprecated #1880
  libs/helpers/src/lib/directives/let/let-context.service.ts
  libs/helpers/src/lib/directives/let/let.directive.ts
Labels: devOnly, availability:reviewed, version:5

#1794 fix(components/polymorph): remove type any for polymorph #1530
  libs/components/src/lib/components/button/button.component.html
  libs/components/src/lib/components/button/button.component.ts
  libs/components/src/lib/components/data-list/data-list.component.html
  libs/components/src/lib/components/dialogs/dialog/dialog.component.html
  libs/components/src/lib/components/dialogs/dialog/dialog.component.ts
  libs/components/src/lib/components/dropdowns/multi-select/input-multi-select.component.html
  libs/components/src/lib/components/dropdowns/select/input-select.component.ts
  libs/components/src/lib/components/table/directives/row-init.directive.ts
  libs/components/src/lib/directives/polymorph/classes/component.ts
  libs/components/src/lib/directives/polymorph/classes/context.ts
  libs/components/src/lib/directives/polymorph/classes/primitive-context.ts
  libs/components/src/lib/directives/polymorph/directives/outlet.old.ts
  libs/components/src/lib/directives/polymorph/directives/outlet.ts
  libs/components/src/lib/directives/polymorph/directives/template.ts
  libs/components/src/lib/directives/polymorph/types/content.ts
  libs/components/src/lib/directives/polymorph/types/handler.ts
  libs/components/src/lib/directives/polymorph/types/primitive.ts
  libs/components/src/lib/directives/polymorph/util.ts
  libs/helpers/src/lib/pipes/to-type/to-type.pipe.ts
Labels: availability:reviewed, availability:tested, version:5

#2134 feat(components/theme): prefer global theme if did not passed any value #1426
  libs/theme/src/lib/directive/theme/theme.directive.ts
Labels: availability:reviewed, availability:tested

#2127 fix(components/switcher): switcher button markup correction #2032
  libs/components/src/lib/components/switcher/components/switcher-item/switcher-item.component.less
Labels: availability:reviewed, availability:tested, version:4

#2058 fix(components/navigation): register icons for navigation header and example #1836 v4
  apps/doc/src/app/components/navigation/examples/navigation-basic-example/navigation-basic-example.component.html
  apps/doc/src/app/components/navigation/examples/navigation-basic-example/navigation-basic-example.component.ts
  libs/components/src/lib/components/header/components/prizm-header-module-btn/prizm-header-module-btn.component.ts
Labels: availability:reviewed, availability:tested, version:4

#2049 fix(components/input): padding changed for inner inputs #1763 v4
  libs/components/src/lib/components/input/common/styles/input.component.less
Labels: availability:reviewed, availability:tested, version:4

#2152 fix(components/button): fixed problem with confused test id for buttons with and without icons #2150
  libs/components/src/lib/components/button/button.component.ts
Labels: devOnly, availability:review, version:4

#2155 feat(components/input-select): hide chevron when disabled #1917
  libs/components/src/lib/components/dropdowns/multi-select/input-multi-select.component.less
  libs/components/src/lib/components/dropdowns/select/input-select.component.less
  libs/components/src/lib/components/dropdowns/tree-multi-select/tree-multi-select.component.less
Labels: availability:reviewed, availability:tested

#2123 fix(components/tabs): markup correction for tabs contained #000
  libs/components/src/lib/components/tabs/components/tab.component.less
Labels: availability:reviewed, availability:tested, version:4

#2154 feat(components/input-select): hide chevron when disabled #1917
  libs/components/src/lib/components/dropdowns/multi-select/input-multi-select.component.less
  libs/components/src/lib/components/dropdowns/select/input-select.component.less
  libs/components/src/lib/components/dropdowns/tree-multi-select/tree-multi-select.component.less
Labels: availability:review, availability:tested
