Repository zyfra/Prizm, pull requests merged in 2024-04, with the labels that each got.

#1536 fix: circular import by LinkComponent #1535
  libs/components/src/lib/components/link/link.component.ts
Labels: devOnly, availability:test, availability:review

#1578 fix: cron selected working with specified tabs #1494
  libs/components/src/lib/components/cron/cron.component.ts
Labels: availability:review

#1532 fix: search for server sort example #1107
  apps/doc/src/app/components/table/examples/table-server-sort-example/table-server-sort-example.component.ts
Labels: state:ready, availability:tested

#1533 fix: incorrect display of one unhidden column in column settings #1036
  libs/components/src/lib/components/column-settings/column-settings.component.ts
Labels: state:ready, availability:tested

#1538 fix: remove 'v3' prefix in theme-colors.component #1496
  apps/doc/src/app/guidelines/colors/components/theme-colors/theme-colors.component.html
Labels: state:ready, availability:tested

#1539 fix: fixed description of checkbox module import #1527
  apps/doc/src/app/components/checkbox/checkbox-example.component.html
  apps/doc/src/app/components/checkbox/examples/setup-module.md
Labels: state:ready, availability:tested

#1546 fix: changelog formatting #1499
  apps/doc/src/app/about-prizm/changelog/CHANGELOG.md
  apps/doc/src/app/about-prizm/changelog/changelog.component.less
Labels: state:ready, availability:tested

#1547 fix: fixed rows selector width #1466
  libs/components/src/lib/components/paginator/prizm-paginator.component.less
Labels: state:ready, availability:tested

#1549 fix: removed shadow variant duplicate #1434
  apps/doc/src/app/components/card/card.component.ts
Labels: state:ready, availability:tested

#1553 fix: removed hover and focus if loading #1485
  libs/components/src/lib/components/toggle/toggle.component.html
  libs/components/src/lib/components/toggle/toggle.component.less
Labels: state:ready, availability:tested

#1554 fix: file name display #1541
  libs/components/src/lib/components/file-upload/file-upload.component.html
  libs/components/src/lib/components/file-upload/file-upload.component.less
  libs/components/src/lib/components/file-upload/file-upload.component.ts
  libs/components/src/lib/components/file-upload/pipes/file-extension.pipe.ts
  libs/components/src/lib/components/file-upload/pipes/file-name.pipe.ts
Labels: state:ready, availability:tested

#1557 fix: hidden overflow for navigation titles #1510
  apps/doc/src/app/components/navigation/navigation-example.const.ts
  libs/components/src/lib/components/header/components/prizm-header-dropdown/prizm-header-dropdown.component.html
  libs/components/src/lib/components/header/components/prizm-header-dropdown/prizm-header-dropdown.component.less
  libs/components/src/lib/components/header/components/prizm-header-dropdown/prizm-header-dropdown.component.ts
  libs/components/src/lib/components/navigation/components/prizm-navigation-item-expandable/prizm-navigation-item-expandable.component.html
  libs/components/src/lib/components/navigation/components/prizm-navigation-item-expandable/prizm-navigation-item-expandable.component.ts
  libs/components/src/lib/components/navigation/components/prizm-navigation-item-simple/prizm-navigation-item-simple.component.html
  libs/components/src/lib/components/navigation/components/prizm-navigation-item-simple/prizm-navigation-item-simple.component.ts
Labels: state:ready, availability:tested

#1559 fix: fix scroll in sticky example #670
  apps/doc/src/app/components/sticky/examples/base/sticky-base-example.component.less
Labels: state:ready, availability:tested

#1562 fix: typography page changed #1497 #1498
  apps/doc/src/app/guidelines/typography/components/frame4/frame4.component.css
  apps/doc/src/app/guidelines/typography/components/frame4/frame4.component.html
  apps/doc/src/app/guidelines/typography/components/frame9/frame9.component.css
  apps/doc/src/app/guidelines/typography/components/frame9/frame9.component.html
  apps/doc/src/app/guidelines/typography/typography.component.html
  apps/doc/src/app/guidelines/typography/typography.module.ts
Labels: state:ready, availability:tested

#1588 fix: changed filesValidationErrors type #1371
  apps/doc/src/app/components/file-upload/examples/auto-upload/auto-upload.component.html
  apps/doc/src/app/components/file-upload/examples/auto-upload/auto-upload.component.ts
  apps/doc/src/app/components/file-upload/examples/basic/basic.component.html
  apps/doc/src/app/components/file-upload/examples/basic/basic.component.ts
  apps/doc/src/app/components/file-upload/examples/i18n/file-upload-i18n-example.component.html
  apps/doc/src/app/components/file-upload/examples/i18n/file-upload-i18n-example.component.ts
  apps/doc/src/app/components/file-upload/file-upload-example.component.html
  apps/doc/src/app/components/file-upload/file-upload-example.component.ts
  apps/doc/src/app/how-to-work/internationalization/examples/language-switcher/language-switcher-example.component.ts
Labels: state:ready, availability:tested

#1592 fix: auto deploy doc
  .github/workflows/deploy-main-doc-ng14.yml
  .github/workflows/deploy-main-doc-ng15.yml
  .github/workflows/deploy-main-doc-ng16.yml
  .github/workflows/deploy-main-doc-ng17.yml
  .github/workflows/main-publish-ng14.yml
  .github/workflows/main-publish-ng15.yml
  .github/workflows/main-publish-ng16.yml
  .github/workflows/main-publish-ng17.yml
  nx.json
  nx.json.ng14
  nx.json.ng15
  nx.json.ng16
  nx.json.ng17
Labels: state:ready, devOnly, availability:review

#1594 Fix/input number min error v4
  apps/doc/src/app/components/input/input-number/examples/input-number-min-max-example/input-number-min-max-example.component.html
  apps/doc/src/app/components/input/input-number/examples/input-number-min-max-example/input-number-min-max-example.component.less
  apps/doc/src/app/components/input/input-number/examples/input-number-min-max-example/input-number-min-max-example.component.ts
  apps/doc/src/app/components/input/input-number/input-number-example.component.html
  apps/doc/src/app/components/input/input-number/input-number-example.component.ts
  apps/doc/src/app/components/input/input-number/input-number-example.module.ts
  libs/components/src/lib/components/input/common/input-layout/input-layout.component.ts
  libs/components/src/lib/components/input/input-number/input-number.component.ts
Labels: state:ready, availability:tested

#1601 Feat: cron custom title #1431
  apps/doc/src/app/components/cron/cron.component.html
  apps/doc/src/app/components/cron/cron.component.ts
  libs/components/src/lib/components/cron/cron.component.html
  libs/components/src/lib/components/cron/cron.component.less
  libs/components/src/lib/components/cron/cron.component.ts
Labels: state:ready, availability:tested

#1544 fix: fixed description of checkbox module import #1527
  apps/doc/src/app/components/checkbox/checkbox-example.component.html
  apps/doc/src/app/components/checkbox/examples/setup-module.md
Labels: state:ready, availability:tested

#1550 fix: removed shadow variant duplicate #1434
  apps/doc/src/app/components/card/card.component.ts
Labels: state:ready, availability:tested

#1552 fix: removed hover and focus if loading #1485
  libs/components/src/lib/components/toggle/toggle.component.html
  libs/components/src/lib/components/toggle/toggle.component.less
Labels: state:ready, availability:tested

#1556 fix: hidden overflow for navigation titles #1510
  apps/doc/src/app/components/navigation/navigation-example.const.ts
  libs/components/src/lib/components/header/components/prizm-header-dropdown/prizm-header-dropdown.component.html
  libs/components/src/lib/components/header/components/prizm-header-dropdown/prizm-header-dropdown.component.less
  libs/components/src/lib/components/header/components/prizm-header-dropdown/prizm-header-dropdown.component.ts
  libs/components/src/lib/components/navigation/components/prizm-navigation-item-expandable/prizm-navigation-item-expandable.component.html
  libs/components/src/lib/components/navigation/components/prizm-navigation-item-expandable/prizm-navigation-item-expandable.component.ts
  libs/components/src/lib/components/navigation/components/prizm-navigation-item-simple/prizm-navigation-item-simple.component.html
  libs/components/src/lib/components/navigation/components/prizm-navigation-item-simple/prizm-navigation-item-simple.component.ts
Labels: state:ready, availability:tested

#1563 fix: typography page changed #1497 #1498
  apps/doc/src/app/guidelines/typography/components/frame4/frame4.component.css
  apps/doc/src/app/guidelines/typography/components/frame4/frame4.component.html
  apps/doc/src/app/guidelines/typography/components/frame9/frame9.component.css
  apps/doc/src/app/guidelines/typography/components/frame9/frame9.component.html
  apps/doc/src/app/guidelines/typography/typography.component.html
  apps/doc/src/app/guidelines/typography/typography.module.ts
Labels: state:ready, availability:tested

#1576 feat: cron custom title #1431
  apps/doc/src/app/components/cron/cron.component.html
  apps/doc/src/app/components/cron/cron.component.ts
  libs/components/src/lib/components/cron/cron.component.html
  libs/components/src/lib/components/cron/cron.component.less
  libs/components/src/lib/components/cron/cron.component.ts
Labels: state:ready, availability:tested

#1581 Fix/sticky scroll 3.13
  apps/doc/src/app/components/sticky/examples/base/sticky-base-example.component.less
Labels: state:ready, availability:tested

#1582 Fix/column settings show last 3.13
  libs/components/src/lib/components/column-settings/column-settings.component.ts
Labels: state:ready, availability:tested

#1583 fix: search for server sort example #1107
  apps/doc/src/app/components/table/examples/table-server-sort-example/table-server-sort-example.component.ts
Labels: state:ready, availability:tested

#1584 fix: input number manual input works incorrect if min set #1580 v3
  apps/doc/src/app/components/input/input-number/examples/input-number-min-max-example/input-number-min-max-example.component.html
  apps/doc/src/app/components/input/input-number/examples/input-number-min-max-example/input-number-min-max-example.component.less
  apps/doc/src/app/components/input/input-number/examples/input-number-min-max-example/input-number-min-max-example.component.ts
  apps/doc/src/app/components/input/input-number/input-number-example.component.html
  apps/doc/src/app/components/input/input-number/input-number-example.component.ts
  apps/doc/src/app/components/input/input-number/input-number-example.module.ts
  libs/components/src/lib/components/input/common/input-layout/input-layout.component.ts
  libs/components/src/lib/components/input/input-number/input-number.component.ts
Labels: state:ready, availability:tested

#1586 Feat/charts update colors v3
  apps/doc/src/app/charts/bar/bar.component.html
  apps/doc/src/app/charts/bar/examples/base/prizm-charts-bar-example.component.html
  apps/doc/src/app/charts/bar/examples/base/prizm-charts-bar-example.component.ts
  apps/doc/src/app/charts/bar/examples/group/prizm-charts-group-bar-example.component.html
  apps/doc/src/app/charts/bar/examples/group/prizm-charts-group-bar-example.component.ts
  apps/doc/src/app/charts/bar/examples/stacked/prizm-charts-stacked-bar-example.component.html
  apps/doc/src/app/charts/bar/examples/stacked/prizm-charts-stacked-bar-example.component.ts
  apps/doc/src/app/charts/gauge/gauge.component.html
  apps/doc/src/app/charts/pie/pie.component.html
  apps/doc/src/app/charts/scatter/examples/base/prizm-charts-scatter-example.component.ts
  apps/doc/src/app/charts/scatter/scatter.component.ts
  apps/doc/src/app/charts/waterfall/examples/base/prizm-charts-waterfall-example.component.ts
  apps/doc/src/app/charts/waterfall/waterfall.component.ts
  libs/charts/base/src/lib/theme/base-options.const.ts
  libs/charts/base/src/lib/theme/dark.const.ts
  libs/charts/base/src/lib/theme/light.const.ts
  libs/charts/base/src/lib/theme/types.ts
  libs/doc/base/src/lib/components/documentation/documentation.component.html
  libs/doc/base/src/lib/components/documentation/documentation.module.ts
  libs/theme/src/styles/theme/v3/default.less
  package-lock.json
Labels: state:ready, availability:tested

#1591 fix: changed filesValidationErrors type in examples #1371
  apps/doc/src/app/components/file-upload/examples/auto-upload/auto-upload.component.html
  apps/doc/src/app/components/file-upload/examples/auto-upload/auto-upload.component.ts
  apps/doc/src/app/components/file-upload/examples/basic/basic.component.html
  apps/doc/src/app/components/file-upload/examples/basic/basic.component.ts
  apps/doc/src/app/components/file-upload/examples/i18n/file-upload-i18n-example.component.html
  apps/doc/src/app/components/file-upload/examples/i18n/file-upload-i18n-example.component.ts
  apps/doc/src/app/components/file-upload/file-upload-example.component.html
  apps/doc/src/app/components/file-upload/file-upload-example.component.ts
  apps/doc/src/app/how-to-work/internationalization/examples/language-switcher/language-switcher-example.component.ts
Labels: state:ready, availability:tested

#1603 fix: fixed rows selector width #1466
  libs/components/src/lib/components/paginator/prizm-paginator.component.less
Labels: state:ready, availability:tested

#1610 feat: checklist for release 4x version
  .github/PULL_REQUEST_TEMPLATE/prepare_release_for_4.md
Labels: devOnly, availability:test

#1613 feat: checklist for release 3x version v4
  .github/PULL_REQUEST_TEMPLATE/prepare_release_for_3.md.md
Labels: devOnly, availability:test, availability:review

#1611 feat: checklist for release 4x version for v3
  .github/PULL_REQUEST_TEMPLATE/prepare_release_for_4.md
Labels: state:ready, devOnly

#1604 feat: release 4.2.0
  .github/PULL_REQUEST_TEMPLATE/prepare_release_for_3.md
  .github/workflows/beta-publish-ng17.yml
  .github/workflows/main-publish-ng17.yml
  .github/workflows/pre-release-publish-ng17.yml
  apps/doc/src/app/about-prizm/changelog/CHANGELOG.md
  apps/doc/src/app/version-manager/current.const.ts
  apps/doc/src/app/version-manager/current.const.ts.ng17
  apps/doc/src/app/version-manager/versions.constants.ts
  libs/ast/package.json
  libs/ast/package.json.ng17
  libs/charts/base/package.json
  libs/charts/base/package.json.ng17
  libs/components/package.json
  libs/components/package.json.ng17
  libs/components/src/lib/components/cron/cron.component.html
  libs/components/src/lib/components/cron/cron.component.less
  libs/components/src/lib/components/file-upload/file-upload.component.ts
  libs/core/package.json
  libs/core/package.json.ng17
  libs/helpers/package.json
  libs/helpers/package.json.ng17
  libs/i18n/package.json
  libs/i18n/package.json.ng17
  libs/icons/base/package.json
  libs/icons/base/package.json.ng17
  libs/icons/flags/package.json
  libs/icons/flags/package.json.ng17
  libs/icons/loader/package.json
  libs/nxmv/package.json
  libs/nxmv/package.json.ng17
  libs/plugin/package.json
  libs/plugin/package.json.ng17
  libs/schematics/package.json
  libs/schematics/package.json.ng17
  libs/theme/package.json
  libs/theme/package.json.ng17
  package.json
  package.json.ng17
Labels: availability:tested

#1629 fix: update native time value for min-max date time limit #1618
  libs/components/src/lib/components/input/input-date-time/input-layout-date-time.component.ts
Labels: state:ready, availability:review, availability:tested
