Repository zyfra/Prizm, pull requests merged in 2025-01, with the labels that each got.

#2286 fix(chore): package lock files was broken in v4 #0
  package-lock.json
  package.json
Labels: devOnly

#2282 feat(components/confirm-dialog): add translations for default button texts #2209
  apps/doc/src/app/components/dialogs/confirm-dialog/examples/footer-template/footer-template.component.html
  libs/components/src/lib/components/dialogs/confirm-dialog/confirm-dialog.component.html
  libs/components/src/lib/components/dialogs/confirm-dialog/confirm-dialog.component.less
  libs/components/src/lib/components/dialogs/confirm-dialog/confirm-dialog.component.ts
  libs/components/src/lib/components/dialogs/confirm-dialog/confirm-dialog.service.ts
  libs/components/src/lib/components/dialogs/sidebar/sidebar.component.html
  libs/components/src/lib/components/dialogs/sidebar/sidebar.component.ts
  libs/components/src/lib/components/dialogs/sidebar/sidebar.service.ts
  libs/components/src/lib/directives/confirm-popup/confirm-popup-container.component.html
  libs/components/src/lib/directives/confirm-popup/confirm-popup-container.component.ts
  libs/components/src/lib/directives/confirm-popup/util.ts
  libs/components/src/lib/tokens/i18n.ts
  libs/i18n/src/lib/interfaces/language.ts
  libs/i18n/src/lib/languages/english/dialogs.ts
  libs/i18n/src/lib/languages/english/english.ts
  libs/i18n/src/lib/languages/english/index.ts
  libs/i18n/src/lib/languages/russian/dialogs.ts
  libs/i18n/src/lib/languages/russian/index.ts
  libs/i18n/src/lib/languages/russian/russian.ts
Labels: availability:reviewed, availability:tested, version:5

#2244 feat(components/card): add card options provider #1669
  apps/doc/src/app/components/card/card.component.html
  apps/doc/src/app/components/card/card.component.ts
  apps/doc/src/app/components/card/card.module.ts
  apps/doc/src/app/components/card/examples/shadow-provider/card-shadow-provider-example.component.html
  apps/doc/src/app/components/card/examples/shadow-provider/card-shadow-provider-example.component.ts
  libs/components/src/lib/components/card/card-options.ts
  libs/components/src/lib/components/card/card.component.ts
  libs/components/src/lib/components/card/index.ts
Labels: availability:reviewed, availability:tested, version:5

#2291 feat(chore): release 5.5.0
  .github/PULL_REQUEST_TEMPLATE/prepare_release_for_5.md
  apps/doc/src/app/about-prizm/changelog/CHANGELOG.md
  apps/doc/src/app/components/dialogs/confirm-dialog/examples/footer-template/footer-template.component.ts
  apps/doc/src/app/version-manager/current.const.ts
  apps/doc/src/app/version-manager/versions.constants.ts
  libs/addons/query-builder/package.json
  libs/ast/package.json
  libs/charts/base/package.json
  libs/components/package.json
  libs/components/src/lib/components/dialogs/confirm-dialog/confirm-dialog.component.html
  libs/components/src/lib/components/dialogs/confirm-dialog/confirm-dialog.component.less
  libs/components/src/lib/directives/confirm-popup/confirm-popup-container.component.less
  libs/core/package.json
  libs/helpers/package.json
  libs/i18n/package.json
  libs/icons/base/package.json
  libs/icons/flags/package.json
  libs/icons/loader/package.json
  libs/nxmv/package.json
  libs/plugin/package.json
  libs/schematics/package.json
  libs/schematics/src/ng-add/consts.ts
  libs/theme/package.json
  local/package.json
  nxmv.json
  package.json
  package.json.ng18
Labels: availability:reviewed, availability:tested

#2307 fix(components/dialogs): test id postfix setters override for dialogs #2304
  apps/doc/src/app/addons/query-builder/examples/query-builder-basic-example/query-builder-basic-example.component.html
  apps/doc/src/app/components/dialogs/confirm-dialog/examples/base/base.component.html
  apps/doc/src/app/components/dialogs/confirm-dialog/examples/base/base.component.ts
  apps/doc/src/app/components/dialogs/dialog/examples/base/dialog-base-example.component.html
  apps/doc/src/app/components/dialogs/dialog/examples/base/dialog-base-example.component.ts
  apps/doc/src/app/components/dialogs/sidebar/examples/base/base.component.html
  apps/doc/src/app/components/dialogs/sidebar/examples/base/base.component.ts
  apps/doc/src/app/components/radio/examples/radio-button-basic-example/radio-button-basic-example.component.html
  apps/doc/src/app/components/radio/examples/radio-button-basic-example/radio-button-basic-example.component.ts
  apps/doc/src/app/components/splitter/splitter-example.component.html
  apps/doc/src/app/components/table/examples/table-basic-example/table-basic-example.component.html
  libs/addons/query-builder/src/lib/query-builder.component.ts
  libs/components/src/lib/components/dialogs/confirm-dialog/confirm-dialog.component.ts
  libs/components/src/lib/components/dialogs/dialog/dialog.component.ts
  libs/components/src/lib/components/dialogs/dialog/dialog.models.ts
  libs/components/src/lib/components/dialogs/sidebar/sidebar.component.ts
  libs/components/src/lib/components/radio/prizm-radio-button.component.ts
  libs/components/src/lib/components/table/directives/table.directive.ts
  libs/components/src/lib/components/table/directives/thead.directive.ts
  libs/components/src/lib/components/table/tbody/tbody.component.ts
  libs/components/src/lib/components/table/td/td.component.ts
  libs/components/src/lib/components/table/th-group/th-group.component.ts
  libs/components/src/lib/components/table/th/th.component.ts
  libs/components/src/lib/components/table/tr/tr.component.ts
  libs/doc/base/src/lib/components/documentation/documentation.component.html
  libs/helpers/src/lib/directives/index.ts
  libs/helpers/src/lib/directives/test-id/index.ts
  libs/helpers/src/lib/directives/test-id/test-id.ts
Labels: availability:reviewed, availability:tested, version:5

#2317 fix(chore): wrong lock file check in ci #0
  .github/workflows/pr-ng18.yml
Labels: devOnly

#2314 fix(components/switcher): wrong set touched state #2180
  libs/components/src/lib/components/switcher/components/switcher-item/switcher-item.component.html
  libs/components/src/lib/components/switcher/components/switcher-item/switcher-item.component.ts
  libs/components/src/lib/components/switcher/directives/switcher-control.directive.ts
Labels: availability:reviewed, availability:tested

#2315 fix(components/accordion): cursor pointer on body #2141
  libs/components/src/lib/components/accordion/components/accordion-item/accordion-item.component.less
Labels: availability:reviewed, availability:tested
