Repository zyfra/Prizm, pull requests merged in 2025-02, with the labels that each got.

#2306 feat(components/tree): add input func to detect tree node expand state #2289
  apps/doc/src/app/components/tree/examples/function-access/function-access-example.component.html
  apps/doc/src/app/components/tree/examples/function-access/function-access-example.component.ts
  apps/doc/src/app/components/tree/tree.component.html
  apps/doc/src/app/components/tree/tree.component.ts
  apps/doc/src/app/components/tree/tree.module.ts
  libs/components/src/lib/components/tree/directives/tree-controller.directive.ts
Labels: availability:reviewed, availability:tested, version:5

#2346 5.7.0
  .github/PULL_REQUEST_TEMPLATE/prepare_release_for_5.md
  apps/doc/src/app/about-prizm/changelog/CHANGELOG.md
  apps/doc/src/app/version-manager/current.const.ts
  apps/doc/src/app/version-manager/versions.constants.ts
  libs/addons/query-builder/package.json
  libs/ast/package.json
  libs/charts/base/package.json
  libs/components/package.json
  libs/core/package.json
  libs/helpers/package.json
  libs/i18n/package.json
  libs/icons/base/package.json
  libs/icons/flags/package.json
  libs/icons/loader/package.json
  libs/nxmv/package.json
  libs/plugin/package.json
  libs/schematics/package.json
  libs/schematics/src/ng-add/consts.ts
  libs/theme/package.json
  local/package.json
  nxmv.json
  package.json
Labels: availability:reviewed, availability:tested

#2339 fix(components/tab): button disappear after click from dropdown #2096
  libs/components/src/lib/components/tabs/tabs.component.ts
Labels: availability:reviewed, availability:tested

#2344 fix(doc/dropdown-host): add disable property to live demo #2343
  apps/doc/src/app/components/dropdowns/dropdown-host/dropdown-host.component.html
Labels: availability:review, availability:tested, version:5

#2313 feat(components/time-picker): add only hour edit mode #2298
  apps/doc/src/app/components/time-picker/time-picker-example.component.html
  apps/doc/src/app/components/time-picker/time-picker-example.component.ts
  libs/components/src/lib/components/internal/primitive-time-pagination/primitive-time-pagination.component.html
  libs/components/src/lib/components/internal/primitive-time-pagination/primitive-time-pagination.component.less
  libs/components/src/lib/components/internal/primitive-time-pagination/primitive-time-pagination.component.ts
  libs/components/src/lib/components/time-picker/time-picker.component.ts
Labels: availability:reviewed, availability:tested, version:5

#2328 fix(components/day-time-range): fix the "to" time in the toLocalNativeDate function #2326
  libs/components/src/lib/@core/date-time/day-time-range.ts
Labels: availability:reviewed, availability:tested

#2333 fix(components/cron): double emits change event #2113
  apps/doc/src/app/components/cron/cron.component.ts
  libs/components/src/lib/components/cron/cron.component.ts
Labels: availability:reviewed, availability:tested

#2334 fix(components/tabs): wrong display right button on zoomed browser viewport #988
  libs/components/src/lib/components/tabs/tabs.component.ts
Labels: availability:reviewed, availability:tested

#2342 fix(doc): add missing unsubscriptions
  apps/doc/src/app/app.component.ts
  apps/doc/src/app/components/dialogs/confirm-dialog/confirm.component.ts
  apps/doc/src/app/components/dialogs/dialog/dialog-example.component.ts
  apps/doc/src/app/components/dialogs/dialog/examples/base/dialog-base-example.component.ts
  apps/doc/src/app/components/dialogs/dialog/examples/custom-service/dialog-custom-service-example.component.ts
  apps/doc/src/app/components/dialogs/dialog/examples/outher-header/dialog-outher-header-example.component.ts
  apps/doc/src/app/components/dialogs/dialog/examples/result/dialog-result-handling-example.component.ts
  apps/doc/src/app/components/dialogs/dialog/examples/with-buttons/dialog-with-buttons-example.component.ts
  apps/doc/src/app/components/dialogs/dialog/examples/with-parent/dialog-with-parent-example.component.ts
  apps/doc/src/app/components/dialogs/sidebar/examples/base/base.component.ts
  apps/doc/src/app/components/dialogs/sidebar/examples/custom-button/custom-button-template.component.ts
  apps/doc/src/app/components/dialogs/sidebar/examples/custom-close-guard/custom-close-guard.component.ts
  apps/doc/src/app/components/dialogs/sidebar/examples/custom-header-template/custom-header-template.component.ts
  apps/doc/src/app/components/dialogs/sidebar/examples/custom-wrapper-style/custom-wrapper-style.component.ts
  apps/doc/src/app/components/dialogs/sidebar/examples/hidden-footer/hidden-footer.component.ts
  apps/doc/src/app/components/dialogs/sidebar/examples/only-confirm-button/only-confirm-button.component.ts
  apps/doc/src/app/components/dialogs/sidebar/examples/top-bottom/top-bottom.component.ts
  apps/doc/src/app/components/dialogs/sidebar/examples/with-parent/with-parent.component.ts
  apps/doc/src/app/components/dialogs/sidebar/sidebar.component.ts
  apps/doc/src/app/components/file-upload/examples/auto-upload/auto-upload.component.ts
  apps/doc/src/app/components/file-upload/examples/basic/basic.component.ts
  apps/doc/src/app/components/file-upload/examples/i18n/file-upload-i18n-example.component.ts
  apps/doc/src/app/components/file-upload/file-upload-example.component.ts
  apps/doc/src/app/components/input/combobox/examples/with-backend-search/combobox-with-backend-search-example.component.ts
  apps/doc/src/app/components/table-advanced/examples/table-search-example/table-search-example.component.ts
  apps/doc/src/app/components/table/examples/table-search-example/table-search-example.component.ts
  apps/doc/src/app/how-to-work/internationalization/examples/language-switcher/language-switcher-example.component.ts
  apps/doc/src/app/logo/logo.component.ts
  libs/components/src/lib/components/dropdowns/combobox/combobox-missing-value-handler.directive.ts
Labels: availability:reviewed, availability:tested, version:5

#2341 fix(components/multi-select): chevron overlaps input for layout with status #1744
  libs/components/src/lib/components/chips/chips.component.html
  libs/components/src/lib/components/chips/chips.component.ts
  libs/components/src/lib/components/dropdowns/multi-select/input-multi-select.component.ts
  libs/components/src/lib/components/dropdowns/tree-multi-select/tree-multi-select.component.ts
Labels: availability:reviewed, availability:tested, version:5

#2332 feat(doc/dropdown-host): added example with nested dropdown #2329
  apps/doc/src/app/components/dropdowns/dropdown-host/dropdown-host.component.html
  apps/doc/src/app/components/dropdowns/dropdown-host/dropdown-host.component.ts
  apps/doc/src/app/components/dropdowns/dropdown-host/dropdown-host.module.ts
  apps/doc/src/app/components/dropdowns/dropdown-host/examples/nested/template.html
  apps/doc/src/app/components/dropdowns/dropdown-host/examples/nested/template.ts
  libs/components/src/lib/directives/zone-event/zone-event.directive.ts
  libs/components/src/lib/directives/zone-event/zone-event.service.ts
Labels: availability:review, availability:tested

#2359 fix(chore): stackblitz version for v5 #0
  apps/doc/src/app/code-demo/code-demo.service.ts
  apps/doc/src/app/code-demo/files/src/app/shared.module.ts
  apps/doc/src/app/code-demo/files/src/app/shared.module.ts.template
  apps/doc/src/app/code-demo/util.ts
  libs/doc/base/src/lib/components/example/example.component.html
  libs/doc/base/src/lib/components/example/example.component.ts
  libs/doc/base/src/lib/services/demo/model.ts
  libs/theme/src/styles/styles.less
Labels: devOnly

#2360 5.8.0
  .github/PULL_REQUEST_TEMPLATE/prepare_release_for_5.md
  .github/workflows/beta-publish-ng18.yml
  .github/workflows/pre-release-publish-ng18.yml
  .github/workflows/pre-release-publish-ng18.yml.ng18
  apps/doc/src/app/about-prizm/changelog/CHANGELOG.md
  apps/doc/src/app/version-manager/current.const.ts
  apps/doc/src/app/version-manager/versions.constants.ts
  libs/addons/query-builder/package.json
  libs/ast/package.json
  libs/charts/base/package.json
  libs/components/package.json
  libs/components/src/lib/components/time-picker/time-picker.component.ts
  libs/core/package.json
  libs/helpers/package.json
  libs/i18n/package.json
  libs/icons/base/package.json
  libs/icons/flags/package.json
  libs/icons/loader/package.json
  libs/nxmv/package.json
  libs/plugin/package.json
  libs/schematics/package.json
  libs/schematics/src/ng-add/consts.ts
  libs/theme/package.json
  local/package.json
  nxmv.json
  package.json
Labels: availability:reviewed, availability:tested
